<Workspace Version="1.2.3.573" X="-420.009258237187" Y="-275.82697555875" zoom="1.78359936238281" ScaleFactor="1" Name="InteriorElevation.GetCropRegion" Description="This will obtain the crop region from an Interior Elevation View Type." ID="a5550842-daa4-4bcb-940f-7aff6fd57d6a" Category="Rhythm.Revit.Views.InteriorElevation">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="5b6cf779-58f4-43be-9604-e4ae7d54dd39" type="PythonNodeModels.PythonNode" nickname="Python Script" x="681.111081187586" y="327.029375577582" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Copyright(c) 2017, john pierson
# @60secondrevit, http://sixtysecondrevit.com
import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

from System.Collections.Generic import *

# Import RevitAPI
clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

#The inputs to this node will be stored as a list in the IN variable.
dataEnteringNode = IN

#unwrap all elements to use with API
items = UnwrapElement(IN[0])
TransactionManager.Instance.EnsureInTransaction(doc)
#get the associated view id with the viewport and select the thing
typelist = list()
for i in items:
	try:
		typelist.append(doc.GetElement(ElementId(int(str(i.Id))-1)))
	except:
		typelist.append(doc.GetElement(ElementId(int(str(i.Id))-1)))

# "End" the transaction
TransactionManager.Instance.TransactionTaskDone()

#Assign your output to the OUT variable
OUT = typelist</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="c8030624-afdb-46a5-bec7-6ee60cb91a95" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="165.961742575267" y="307.146877887911" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="interiorElevations" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="53e4361f-df24-4ff1-a78c-89cc782b3176" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="397.117502310329" y="316.196679867994" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Flatten({items});" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="880631b2-1e31-4518-8cdd-d534b8d1e0ec" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="846.047206599814" y="330.134102970357" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="cropRegions" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="5b6cf779-58f4-43be-9604-e4ae7d54dd39" start_index="0" end="880631b2-1e31-4518-8cdd-d534b8d1e0ec" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c8030624-afdb-46a5-bec7-6ee60cb91a95" start_index="0" end="53e4361f-df24-4ff1-a78c-89cc782b3176" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="53e4361f-df24-4ff1-a78c-89cc782b3176" start_index="0" end="5b6cf779-58f4-43be-9604-e4ae7d54dd39" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-0.440881588928534" eyeY="5.63070114836623" eyeZ="4.60123366597143" lookX="0.948988584958638" lookY="-1.49714361767638" lookZ="-2.01767504289907" upX="0.155987100211542" upY="0.930417567982024" upZ="-0.331649172708163" />
  </Cameras>
</Workspace>