<Workspace Version="1.2.1.3083" X="-320.965381393078" Y="-303.657997673201" zoom="1.24844365397223" Name="PostableCommand.Default3DView" Description="This will set the active view as the default (little house) 3D view." ID="66f6066b-239e-4ec7-ad5e-f5f6010428df" Category="Rhythm.Revit.Application.PostableCommand">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="5b1bd9f7-0638-4509-942c-e87d87e3877c" type="PythonNodeModels.PythonNode" nickname="Python Script" x="509.840197851231" y="391.955957263909" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc =  DocumentManager.Instance.CurrentDBDocument
uidoc = DocumentManager.Instance.CurrentUIDocument
app = DocumentManager.Instance.CurrentUIApplication.Application
uiapp = DocumentManager.Instance.CurrentUIApplication

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import *
clr.AddReference("RevitAPIUI")
from Autodesk.Revit.UI import *
output = []
pCmd = RevitCommandId.LookupPostableCommandId(PostableCommand.Default3DView)
if IN[0] == True:
	uiapp.PostCommand(pCmd)
	output = True
else :
	output = 'set runit to true'
OUT = output</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="ed5c277a-5cfa-4a2f-a39e-2371a591680e" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="253.725081772393" y="389.965502476742" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="RunIt : bool = false" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="ce698709-9c6f-4f7c-a90a-7f7e5a85e4fd" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="775.880630415518" y="389.147638977416" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="toggle" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="5b1bd9f7-0638-4509-942c-e87d87e3877c" start_index="0" end="ce698709-9c6f-4f7c-a90a-7f7e5a85e4fd" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ed5c277a-5cfa-4a2f-a39e-2371a591680e" start_index="0" end="5b1bd9f7-0638-4509-942c-e87d87e3877c" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>