<Workspace Version="1.3.1.1736" X="56.9656705588553" Y="282.523205264579" zoom="1.33823125" ScaleFactor="1" Name="DisplayUnit.ToInternalUnit" Description="Converts a value from a given display unit to Revit's internal unit" ID="7f19e4a8-c7e0-4041-b57b-0b8d04a99b2c" Category="Clockwork.Revit.Units.Actions">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="7d7a657f-b39f-45b1-8b50-3c9eeea5736b" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="195.521857208909" y="43.0575693608339" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="val : double" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="fdbfde34-e543-4bdf-9669-98f7b208228c" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="673.521857208909" y="72.0575693608339" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="val" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="faff8c1b-6ec0-44d3-99c6-e8eef995ab07" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="195.521857208909" y="127.057569360834" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="displayUnitType" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <PythonNodeModels.PythonNode guid="c2041798-1d3a-4efe-b094-de42c6c7af95" type="PythonNodeModels.PythonNode" nickname="Python Script" x="449.521857208909" y="72.0575693608339" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

def ToInternalUnits(val, unittype):
	if str(dispunit.GetType()) == "Autodesk.Revit.DB.DisplayUnitType":
		return UnitUtils.ConvertToInternalUnits(val,unittype)
	else: return None

vals = IN[0]
dispunit = IN[1]

if isinstance(IN[0], list): OUT = [ToInternalUnits(x, dispunit) for x in vals]
else: OUT = ToInternalUnits(vals, dispunit)</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="7d7a657f-b39f-45b1-8b50-3c9eeea5736b" start_index="0" end="c2041798-1d3a-4efe-b094-de42c6c7af95" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="faff8c1b-6ec0-44d3-99c6-e8eef995ab07" start_index="0" end="c2041798-1d3a-4efe-b094-de42c6c7af95" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c2041798-1d3a-4efe-b094-de42c6c7af95" start_index="0" end="fdbfde34-e543-4bdf-9669-98f7b208228c" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>