<Workspace Version="1.3.1.1736" X="165.417566988464" Y="219.667987626742" zoom="1.01035805450683" ScaleFactor="1" Name="Element.OwnerView" Description="Gets the owner view of a given Revit element (if possible)" ID="a0fc8138-f7bc-4425-abe6-2ef1b411d447" Category="Clockwork.Revit.Elements.Element.Query">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="1da84079-f5bd-46db-92fe-331f3856ffe8" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="262.180327868853" y="153.972999414089" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="element" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="33a866fd-53e7-4d29-b752-0e046772155c" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="674.180327868853" y="153.972999414089" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="view" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="8f50c4d1-b888-4562-933a-68ff7e6b5a56" type="PythonNodeModels.PythonNode" nickname="Python Script" x="450.180327868853" y="153.972999414089" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

def GetOwnerView(item):
	if hasattr(item, "OwnerViewId"): return item.Document.GetElement(item.OwnerViewId)
	else: return None

items = UnwrapElement(IN[0])

if isinstance(IN[0], list): OUT = [GetOwnerView(x) for x in items]
else: OUT = GetOwnerView(items)</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="1da84079-f5bd-46db-92fe-331f3856ffe8" start_index="0" end="8f50c4d1-b888-4562-933a-68ff7e6b5a56" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8f50c4d1-b888-4562-933a-68ff7e6b5a56" start_index="0" end="33a866fd-53e7-4d29-b752-0e046772155c" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>