<Workspace Version="1.2.0.2831" X="-34.7425881120178" Y="-86.681838482938" zoom="0.97676875" Name="Conduit.ByLines" Description="Creates conduits by Line, ConduitType, Level and Diameter" ID="1aeb9ac2-54f1-4786-b432-6208fdb09eb9" Category="MEPover.Revit.Elements">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="8aeddde9-3561-4cd7-b42c-343fb99386f6" type="PythonNodeModels.PythonNode" nickname="Python Script" x="363" y="249" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="4">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <PortInfo index="3" default="False" />
      <Script>import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

toggle = ""

if isinstance(IN[0], list):
	lines = IN[0]
else:
	lines = [IN[0]]
FirstPoint = [x.StartPoint for x in lines]
SecondPoint = [x.EndPoint for x in lines]
conduittype = UnwrapElement(IN[1])
if isinstance(IN[2], list):
	level = UnwrapElement(IN[2])
	toggle += "0"
else:
	level = [UnwrapElement(IN[2])]
if isinstance(IN[3], list):
	diameter = IN[3]
	toggle += "1"
else:
	diameter = [IN[3]]

elements = []

if toggle == "":
	TransactionManager.Instance.EnsureInTransaction(doc)
	for i,x in enumerate(FirstPoint):
		conduit = Autodesk.Revit.DB.Electrical.Conduit.Create(doc,conduittype.Id,FirstPoint[i].ToXyz(),SecondPoint[i].ToXyz(),level[0].Id)
		
		param = conduit.get_Parameter(BuiltInParameter.RBS_CONDUIT_DIAMETER_PARAM)
		param.SetValueString(diameter[0].ToString())

		elements.append(conduit.ToDSType(False))

	TransactionManager.Instance.TransactionTaskDone()

elif toggle == "0":
	TransactionManager.Instance.EnsureInTransaction(doc)
	for i,x in enumerate(FirstPoint):
		conduit = Autodesk.Revit.DB.Electrical.Conduit.Create(doc,conduittype.Id,FirstPoint[i].ToXyz(),SecondPoint[i].ToXyz(),level[i].Id)
		
		param = conduit.get_Parameter(BuiltInParameter.RBS_CONDUIT_DIAMETER_PARAM)
		param.SetValueString(diameter[0].ToString())

		elements.append(conduit.ToDSType(False))

	TransactionManager.Instance.TransactionTaskDone()

elif toggle == "1":
	TransactionManager.Instance.EnsureInTransaction(doc)
	for i,x in enumerate(FirstPoint):
		conduit = Autodesk.Revit.DB.Electrical.Conduit.Create(doc,conduittype.Id,FirstPoint[i].ToXyz(),SecondPoint[i].ToXyz(),level[0].Id)
		
		param = conduit.get_Parameter(BuiltInParameter.RBS_CONDUIT_DIAMETER_PARAM)
		param.SetValueString(diameter[i].ToString())

		elements.append(conduit.ToDSType(False))

	TransactionManager.Instance.TransactionTaskDone()
	
elif toggle == "01":
	TransactionManager.Instance.EnsureInTransaction(doc)
	for i,x in enumerate(FirstPoint):
		conduit = Autodesk.Revit.DB.Electrical.Conduit.Create(doc,conduittype.Id,FirstPoint[i].ToXyz(),SecondPoint[i].ToXyz(),level[i].Id)
		
		param = conduit.get_Parameter(BuiltInParameter.RBS_CONDUIT_DIAMETER_PARAM)
		param.SetValueString(diameter[i].ToString())

		elements.append(conduit.ToDSType(False))

	TransactionManager.Instance.TransactionTaskDone()

OUT = elements
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="804f4ee9-787a-4a48-b5fa-170ff8bb6255" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="112" y="214" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Lines" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="6f8cfd7a-4275-4b3b-b704-1c6248b109b6" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="112.833513561936" y="291.979460337977" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="ConduitType" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="a0406a23-01a6-4880-8be1-c0d6a7467a4d" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="120" y="353" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Level" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="96a3c3e9-4bfb-4bb2-8c65-7263b3f9a8ed" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="110.73837845447" y="424.163242323221" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Diameter" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="dc939297-aceb-4b5d-8d7a-b1f91b951e7d" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="550" y="250" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Conduits" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="8aeddde9-3561-4cd7-b42c-343fb99386f6" start_index="0" end="dc939297-aceb-4b5d-8d7a-b1f91b951e7d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="804f4ee9-787a-4a48-b5fa-170ff8bb6255" start_index="0" end="8aeddde9-3561-4cd7-b42c-343fb99386f6" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6f8cfd7a-4275-4b3b-b704-1c6248b109b6" start_index="0" end="8aeddde9-3561-4cd7-b42c-343fb99386f6" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a0406a23-01a6-4880-8be1-c0d6a7467a4d" start_index="0" end="8aeddde9-3561-4cd7-b42c-343fb99386f6" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="96a3c3e9-4bfb-4bb2-8c65-7263b3f9a8ed" start_index="0" end="8aeddde9-3561-4cd7-b42c-343fb99386f6" end_index="3" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>