<Workspace Version="1.3.2.2480" X="-641.84174792055" Y="-350.100489810482" zoom="2.06862614151419" ScaleFactor="1" Name="Connector.ConnectedElements" Description="Returns the elements that are connected to this connector (does not return the host element)" ID="8eaccc21-b3d0-4a54-a52e-b0b0373d6510" Category="MEPover.Revit.Connectors">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="65f0fdb8-53cf-4ed5-a4fb-4a008a169ad5" type="PythonNodeModels.PythonNode" nickname="Python" x="458" y="305" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

#Many thanks to Konrad K Sobon for his awesome ProcessList function!
def Unwrap(item):
	return UnwrapElement(item)

def ProcessList(_func, _list):
    return map( lambda x: ProcessList(_func, x) if type(x)==list else _func(x), _list )

if isinstance(IN[0], list):
	connectors = ProcessList(Unwrap, IN[0])
else:
	connectors = [Unwrap(IN[0])]
	
	
def getAllRefs(connector):
	refs = None
	try:
		refs = [doc.GetElement(x.Owner.Id) for x in connector.AllRefs if x.Owner.Id != connector.Owner.Id and x.ConnectorType != ConnectorType.Logical]
	except:
		pass
	if type(refs)==list:
		if refs == []:
			return None
		else:
			return refs[0]
	else:
		return refs

			
#Assign your output to the OUT variable.

OUT = ProcessList(getAllRefs, connectors)</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="7195ec03-09ff-4627-b2e6-8050a188a00c" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="313" y="292" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Connector" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="b847c9e3-5646-4c56-b099-b310d47fd50e" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="718" y="279" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Element" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="65f0fdb8-53cf-4ed5-a4fb-4a008a169ad5" start_index="0" end="b847c9e3-5646-4c56-b099-b310d47fd50e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7195ec03-09ff-4627-b2e6-8050a188a00c" start_index="0" end="65f0fdb8-53cf-4ed5-a4fb-4a008a169ad5" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>