<Workspace Version="1.3.2.2480" X="0" Y="0" zoom="1" ScaleFactor="1" Name="Connector.IsConnected" Description="Returns a boolean indicating whether the connector is connected to a connector on different element" ID="2be4e33c-6d0e-4d4e-b305-c72ac8463407" Category="MEPover.Revit.Connectors">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="d019afcd-49da-4dfc-9f3f-1d2bd5cb4ba3" type="PythonNodeModels.PythonNode" nickname="Python" x="519" y="292" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

#Many thanks to Konrad K Sobon for his awesome ProcessList function!
def Unwrap(item):
	return UnwrapElement(item)

def ProcessList(_func, _list):
    return map( lambda x: ProcessList(_func, x) if type(x)==list else _func(x), _list )

if isinstance(IN[0], list):
	connectors = ProcessList(Unwrap, IN[0])
else:
	connectors = [Unwrap(IN[0])]
	
	
def IsConnected(connector):
	bool = False
	try:
		bool = connector.IsConnected
	except:
		pass
	return bool

			
#Assign your output to the OUT variable.

OUT = ProcessList(IsConnected, connectors)</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="e00aa14f-38c8-493c-9b04-b86e2cd5e991" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="232" y="301" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Connector" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="41ec26f6-fa7b-4c4d-a1f2-86ab4b851072" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="703" y="317" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="IsConnected" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="d019afcd-49da-4dfc-9f3f-1d2bd5cb4ba3" start_index="0" end="41ec26f6-fa7b-4c4d-a1f2-86ab4b851072" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e00aa14f-38c8-493c-9b04-b86e2cd5e991" start_index="0" end="d019afcd-49da-4dfc-9f3f-1d2bd5cb4ba3" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>