<Workspace Version="1.3.2.2480" X="0" Y="0" zoom="1" ScaleFactor="1" Name="Connector.SizeRound" Description="Returns the Height and the Width of the connector (in feet)" ID="13020e37-81eb-484d-a9bc-534ca6a01acf" Category="MEPover.Revit.Connectors">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="b6fe14ac-0b6a-46af-b165-e4fb1c637370" type="PythonNodeModels.PythonNode" nickname="Python" x="589" y="274" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

#Many thanks to Konrad K Sobon for his awesome ProcessList function!
def Unwrap(item):
	return UnwrapElement(item)

def ProcessList(_func, _list):
    return map( lambda x: ProcessList(_func, x) if type(x)==list else _func(x), _list )

if isinstance(IN[0], list):
	connectors = ProcessList(Unwrap, IN[0])
else:
	connectors = [Unwrap(IN[0])]
	
	
def getConnSizeRound(connector):
	r = None
	try:
		r = connector.Radius
	except:
		pass
	return r


			
#Assign your output to the OUT variable.

OUT = ProcessList(getConnSizeRound, connectors)</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="d29197da-3ba8-4b7e-a78a-78a593a318ed" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="355" y="265" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Connector" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="851ab14f-6644-49f1-b886-1f3fb1615d14" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="793" y="116" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Radius" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="b6fe14ac-0b6a-46af-b165-e4fb1c637370" start_index="0" end="851ab14f-6644-49f1-b886-1f3fb1615d14" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d29197da-3ba8-4b7e-a78a-78a593a318ed" start_index="0" end="b6fe14ac-0b6a-46af-b165-e4fb1c637370" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>