<Workspace Version="1.3.2.2480" X="0" Y="0" zoom="1" ScaleFactor="1" Name="Connector.ConnectTo" Description="Connects a connector to another connector. Returns True if connection succeeded" ID="ca223201-4642-413f-8de8-707f933b90a9" Category="MEPover.Revit.Connectors">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="6bfdfbc1-4347-4439-8494-f7063cc26aa0" type="PythonNodeModels.PythonNode" nickname="Python" x="407" y="263" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

#Many thanks to Konrad K Sobon for his awesome ProcessList function!
def Unwrap(item):
	return UnwrapElement(item)
	
def ProcessList(_func, _list):
    return map( lambda x: ProcessList(_func, x) if type(x)==list else _func(x), _list )

def ProcessList2(_func, _list, _list2):
    return map( lambda x,y: ProcessList2(_func, x, y) if type(x)==list else _func(x,y), _list, _list2 )

if isinstance(IN[0], list):
	connectors = IN[0]
else:
	connectors = [IN[0]]
	
if isinstance(IN[1], list):
	connectors2 = IN[1]
else:
	connectors2 = [IN[1]]
	
	
def ConnectTo(connector, conn2):
	bool = False
	try:
		TransactionManager.Instance.EnsureInTransaction(doc)
		connector.ConnectTo(conn2)
		bool = True
		TransactionManager.Instance.TransactionTaskDone()
	except:
		pass
	return bool

			
#Assign your output to the OUT variable.
OUT = ProcessList2(ConnectTo, connectors, connectors2)</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="cb67dde5-6ed8-4e59-84de-99d24d403233" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="208" y="243" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Connector" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="358427ec-9929-42d2-af71-b7bd253fa5e8" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="214" y="388" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Connector2" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="f8a5f9d2-7f81-4ee3-8ecc-fabb4b3dbbf8" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="600" y="272" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Connected" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="6bfdfbc1-4347-4439-8494-f7063cc26aa0" start_index="0" end="f8a5f9d2-7f81-4ee3-8ecc-fabb4b3dbbf8" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="cb67dde5-6ed8-4e59-84de-99d24d403233" start_index="0" end="6bfdfbc1-4347-4439-8494-f7063cc26aa0" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="358427ec-9929-42d2-af71-b7bd253fa5e8" start_index="0" end="6bfdfbc1-4347-4439-8494-f7063cc26aa0" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>