<Workspace Version="1.3.2.2480" X="-64.3822966856333" Y="101.3590550681" zoom="0.712594832628488" ScaleFactor="1" Name="Connector.LinkedConnector" Description="Returns the linked connector" ID="f6c19a28-11b7-4d37-89ac-d91623fe4f1c" Category="MEPover.Revit.Connectors">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="78f0fec1-b055-4082-bc75-47f916eab37b" type="PythonNodeModels.PythonNode" nickname="Python" x="540" y="351" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

#Many thanks to Konrad K Sobon for his awesome ProcessList function!
def Unwrap(item):
	return UnwrapElement(item)

def ProcessList(_func, _list):
    return map( lambda x: ProcessList(_func, x) if type(x)==list else _func(x), _list )

if isinstance(IN[0], list):
	connectors = ProcessList(Unwrap, IN[0])
else:
	connectors = [Unwrap(IN[0])]
	
	
def getConnLink(connector):
	link = None
	try:
		link = connector.GetMEPConnectorInfo().LinkedConnector
	except:
		pass
	return link

			
#Assign your output to the OUT variable.

OUT = ProcessList(getConnLink, connectors)</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="c9bcbb44-9044-4229-a260-b15f470dff7c" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="382" y="347" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Connector" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="f9c43d12-5a9b-48c5-9e81-05d400a9b15a" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="739" y="351" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="LinkedConnector" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="78f0fec1-b055-4082-bc75-47f916eab37b" start_index="0" end="f9c43d12-5a9b-48c5-9e81-05d400a9b15a" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c9bcbb44-9044-4229-a260-b15f470dff7c" start_index="0" end="78f0fec1-b055-4082-bc75-47f916eab37b" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>