<Workspace Version="1.3.2.2480" X="0" Y="0" zoom="1" ScaleFactor="1" Name="Connector.DisconnectFrom" Description="Disconnects a connector from another connector. Returns True if succeeded" ID="39ab3156-feb9-4e1d-9e24-ff1af4029ff5" Category="MEPover.Revit.Connectors">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="9da531b4-c036-4bff-b6b1-f11baa1fa527" type="PythonNodeModels.PythonNode" nickname="Python" x="454" y="405" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

#Many thanks to Konrad K Sobon for his awesome ProcessList function!
def Unwrap(item):
	return UnwrapElement(item)
	
def ProcessList(_func, _list):
    return map( lambda x: ProcessList(_func, x) if type(x)==list else _func(x), _list )

def ProcessList2(_func, _list, _list2):
    return map( lambda x,y: ProcessList2(_func, x, y) if type(x)==list else _func(x,y), _list, _list2 )

if isinstance(IN[0], list):
	connectors = IN[0]
else:
	connectors = [IN[0]]
	
if isinstance(IN[1], list):
	connectors2 = IN[1]
else:
	connectors2 = [IN[1]]
	
	
def DisconnectFrom(connector, conn2):
	bool = False
	try:
		TransactionManager.Instance.EnsureInTransaction(doc)
		connector.DisconnectFrom(conn2)
		bool = True
		TransactionManager.Instance.TransactionTaskDone()
	except:
		pass
	return bool

			
#Assign your output to the OUT variable.
OUT = ProcessList2(DisconnectFrom, connectors, connectors2)</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="322c855d-db60-480c-a8a8-d8b10c7c52a6" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="273" y="345" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Connector" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="62b55f76-3336-4588-b77c-1d2a7dbc9d15" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="271" y="483" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Connector2" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="03de6fff-9506-4454-a1fe-883907495c9a" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="667" y="388" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Disconnected" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="9da531b4-c036-4bff-b6b1-f11baa1fa527" start_index="0" end="03de6fff-9506-4454-a1fe-883907495c9a" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="322c855d-db60-480c-a8a8-d8b10c7c52a6" start_index="0" end="9da531b4-c036-4bff-b6b1-f11baa1fa527" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="62b55f76-3336-4588-b77c-1d2a7dbc9d15" start_index="0" end="9da531b4-c036-4bff-b6b1-f11baa1fa527" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>