<Workspace Version="1.3.2.2480" X="0" Y="0" zoom="1" ScaleFactor="1" Name="Connector.FlowDirection" Description="Returns the direction of the flow on the connector" ID="0f1479a4-1101-4b16-a772-5c152faea8c3" Category="MEPover.Revit.Connectors">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="e66d8dae-5662-4e27-80ba-a9574e65ae0c" type="PythonNodeModels.PythonNode" nickname="Python" x="539" y="350" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

#Many thanks to Konrad K Sobon for his awesome ProcessList function!
def Unwrap(item):
	return UnwrapElement(item)

def ProcessList(_func, _list):
    return map( lambda x: ProcessList(_func, x) if type(x)==list else _func(x), _list )

if isinstance(IN[0], list):
	connectors = ProcessList(Unwrap, IN[0])
else:
	connectors = [Unwrap(IN[0])]
	
	
def getConnFlowDir(connector):
	try:
		return connector.Direction.ToString()
	except:
		return None


			
#Assign your output to the OUT variable.

OUT = ProcessList(getConnFlowDir, connectors)</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="cb487406-d63c-45b8-8caf-c4d142b53249" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="247" y="420" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Connector" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="d228f3ba-f3ab-4170-beb0-c7c4820b6d5d" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="754" y="366" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="FlowDirection" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="e66d8dae-5662-4e27-80ba-a9574e65ae0c" start_index="0" end="d228f3ba-f3ab-4170-beb0-c7c4820b6d5d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="cb487406-d63c-45b8-8caf-c4d142b53249" start_index="0" end="e66d8dae-5662-4e27-80ba-a9574e65ae0c" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>