<Workspace Version="1.3.2.2480" X="0" Y="0" zoom="1" ScaleFactor="1" Name="Connector.SystemType" Description="Returns the System Type of the connected system" ID="93cc2b05-db31-4a22-b158-77911531f78e" Category="MEPover.Revit.Connectors">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="8c064e62-3234-406d-8645-bed9431f7984" type="PythonNodeModels.PythonNode" nickname="Python" x="522" y="277" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

#Many thanks to Konrad K Sobon for his awesome ProcessList function!
def Unwrap(item):
	return UnwrapElement(item)

def ProcessList(_func, _list):
    return map( lambda x: ProcessList(_func, x) if type(x)==list else _func(x), _list )

if isinstance(IN[0], list):
	connectors = ProcessList(Unwrap, IN[0])
else:
	connectors = [Unwrap(IN[0])]
	
	
def getConnSysType(connector):
	systype = None
	try:
		sys = connector.MEPSystem
		systype = doc.GetElement(sys.GetTypeId())
	except:
		pass
	return systype

			
#Assign your output to the OUT variable.

OUT = ProcessList(getConnSysType, connectors)</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="b4d47b3d-97f1-45e4-bc24-4e9854864a82" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="329" y="278" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Connector" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="be51652e-1349-4dfa-92be-2f65d9858d77" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="707" y="242" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="SystemType" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="8c064e62-3234-406d-8645-bed9431f7984" start_index="0" end="be51652e-1349-4dfa-92be-2f65d9858d77" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b4d47b3d-97f1-45e4-bc24-4e9854864a82" start_index="0" end="8c064e62-3234-406d-8645-bed9431f7984" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>