<Workspace Version="1.3.2.2480" X="0" Y="0" zoom="1" ScaleFactor="1" Name="Connector.IsPrimary" Description="Returns a boolean indicating whether the connector is the primary connector" ID="fd52f8e4-503e-4be4-9bfb-ce74c693b3dd" Category="MEPover.Revit.Connectors">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="b148967a-b928-4ee9-9e63-37165bbec30b" type="PythonNodeModels.PythonNode" nickname="Python" x="509" y="294" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

#Many thanks to Konrad K Sobon for his awesome ProcessList function!
def Unwrap(item):
	return UnwrapElement(item)

def ProcessList(_func, _list):
    return map( lambda x: ProcessList(_func, x) if type(x)==list else _func(x), _list )

if isinstance(IN[0], list):
	connectors = ProcessList(Unwrap, IN[0])
else:
	connectors = [Unwrap(IN[0])]
	
	
def getConnPrim(connector):
	prim = False
	try:
		prim = connector.GetMEPConnectorInfo().IsPrimary
	except:
		pass
	return prim

			
#Assign your output to the OUT variable.

OUT = ProcessList(getConnPrim, connectors)</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="503cb2c5-1791-49d4-ad8e-3afc3a55feb1" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="326" y="351" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Connector" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="024b9560-68df-4046-b1b8-83921ce14ca5" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="751" y="397" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="bool" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="b148967a-b928-4ee9-9e63-37165bbec30b" start_index="0" end="024b9560-68df-4046-b1b8-83921ce14ca5" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="503cb2c5-1791-49d4-ad8e-3afc3a55feb1" start_index="0" end="b148967a-b928-4ee9-9e63-37165bbec30b" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>