<Workspace Version="1.3.2.2480" X="0" Y="0" zoom="1" ScaleFactor="1" Name="Connector.Direction" Description="Returns the direction of the CoordinateSystem of the Connector" ID="2a7910e0-eedd-4c36-a10d-4b2d998f4808" Category="MEPover.Revit.Connectors">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="a3d65122-8015-4400-a39c-87132f1c7fb1" type="PythonNodeModels.PythonNode" nickname="Python" x="446" y="280" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

#Many thanks to Konrad K Sobon for his awesome ProcessList function!
def Unwrap(item):
	return UnwrapElement(item)

def ProcessList(_func, _list):
    return map( lambda x: ProcessList(_func, x) if type(x)==list else _func(x), _list )

if isinstance(IN[0], list):
	connectors = ProcessList(Unwrap, IN[0])
else:
	connectors = [Unwrap(IN[0])]
	
	
def getConnDir(connector):
	try:
		return connector.CoordinateSystem.BasisZ.ToVector()
	except:
		return None


			
#Assign your output to the OUT variable.

OUT = ProcessList(getConnDir, connectors)</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="0436da68-85dc-47c2-afcf-b6dc881e52bd" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="286" y="309" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Connector" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="3b0a6499-4ffc-436d-bc5c-9a4871e94170" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="647" y="284" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Direction" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="a3d65122-8015-4400-a39c-87132f1c7fb1" start_index="0" end="3b0a6499-4ffc-436d-bc5c-9a4871e94170" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0436da68-85dc-47c2-afcf-b6dc881e52bd" start_index="0" end="a3d65122-8015-4400-a39c-87132f1c7fb1" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>