<Workspace Version="1.3.2.2480" X="0" Y="0" zoom="1" ScaleFactor="1" Name="Connector.Shape" Description="Returns the shape of the connector" ID="2f9d95d5-411c-4e1f-8924-cbd04554f9b3" Category="MEPover.Revit.Connectors">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="8826dc80-da4d-4e5e-ba13-f92d286b1a5c" type="PythonNodeModels.PythonNode" nickname="Python" x="540" y="355" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

#Many thanks to Konrad K Sobon for his awesome ProcessList function!
def Unwrap(item):
	return UnwrapElement(item)

def ProcessList(_func, _list):
    return map( lambda x: ProcessList(_func, x) if type(x)==list else _func(x), _list )

if isinstance(IN[0], list):
	connectors = ProcessList(Unwrap, IN[0])
else:
	connectors = [Unwrap(IN[0])]
	
	
def getConnShape(connector):
	shape = None
	try:
		shape = connector.Shape.ToString()
	except:
		pass
	return shape

			
#Assign your output to the OUT variable.

OUT = ProcessList(getConnShape, connectors)</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="b9af40d0-e841-481c-a873-c8e3479cdfb2" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="353" y="349" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Connector" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="19bbcb37-c676-451f-931e-9812329e4225" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="765" y="311" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Shape" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="8826dc80-da4d-4e5e-ba13-f92d286b1a5c" start_index="0" end="19bbcb37-c676-451f-931e-9812329e4225" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b9af40d0-e841-481c-a873-c8e3479cdfb2" start_index="0" end="8826dc80-da4d-4e5e-ba13-f92d286b1a5c" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>