<Workspace Version="1.3.2.2480" X="0" Y="0" zoom="1" ScaleFactor="1" Name="Connector.HostElement" Description="Returns the element that hosts the connector" ID="97942d80-b06d-43e7-b3d2-87210333825c" Category="MEPover.Revit.Connectors">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="d67f3e7d-c854-4680-9a27-bf729d55c8ca" type="PythonNodeModels.PythonNode" nickname="Python" x="380" y="269" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

#Many thanks to Konrad K Sobon for his awesome ProcessList function!
def Unwrap(item):
	return UnwrapElement(item)

def ProcessList(_func, _list):
    return map( lambda x: ProcessList(_func, x) if type(x)==list else _func(x), _list )

if isinstance(IN[0], list):
	connectors = ProcessList(Unwrap, IN[0])
else:
	connectors = [Unwrap(IN[0])]
	
	
def getConnHost(connector):
	host = None
	try:
		host = doc.GetElement(connector.Owner.Id)
	except:
		pass
	return host.ToDSType(False)

			
#Assign your output to the OUT variable.

OUT = ProcessList(getConnHost, connectors)</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="c12be38e-7dc6-4c35-a2d3-57aaf290a6ea" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="181" y="270" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Connector" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="3e89e4f8-faf4-4790-8298-d3e4f618594d" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="574" y="266" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Element" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="d67f3e7d-c854-4680-9a27-bf729d55c8ca" start_index="0" end="3e89e4f8-faf4-4790-8298-d3e4f618594d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c12be38e-7dc6-4c35-a2d3-57aaf290a6ea" start_index="0" end="d67f3e7d-c854-4680-9a27-bf729d55c8ca" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>