<Workspace Version="1.3.2.2480" X="-921.576179378882" Y="-460.898539611723" zoom="2.37004060791358" ScaleFactor="1" Name="Connector.ConnectorSystemType" Description="Returns the Connector System Type of the connector" ID="90142566-7c88-451d-a219-0d14df9bb9c3" Category="MEPover.Revit.Connectors">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="789250e6-9f94-47e8-b77f-231ca581eec7" type="PythonNodeModels.PythonNode" nickname="Python Script" x="606" y="282" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

#Many thanks to Konrad K Sobon for his awesome ProcessList function!
def Unwrap(item):
	return UnwrapElement(item)

def ProcessList(_func, _list):
    return map( lambda x: ProcessList(_func, x) if type(x)==list else _func(x), _list )

if isinstance(IN[0], list):
	connectors = ProcessList(Unwrap, IN[0])
else:
	connectors = [Unwrap(IN[0])]
	
	
def getConnSysType(connector):
	domain = connector.Domain
	if domain == Domain.DomainHvac:
		return connector.DuctSystemType.ToString()
	elif domain == Domain.DomainPiping:
		return connector.PipeSystemType.ToString()
	elif domain == Domain.DomainElectrical:
		return connector.ElectricalSystemType.ToString()
	else:
		return None



OUT = ProcessList(getConnSysType, connectors)</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="d297ad9e-1ff0-4b59-b792-3bd6844edec3" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="383" y="279" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Connector" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="4a738366-f98b-4337-a227-baf4412b99c4" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="801" y="248" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="ConnectorSystemType" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="789250e6-9f94-47e8-b77f-231ca581eec7" start_index="0" end="4a738366-f98b-4337-a227-baf4412b99c4" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d297ad9e-1ff0-4b59-b792-3bd6844edec3" start_index="0" end="789250e6-9f94-47e8-b77f-231ca581eec7" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>