<Workspace Version="1.2.0.2831" X="-6" Y="-24" zoom="1" Name="DuctRectangular.ByLines" Description="Create ducts by Lines, DuctType, MechanicalFittingType, Level, Width and Height" ID="23e1b85c-1f80-47e6-aac7-d37d3cfcc22b" Category="MEPover.Revit.Elements">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="7a552da6-0d30-4e11-8bce-758e9fd1a6d9" type="PythonNodeModels.PythonNode" nickname="Python Script" x="360" y="153" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="6">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <PortInfo index="3" default="False" />
      <PortInfo index="4" default="False" />
      <PortInfo index="5" default="False" />
      <Script>import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

toggle = ""

if isinstance(IN[0], list):
	lines = IN[0]
else:
	lines = [IN[0]]
FirstPoint = [x.StartPoint for x in lines]
SecondPoint = [x.EndPoint for x in lines]
ducttype = UnwrapElement(IN[1])
systemtype = UnwrapElement(IN[2])
if isinstance(IN[3], list):
	level = UnwrapElement(IN[3])
	toggle += "0"
else:
	level = [UnwrapElement(IN[3])]
if isinstance(IN[4], list):
	width = IN[4]
	toggle += "1"
else:
	width = [IN[4]]
if isinstance(IN[5], list):
	height = IN[5]
	toggle += "1"
else:
	height = [IN[5]]

elements = []

if toggle == "":
	TransactionManager.Instance.EnsureInTransaction(doc)
	for i,x in enumerate(FirstPoint):
		duct = Autodesk.Revit.DB.Mechanical.Duct.Create(doc,systemtype.Id,ducttype.Id,level[0].Id,FirstPoint[i].ToXyz(),SecondPoint[i].ToXyz())
		
		param = duct.get_Parameter(BuiltInParameter.RBS_CURVE_WIDTH_PARAM)
		param.SetValueString(width[0].ToString())
		
		param2 = duct.get_Parameter(BuiltInParameter.RBS_CURVE_HEIGHT_PARAM)
		param2.SetValueString(height[0].ToString())

		elements.append(duct.ToDSType(False))

	TransactionManager.Instance.TransactionTaskDone()
	
elif toggle == "0":
	TransactionManager.Instance.EnsureInTransaction(doc)
	for i,x in enumerate(FirstPoint):
		duct = Autodesk.Revit.DB.Mechanical.Duct.Create(doc,systemtype.Id,ducttype.Id,level[i].Id,FirstPoint[i].ToXyz(),SecondPoint[i].ToXyz())
		
		param = duct.get_Parameter(BuiltInParameter.RBS_CURVE_WIDTH_PARAM)
		param.SetValueString(width[0].ToString())
		
		param2 = duct.get_Parameter(BuiltInParameter.RBS_CURVE_HEIGHT_PARAM)
		param2.SetValueString(height[0].ToString())

		elements.append(duct.ToDSType(False))

	TransactionManager.Instance.TransactionTaskDone()
	
elif toggle == "11":
	TransactionManager.Instance.EnsureInTransaction(doc)
	for i,x in enumerate(FirstPoint):
		duct = Autodesk.Revit.DB.Mechanical.Duct.Create(doc,systemtype.Id,ducttype.Id,level[0].Id,FirstPoint[i].ToXyz(),SecondPoint[i].ToXyz())
		
		param = duct.get_Parameter(BuiltInParameter.RBS_CURVE_WIDTH_PARAM)
		param.SetValueString(width[i].ToString())
		
		param2 = duct.get_Parameter(BuiltInParameter.RBS_CURVE_HEIGHT_PARAM)
		param2.SetValueString(height[i].ToString())

		elements.append(duct.ToDSType(False))

	TransactionManager.Instance.TransactionTaskDone()
	
elif toggle == "011":
	TransactionManager.Instance.EnsureInTransaction(doc)
	for i,x in enumerate(FirstPoint):
		duct = Autodesk.Revit.DB.Mechanical.Duct.Create(doc,systemtype.Id,ducttype.Id,level[i].Id,FirstPoint[i].ToXyz(),SecondPoint[i].ToXyz())
		
		param = duct.get_Parameter(BuiltInParameter.RBS_CURVE_WIDTH_PARAM)
		param.SetValueString(width[i].ToString())
		
		param2 = duct.get_Parameter(BuiltInParameter.RBS_CURVE_HEIGHT_PARAM)
		param2.SetValueString(height[i].ToString())

		elements.append(duct.ToDSType(False))

	TransactionManager.Instance.TransactionTaskDone()


OUT = elements</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="82fb651d-5428-4fcf-8c51-54880162adfd" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="87" y="107" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Lines" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="97c4d735-8fe6-4ee4-9203-895dc576bc2a" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="73" y="176" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="DuctType" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="b81d4234-8f3a-40ac-8a46-58c973c62964" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="25" y="248" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="MechanicalSystemType" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="e9e4c83b-1c0f-4150-a86e-d8a4949e88bb" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="98" y="302" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Level" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="12736f06-4d1c-431a-b66e-e47f71813fe5" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="74" y="376" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Width" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="f85ea5b4-8baa-456f-a84b-a2526b219303" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="92" y="445" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Height" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="c51129c8-0bd7-4fe5-92fe-5025ea7d4d43" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="549" y="157" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Ducts" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="7a552da6-0d30-4e11-8bce-758e9fd1a6d9" start_index="0" end="c51129c8-0bd7-4fe5-92fe-5025ea7d4d43" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="82fb651d-5428-4fcf-8c51-54880162adfd" start_index="0" end="7a552da6-0d30-4e11-8bce-758e9fd1a6d9" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="97c4d735-8fe6-4ee4-9203-895dc576bc2a" start_index="0" end="7a552da6-0d30-4e11-8bce-758e9fd1a6d9" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b81d4234-8f3a-40ac-8a46-58c973c62964" start_index="0" end="7a552da6-0d30-4e11-8bce-758e9fd1a6d9" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e9e4c83b-1c0f-4150-a86e-d8a4949e88bb" start_index="0" end="7a552da6-0d30-4e11-8bce-758e9fd1a6d9" end_index="3" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="12736f06-4d1c-431a-b66e-e47f71813fe5" start_index="0" end="7a552da6-0d30-4e11-8bce-758e9fd1a6d9" end_index="4" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f85ea5b4-8baa-456f-a84b-a2526b219303" start_index="0" end="7a552da6-0d30-4e11-8bce-758e9fd1a6d9" end_index="5" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>