<Workspace Version="1.3.1.1736" X="14" Y="-91" zoom="1" ScaleFactor="1" Name="Duct upstream components" Description="This node will try to return the connected elements in the upstream network. It will stop once it encounters an element twice or encounters a different system classification or cannot find a connector with an opposing direction." ID="e9d65d10-c25a-47d1-90ba-a6faf1c9d9c8" Category="MEPover.Revit.Systems">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="67f3545b-6a56-4105-abbc-504c5417d63c" type="PythonNodeModels.PythonNode" nickname="Python Script" x="321" y="277" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
import math

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)
#The inputs to this node will be stored as a list in the IN variables.
if isinstance(IN[0], list):
	elements = UnwrapElement(IN[0])
else:
	elements = [UnwrapElement(IN[0])]
	
def getSize(x):
	try:
		conns = x.ConnectorManager.Connectors
	except:
		conns = x.MEPModel.ConnectorManager.Connectors
	maxsize = 0
	for c in conns:
		if c.Shape == ConnectorProfileType.Round:
			startsize = c.Radius * 2
		elif c.Shape == ConnectorProfileType.Invalid:
			continue
		else:
			area = c.Width * c.Height
			startsize = (math.sqrt(area/math.pi) * 2)
		if startsize &gt; maxsize:
			maxsize = startsize
	return maxsize
	
factor = IN[1]

def nextElement(elem,sys):
	sysname = next.get_Parameter(BuiltInParameter.RBS_SYSTEM_CLASSIFICATION_PARAM).AsString()
	for s in sysname.split(","):
		if s in sys.split(","):
			break
	else:
		return 4
	if "Return Air" in sysname:
		direction = FlowDirectionType.In
	else:
		direction = FlowDirectionType.Out
	try:
		connectors = elem.ConnectorManager.Connectors
		for conn in connectors:
			if conn.Domain != Domain.DomainHvac:
				continue
			elif conn.Direction == direction:
				continue
			else:
				endconn = conn
		for c in endconn.AllRefs:
			if c.Owner.Id.Equals(elem.Id):
				continue
			elif c.Owner.GetType() == Mechanical.MechanicalSystem:
				return 0
			else:
				newelem = c.Owner
		return newelem
	except AttributeError:
		connectors = elem.MEPModel.ConnectorManager.Connectors
		if connectors.Size == 1:
			for conn in connectors:
				if conn.Domain != Domain.DomainHvac:
					continue
				endconn = conn
			if endconn.AllRefs.Size == 1:
				for c in endconn.AllRefs:
					if c.Owner.GetType() == Mechanical.MechanicalSystem:
						return 1
			for c in endconn.AllRefs:
				if c.Owner.Id.Equals(elem.Id):
					continue
				elif c.Owner.GetType() == Mechanical.MechanicalSystem:
					continue
				else:
					newelem = c.Owner
			return newelem
		elif connectors.Size == 2:
			for conn in connectors:
				if conn.Domain != Domain.DomainHvac:
					continue
				if conn.Direction == direction:
					continue
				else:
					endconn = conn
			if endconn.AllRefs.Size == 1:
				for c in endconn.AllRefs:
					if c.Owner.GetType() == Mechanical.MechanicalSystem:
						return 2
			for c in endconn.AllRefs:
				if c.Owner.Id.Equals(elem.Id):
					continue
				elif c.Owner.GetType() == Mechanical.MechanicalSystem:
					continue
				else:
					newelem = c.Owner
			return newelem
		else:
			for conn in connectors:
				if conn.Domain != Domain.DomainHvac:
					continue
				if conn.Direction != direction:
					endconn = conn
			if endconn.AllRefs.Size == 1:
				for c in endconn.AllRefs:
					if c.Owner.GetType() == Mechanical.MechanicalSystem:
						return 3
			for c in endconn.AllRefs:
				if c.Owner.Id.Equals(elem.Id):
					continue
				elif c.Owner.GetType() == Mechanical.MechanicalSystem:
					continue
				else:
					newelem = c.Owner
			return newelem

result = []
endlist = []
for j,x in enumerate(elements):
	listout = []
	ids = []
	sysclass = x.get_Parameter(BuiltInParameter.RBS_SYSTEM_CLASSIFICATION_PARAM).AsString()
	startsize = getSize(x)
	next = x
	i = 0
	while True:
		if i &gt; 1000:
			result.append(next.Id.ToString() + ": end of loop")
			break
		try:
			next = nextElement(next,sysclass)
			i += 1
		except Exception as e:
			result.append(next.Id.ToString() + ": probably a direction error")
			break		
		if isinstance(next, int):
			result.append(next.ToString() + ": open end or different system classification")
			break
		if next.Id in ids:
			result.append(next.Id.ToString() + ": double element")
			break
		i += 1
		nextsize = getSize(next)
		if nextsize &gt; startsize * factor:
			result.append(next.Id.ToString() + ": size end")
			break
		ids.append(next.Id)
		listout.append(next)
	endlist.append(listout)


#Assign your output to the OUT variable.
if len(endlist) == 1:
	OUT = listout, result
else:
	OUT = endlist, result</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="86a90eef-84b1-4f42-b868-bbb8c0b38ce5" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="523" y="271" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="x[0];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="c878fdd3-450f-4700-93cd-bcbae79ba66b" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="676" y="259" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Elements" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="386c732f-5646-4a8b-acca-278bcf25070c" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="77" y="234" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="DuctElement" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="f9566186-06f2-404f-8d20-ea9979dbe4f8" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-5" y="380" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="SizeLimitFactor: int = 20" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="67f3545b-6a56-4105-abbc-504c5417d63c" start_index="0" end="86a90eef-84b1-4f42-b868-bbb8c0b38ce5" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="86a90eef-84b1-4f42-b868-bbb8c0b38ce5" start_index="0" end="c878fdd3-450f-4700-93cd-bcbae79ba66b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="386c732f-5646-4a8b-acca-278bcf25070c" start_index="0" end="67f3545b-6a56-4105-abbc-504c5417d63c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f9566186-06f2-404f-8d20-ea9979dbe4f8" start_index="0" end="67f3545b-6a56-4105-abbc-504c5417d63c" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>