<Workspace Version="1.2.0.2831" X="0" Y="0" zoom="1" Name="DuctRound.ByLines" Description="Create round Ducts by Lines, DuctType, SystemType, Level and Diameter" ID="ccc9bd94-4914-4d30-8b00-a7434f77b4ef" Category="MEPover.Revit.Elements">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="a24782a3-bc29-409e-ace1-622b23a4c5e1" type="PythonNodeModels.PythonNode" nickname="Python Script" x="292" y="263" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="5">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <PortInfo index="3" default="False" />
      <PortInfo index="4" default="False" />
      <Script>import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

toggle = ""

if isinstance(IN[0], list):
	lines = IN[0]
else:
	lines = [IN[0]]
FirstPoint = [x.StartPoint for x in lines]
SecondPoint = [x.EndPoint for x in lines]
ducttype = UnwrapElement(IN[1])
systemtype = UnwrapElement(IN[2])
if isinstance(IN[3], list):
	level = UnwrapElement(IN[3])
	toggle += "0"
else:
	level = [UnwrapElement(IN[3])]
if isinstance(IN[4], list):
	diameter = IN[4]
	toggle += "1"
else:
	diameter = [IN[4]]

elements = []

if toggle == "":
	TransactionManager.Instance.EnsureInTransaction(doc)
	for i,x in enumerate(FirstPoint):
		duct = Autodesk.Revit.DB.Mechanical.Duct.Create(doc,systemtype.Id,ducttype.Id,level[0].Id,FirstPoint[i].ToXyz(),SecondPoint[i].ToXyz())
		
		param = duct.get_Parameter(BuiltInParameter.RBS_CURVE_DIAMETER_PARAM)
		param.SetValueString(diameter[0].ToString())

		elements.append(duct.ToDSType(False))

	TransactionManager.Instance.TransactionTaskDone()
	
elif toggle == "0":
	TransactionManager.Instance.EnsureInTransaction(doc)
	for i,x in enumerate(FirstPoint):
		duct = Autodesk.Revit.DB.Mechanical.Duct.Create(doc,systemtype.Id,ducttype.Id,level[i].Id,FirstPoint[i].ToXyz(),SecondPoint[i].ToXyz())
		
		param = duct.get_Parameter(BuiltInParameter.RBS_CURVE_DIAMETER_PARAM)
		param.SetValueString(diameter[0].ToString())

		elements.append(duct.ToDSType(False))

	TransactionManager.Instance.TransactionTaskDone()
	
elif toggle == "1":
	TransactionManager.Instance.EnsureInTransaction(doc)
	for i,x in enumerate(FirstPoint):
		duct = Autodesk.Revit.DB.Mechanical.Duct.Create(doc,systemtype.Id,ducttype.Id,level[0].Id,FirstPoint[i].ToXyz(),SecondPoint[i].ToXyz())
		
		param = duct.get_Parameter(BuiltInParameter.RBS_CURVE_DIAMETER_PARAM)
		param.SetValueString(diameter[i].ToString())

		elements.append(duct.ToDSType(False))

	TransactionManager.Instance.TransactionTaskDone()
	
elif toggle == "01":
	TransactionManager.Instance.EnsureInTransaction(doc)
	for i,x in enumerate(FirstPoint):
		duct = Autodesk.Revit.DB.Mechanical.Duct.Create(doc,systemtype.Id,ducttype.Id,level[i].Id,FirstPoint[i].ToXyz(),SecondPoint[i].ToXyz())
		
		param = duct.get_Parameter(BuiltInParameter.RBS_CURVE_DIAMETER_PARAM)
		param.SetValueString(diameter[i].ToString())

		elements.append(duct.ToDSType(False))

	TransactionManager.Instance.TransactionTaskDone()


OUT = elements</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="0451fd48-69f4-4f0f-8797-91e56dafe962" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="78" y="230" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Lines" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="923c00f6-ba29-487e-82c8-5c304d290f42" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="62" y="293" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="DuctType" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="c86dad8b-344b-45ee-b5e5-67696eb015b2" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-15" y="359" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="MechanicalSystemType" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="24d572c5-78cb-46a6-a3e8-f3c374088a3e" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="14" y="432" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Level" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="b80e63de-c6cc-45e7-bdc1-51822be45245" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="16" y="513" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Diameter" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="09d660e2-8821-404b-999f-308bdaefc5d9" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="484" y="279" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Round Ducts" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="a24782a3-bc29-409e-ace1-622b23a4c5e1" start_index="0" end="09d660e2-8821-404b-999f-308bdaefc5d9" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0451fd48-69f4-4f0f-8797-91e56dafe962" start_index="0" end="a24782a3-bc29-409e-ace1-622b23a4c5e1" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="923c00f6-ba29-487e-82c8-5c304d290f42" start_index="0" end="a24782a3-bc29-409e-ace1-622b23a4c5e1" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c86dad8b-344b-45ee-b5e5-67696eb015b2" start_index="0" end="a24782a3-bc29-409e-ace1-622b23a4c5e1" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="24d572c5-78cb-46a6-a3e8-f3c374088a3e" start_index="0" end="a24782a3-bc29-409e-ace1-622b23a4c5e1" end_index="3" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b80e63de-c6cc-45e7-bdc1-51822be45245" start_index="0" end="a24782a3-bc29-409e-ace1-622b23a4c5e1" end_index="4" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>