<Workspace Version="1.2.0.2831" X="0" Y="0" zoom="1" Name="ElectricalFitting connector count" Description="Returns the number of connectors on the cable tray or conduit fitting" ID="89b0f8eb-8cb0-4228-b71f-78a690376aee" Category="MEPover.Revit.Elements">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="718130a3-5b55-40bc-9c39-44732d72d39c" type="PythonNodeModels.PythonNode" nickname="Python Script" x="286" y="291" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
if isinstance(IN[0], list):
	fittings = UnwrapElement(IN[0])
else:
	fittings = [UnwrapElement(IN[0])]
	
count = []

for x in fittings:
	count.append(x.MEPModel.ConnectorManager.Connectors.Size)

#Assign your output to the OUT variable.
OUT = count</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="1996340b-780e-4c46-b22e-e8851d3fb981" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="80" y="273" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Fittings" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="f31632b6-8d01-459a-82d6-7a0c5a08dd90" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="507" y="247" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Connector Count" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="718130a3-5b55-40bc-9c39-44732d72d39c" start_index="0" end="f31632b6-8d01-459a-82d6-7a0c5a08dd90" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1996340b-780e-4c46-b22e-e8851d3fb981" start_index="0" end="718130a3-5b55-40bc-9c39-44732d72d39c" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>