<Workspace Version="1.2.0.2831" X="-643.157800887216" Y="-308.428801234375" zoom="1.545620359375" Name="ElectricalCircuit Get Panels and Elements" Description="Returns the Panels and Elements belonging to the given electrical circuits" ID="e485d345-342c-403b-af78-a6387e65711b" Category="MEPover.Revit.Systems">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="63e2af37-d930-46df-8b0e-dc2a0fc8e513" type="PythonNodeModels.PythonNode" nickname="Python Script" x="560" y="329" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
if isinstance(IN[0], list):
	systems = UnwrapElement(IN[0])
	toggle = 0
else:
	systems = [UnwrapElement(IN[0])]
	toggle = 1
panels = []
elements = []

for x in systems:
	panels.append(x.BaseEquipment)
	sublist = []
	elementset = x.Elements
	for x in elementset:
		sublist.append(x)
	elements.append(sublist)

#Assign your output to the OUT variable.
if toggle:
	OUT = panels[0], sublist
else:
	OUT = panels, elements</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="f87dc955-fbdc-4dee-a1f8-b952d3ccbee7" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="770" y="278" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="x[0];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="f453b89c-3feb-4e9c-904d-1896ddbb805f" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="767" y="386" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="x[1];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="a5e82a8c-0770-402e-9fbd-03a194beaa95" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1009" y="273" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Panels" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="5f0ce2e4-e4ba-4166-b136-0260af263353" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="991" y="389" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Elements" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="5392afa7-9e94-437f-900d-7d82f937981a" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="276" y="312" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Electrical Circuits" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="63e2af37-d930-46df-8b0e-dc2a0fc8e513" start_index="0" end="f87dc955-fbdc-4dee-a1f8-b952d3ccbee7" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="63e2af37-d930-46df-8b0e-dc2a0fc8e513" start_index="0" end="f453b89c-3feb-4e9c-904d-1896ddbb805f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f87dc955-fbdc-4dee-a1f8-b952d3ccbee7" start_index="0" end="a5e82a8c-0770-402e-9fbd-03a194beaa95" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f453b89c-3feb-4e9c-904d-1896ddbb805f" start_index="0" end="5f0ce2e4-e4ba-4166-b136-0260af263353" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5392afa7-9e94-437f-900d-7d82f937981a" start_index="0" end="63e2af37-d930-46df-8b0e-dc2a0fc8e513" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>