<Workspace Version="1.3.2.2480" X="-1384.21336323889" Y="-926.789922441715" zoom="3.14224078322401" ScaleFactor="1" Name="Element.Connectors" Description="Returns every connector on an element (also return connectors of a System)" ID="37ef70e6-cf97-40b9-b584-2d68d77d5057" Category="MEPover.Revit.Connectors">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="91405a3d-5799-4b4a-b58d-4ec2ffa65dae" type="PythonNodeModels.PythonNode" nickname="Python: Connector" x="573" y="334" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>
import clr
import math

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)
#The inputs to this node will be stored as a list in the IN variables.
if isinstance(IN[0], list):
	elements = UnwrapElement(IN[0])
	toggle = 0
else:
	toggle = 1
	elements = [UnwrapElement(IN[0])]
	

listout = []

for element in elements:
	try:
		connectors = element.MEPModel.ConnectorManager.Connectors
	except:
		try:
			connectors = element.ConnectorManager.Connectors
		except:			
			connectors = []
	listout.append([x for x in connectors])


#Assign your output to the OUT variable.
if toggle:
	OUT = connectors
else:
	OUT = listout</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="c8eecda6-3cef-4b98-951d-478cc29dd5e0" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="280" y="381" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Element" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="fdce0446-205e-4ec3-a565-6a9b8c58af69" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="771" y="333" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Connectors" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="91405a3d-5799-4b4a-b58d-4ec2ffa65dae" start_index="0" end="fdce0446-205e-4ec3-a565-6a9b8c58af69" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c8eecda6-3cef-4b98-951d-478cc29dd5e0" start_index="0" end="91405a3d-5799-4b4a-b58d-4ec2ffa65dae" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>