<Workspace Version="1.2.1.3083" X="-57.166875807053" Y="-12.023567338392" zoom="0.931811528498331" Name="FlexCurve.ByPoints" Description="Create a flex pipe or duct by a list of points, system type, flex duct type or flex pipe type, level and diameter." ID="a855cf9e-009f-4844-87c8-59e351fe5df0" Category="MEPover.Revit.Elements">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="92ca0d0c-fbbf-40a8-bc8d-d3471acdb420" type="PythonNodeModels.PythonNode" nickname="Python Script" x="401" y="172" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="5">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <PortInfo index="3" default="False" />
      <PortInfo index="4" default="False" />
      <Script>#made by Taco Pover
import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference('System')		
from System.Collections.Generic import List

if isinstance(IN[0][0], list):
	curvepoints = IN[0]
else:
	curvepoints = [IN[0]]

if isinstance(IN[1], list):
	systype = UnwrapElement(IN[1])
else:
	systype = [UnwrapElement(IN[1])]
sl = len(systype)

flextype = UnwrapElement(IN[2])

if isinstance(IN[3], list):
	level = UnwrapElement(IN[3])
else:
	level = [UnwrapElement(IN[3])]
ll = len(level)

if isinstance(IN[4], list):
	diameter = IN[4]
else:
	diameter = [IN[4]]
dl = len(diameter)

metric = doc.DisplayUnitSystem == DisplayUnit.METRIC

def createFlexPipe(systype,levelid,starttan,endtan,points,diameter):
	flex = Plumbing.FlexPipe.Create(doc,systype,flextype.Id,levelid,starttan,endtan,points)
	param = flex.get_Parameter(BuiltInParameter.RBS_PIPE_DIAMETER_PARAM)
	if metric:
		param.Set(diameter/304.8)
	else:
		param.Set(diameter)
	return flex
	
	
def createFlexDuct(systype,levelid,starttan,endtan,points,diameter):
	flex = Mechanical.FlexDuct.Create(doc,systype,flextype.Id,levelid,starttan,endtan,points)
	param = flex.get_Parameter(BuiltInParameter.RBS_CURVE_DIAMETER_PARAM)
	if metric:
		param.Set(diameter/304.8)
	else:
		param.Set(diameter)
	return flex

newflex = []

TransactionManager.Instance.EnsureInTransaction(doc)
for i,p in enumerate(curvepoints):
	levelid = level[i%ll].Id
	sysid = systype[i%sl].Id
	diam = diameter[i%dl]
	
	points = List[XYZ]()
	for x in p:
		points.Add(x.ToXyz())
		
	starttang = points[1].Subtract(points[0])
	last = points.Count - 1
	secondlast = last -1
	endtang = points[last].Subtract(points[secondlast])

	if flextype.GetType() == Plumbing.FlexPipeType:
		flex = createFlexPipe(sysid,levelid,starttang,endtang,points,diam)
	else:
		flex = createFlexDuct(sysid,levelid,starttang,endtang,points,diam)

	newflex.append(flex.ToDSType(False))
	
TransactionManager.Instance.TransactionTaskDone()

			

OUT = newflex</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="f483c3df-33f3-4b35-907d-9e11e2826fe6" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="120" y="102" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Points" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="ef2eec5b-eec4-4288-8d00-8dc5c3a71bd3" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="118" y="173" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="SystemType" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="c55b970a-daa8-4fb9-b4a2-e98356f7e72c" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="111" y="249" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="FlexType" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="c7ca5729-85c3-444c-b37e-7b50ad120256" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="103" y="329" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Level" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="df2fd14c-c452-48e2-a2d6-a5d778417fa5" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="98" y="424" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Diameter" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="eb493d78-6706-4809-a886-807726631cb3" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="602.889848812095" y="177.833693304536" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="FlexCurves" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="92ca0d0c-fbbf-40a8-bc8d-d3471acdb420" start_index="0" end="eb493d78-6706-4809-a886-807726631cb3" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f483c3df-33f3-4b35-907d-9e11e2826fe6" start_index="0" end="92ca0d0c-fbbf-40a8-bc8d-d3471acdb420" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ef2eec5b-eec4-4288-8d00-8dc5c3a71bd3" start_index="0" end="92ca0d0c-fbbf-40a8-bc8d-d3471acdb420" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c55b970a-daa8-4fb9-b4a2-e98356f7e72c" start_index="0" end="92ca0d0c-fbbf-40a8-bc8d-d3471acdb420" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c7ca5729-85c3-444c-b37e-7b50ad120256" start_index="0" end="92ca0d0c-fbbf-40a8-bc8d-d3471acdb420" end_index="3" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="df2fd14c-c452-48e2-a2d6-a5d778417fa5" start_index="0" end="92ca0d0c-fbbf-40a8-bc8d-d3471acdb420" end_index="4" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-51.6668472290039" eyeY="11579.779296875" eyeZ="17441.267578125" lookX="3795.5234375" lookY="-4111.81689453125" lookZ="-18345.029296875" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>