<Workspace Version="1.2.0.2831" X="-34.33" Y="29.185" zoom="0.8425" Name="MechanicalFitting info" Description="Gets the fitting Part Type and number of connectors" ID="03d22a92-64df-48e2-a531-f2f582e99312" Category="MEPover.Revit.Elements">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="0da8166e-8820-485a-b08b-acdc5b5fe24b" type="PythonNodeModels.PythonNode" nickname="Python Script" x="310" y="252" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
if isinstance(IN[0], list):
	fittings = UnwrapElement(IN[0])
else:
	fittings = [UnwrapElement(IN[0])]
	
count = []
types = []

for x in fittings:
	count.append(x.MEPModel.ConnectorManager.Connectors.Size)
	types.append(x.MEPModel.PartType)

#Assign your output to the OUT variable.
OUT = count, types</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="5adcef6e-fa6c-4df4-94a8-327f3e95e7ab" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="642" y="228" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Connector Count" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="fe6da865-8d33-4e0d-a533-eec149def1f2" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="479" y="236" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="x[0];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="33b5879f-d255-4475-bc64-9dec88c982fd" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="479.5" y="326.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="x[1];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="43f12472-5fda-49e9-9b38-2bf01c9151d5" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="642.5" y="335.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Part Type" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="81c72da4-057d-49da-8d38-8f37757419a7" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="102" y="251" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Fittings" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="0da8166e-8820-485a-b08b-acdc5b5fe24b" start_index="0" end="fe6da865-8d33-4e0d-a533-eec149def1f2" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0da8166e-8820-485a-b08b-acdc5b5fe24b" start_index="0" end="33b5879f-d255-4475-bc64-9dec88c982fd" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="fe6da865-8d33-4e0d-a533-eec149def1f2" start_index="0" end="5adcef6e-fa6c-4df4-94a8-327f3e95e7ab" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="33b5879f-d255-4475-bc64-9dec88c982fd" start_index="0" end="43f12472-5fda-49e9-9b38-2bf01c9151d5" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="81c72da4-057d-49da-8d38-8f37757419a7" start_index="0" end="0da8166e-8820-485a-b08b-acdc5b5fe24b" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>