<Workspace Version="1.2.0.2831" X="0" Y="0" zoom="1" Name="MEP Curve connected fittings" Description="Returns the fittings, ducts accessories and terminals connected to the given duct, cable tray, pipe or conduit. Also return air terminals on Ducts" ID="4d4d8b43-ed79-45ad-8c82-aa6353b2b05f" Category="MEPover.Revit.Elements">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="8b91ed13-5253-44be-86b0-9accb495acab" type="PythonNodeModels.PythonNode" nickname="Python Script" x="247" y="245" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
if isinstance(IN[0], list):
	curves = UnwrapElement(IN[0])
else:
	curves = [UnwrapElement(IN[0])]

refs = []

for curve in curves:
	connMan = curve.ConnectorManager
	fittings = []
	for conn in connMan.Connectors:
		if conn.IsConnected:
			for lc in conn.AllRefs:
				if connMan.Owner.Id !=  lc.Owner.Id:
					fittings.append(lc.Owner)
	refs.append(fittings)

#Assign your output to the OUT variable.
OUT = refs</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="7d6a2199-b382-4fa9-9797-a170310dc248" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="40" y="224" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="MEP Curves" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="256ef4b2-2e08-4cb5-93cb-66b36ebf35cb" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="467" y="235" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Fittings" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="8b91ed13-5253-44be-86b0-9accb495acab" start_index="0" end="256ef4b2-2e08-4cb5-93cb-66b36ebf35cb" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7d6a2199-b382-4fa9-9797-a170310dc248" start_index="0" end="8b91ed13-5253-44be-86b0-9accb495acab" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>