<Workspace Version="1.2.0.2831" X="0" Y="0" zoom="1" Name="MEP Fitting connected MEPCurves" Description="Returns the pipes, ducts, conduits or cable trays that are connected to the given fittings" ID="5d34fdf8-fb8e-423d-a421-92bb6fc95455" Category="MEPover.Revit.Elements">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="d7a61785-4240-4fa2-88cf-9d3f06e12fee" type="PythonNodeModels.PythonNode" nickname="Python Script" x="274" y="250" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
if isinstance(IN[0], list):
	fittings = UnwrapElement(IN[0])
else:
	fittings = [UnwrapElement(IN[0])]

refs = []

for x in fittings:
	connset = x.MEPModel.ConnectorManager.Connectors
	conn_pipes = []
	for c in connset:
		if c.IsConnected:
			for lc in c.AllRefs:
				conn_pipes.append(lc.Owner)
	refs.append(conn_pipes)

#Assign your output to the OUT variable.
OUT = refs</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="ba8869e6-73ac-40f0-98b3-d82bacc22809" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="97" y="235" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Fittings" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="973309a6-fd97-4d85-976b-989582afe9d3" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="489" y="244" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="MEP curves" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="d7a61785-4240-4fa2-88cf-9d3f06e12fee" start_index="0" end="973309a6-fd97-4d85-976b-989582afe9d3" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ba8869e6-73ac-40f0-98b3-d82bacc22809" start_index="0" end="d7a61785-4240-4fa2-88cf-9d3f06e12fee" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>