<Workspace Version="1.3.2.2480" X="-7.72950517003926" Y="149.298027098245" zoom="0.76669208910492" ScaleFactor="1" Name="MEPCurveType.JunctionType" Description="Returns the preferred JunctionType (tap or tee) of a DuctType or PipeType" ID="6de47112-123b-41a8-8e0d-cddb356b13cb" Category="MEPover.Revit.Elements">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="32da7e3f-a604-4651-8c59-82f20edc59aa" type="PythonNodeModels.PythonNode" nickname="Python Script" x="416" y="168" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

#Many thanks to Konrad K Sobon for his awesome ProcessList function!
def Unwrap(item):
	return UnwrapElement(item)

def ProcessList(_func, _list):
    return map( lambda x: ProcessList(_func, x) if type(x)==list else _func(x), _list )

if isinstance(IN[0], list):
	pipetypes = ProcessList(Unwrap, IN[0])
else:
	pipetypes = [Unwrap(IN[0])]
	
	
def getJunctionType(pipetype):
	return pipetype.RoutingPreferenceManager.PreferredJunctionType



OUT = ProcessList(getJunctionType, pipetypes)</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="3d055eb3-2d74-4dd4-b39a-066ae714f4cd" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="228.869867969849" y="158.437420880115" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="MEPCurveType" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="7137c9b8-01ea-443e-b229-f417183d9c97" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="604.951980452261" y="158.440405154344" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="JunctionType" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="32da7e3f-a604-4651-8c59-82f20edc59aa" start_index="0" end="7137c9b8-01ea-443e-b229-f417183d9c97" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3d055eb3-2d74-4dd4-b39a-066ae714f4cd" start_index="0" end="32da7e3f-a604-4651-8c59-82f20edc59aa" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>