<Workspace Version="1.2.1.3083" X="0" Y="0" zoom="1" Name="MEPFitting.ByMEPCurves" Description="Creates a UnionFitting or ElbowFitting by 2 MEPCurves (Ducts, Cable Trays, Pipes or Conduits). The output may not always be all the fittings created as Revit sometimes creates extra transition fittings outside of the node transactions." ID="82f54f53-50fa-44a8-9cf0-093a797467fd" Category="MEPover.Revit.Elements">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="66a2630a-6078-448d-a9fe-3d66b1fda453" type="PythonNodeModels.PythonNode" nickname="Python Script" x="280" y="220" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

if isinstance(IN[0], list):
	pipe1 = UnwrapElement(IN[0])
else:
	pipe1 = [UnwrapElement(IN[0])]
if isinstance(IN[1], list):
	pipe2 = UnwrapElement(IN[1])
else:
	pipe2 = [UnwrapElement(IN[1])]

def closest_connectors(pipe1, pipe2):
	conn1 = pipe1.ConnectorManager.Connectors
	conn2 = pipe2.ConnectorManager.Connectors
	
	dist = 100000000
	connset = None
	for c in conn1:
		for d in conn2:
			conndist = c.Origin.DistanceTo(d.Origin)
			if conndist &lt; dist:
				dist = conndist
				connset = [c,d]
	return connset

	
def check_dir(conn1,conn2):
	if conn1.CoordinateSystem.BasisZ.ToString() == conn2.CoordinateSystem.BasisZ.ToString() or conn1.CoordinateSystem.BasisZ.ToString() == (conn2.CoordinateSystem.BasisZ*-1).ToString():
		return True
	else:
		return False
	
fittings = []

for p1,p2 in zip(pipe1,pipe2):
	connectors = closest_connectors(p1,p2)
	
	if check_dir(connectors[0],connectors[1]):
		TransactionManager.Instance.EnsureInTransaction(doc)
		
		fitting = doc.Create.NewUnionFitting(connectors[0],connectors[1])
		try:
			fittings.append(fitting.ToDSType(False))
		except:
			fittings.append("fitting not created by Dynamo")
		
		TransactionManager.Instance.TransactionTaskDone()
	else:
		TransactionManager.Instance.EnsureInTransaction(doc)
	
		fitting = doc.Create.NewElbowFitting(connectors[0],connectors[1])
		fittings.append(fitting.ToDSType(False))
		
		TransactionManager.Instance.TransactionTaskDone()

			

OUT = fittings</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="badf6c39-3d0b-481e-ad07-348de414a86f" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="77" y="208" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="MEPCurve1" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="46ab4d06-01d5-4887-bf98-ab56caa58687" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="72" y="287" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="MEPCurve2" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="3d0c0d6d-f513-4ca8-a006-e114a8c1dfc7" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="492" y="219" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Fittings" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="66a2630a-6078-448d-a9fe-3d66b1fda453" start_index="0" end="3d0c0d6d-f513-4ca8-a006-e114a8c1dfc7" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="badf6c39-3d0b-481e-ad07-348de414a86f" start_index="0" end="66a2630a-6078-448d-a9fe-3d66b1fda453" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="46ab4d06-01d5-4887-bf98-ab56caa58687" start_index="0" end="66a2630a-6078-448d-a9fe-3d66b1fda453" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>