<Workspace Version="1.2.2.373" X="-429.412450585781" Y="-297.767757705469" zoom="1.78359936238281" Name="MEPSystem.DivideSystem" Description="Divide a duct or piping system into separate systems if possible" ID="f41f9715-f8e0-458d-95be-35be70591cc0" Category="MEPover.Revit.Systems">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="db5040f7-6fec-4187-a4b9-ea31c2032314" type="PythonNodeModels.PythonNode" nickname="Python: Divide system" x="465" y="324" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

if isinstance(IN[0], list):
	systems = UnwrapElement(IN[0])
else:
	systems = [UnwrapElement(IN[0])]
	
listout = []
TransactionManager.Instance.EnsureInTransaction(doc)
for sys in systems:
	if sys.IsMultipeNetwork:
		ids = sys.DivideSystem(doc)
		sublist = []
		for id in ids:
			sublist.append(doc.GetElement(id).ToDSType(True))
		listout.append(sublist)
TransactionManager.Instance.TransactionTaskDone()

OUT = listout</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="32a9fa00-cd71-4829-bbfc-1b8be799a42e" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="274" y="330" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="System" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="eed850eb-a750-476b-b448-9481bed3f5a7" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="687" y="329" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Separated Systems" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="db5040f7-6fec-4187-a4b9-ea31c2032314" start_index="0" end="eed850eb-a750-476b-b448-9481bed3f5a7" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="32a9fa00-cd71-4829-bbfc-1b8be799a42e" start_index="0" end="db5040f7-6fec-4187-a4b9-ea31c2032314" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>