<Workspace Version="1.3.2.2480" X="0" Y="0" zoom="1" ScaleFactor="1" Name="Pipe.ByLines" Description="Creates a pipe by Line, PipeType, SystemType, Level and Diameter" ID="410c1c30-be13-4789-99f3-e39e074d127e" Category="MEPover.Revit.Elements">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="5c6492d1-408b-4d49-ad51-5a968872a90a" type="PythonNodeModels.PythonNode" nickname="Python Script" x="281" y="207" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="5">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <PortInfo index="3" default="False" />
      <PortInfo index="4" default="False" />
      <Script>import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)


if isinstance(IN[0], list):
	lines = IN[0]
else:
	lines = [IN[0]]
FirstPoint = [x.StartPoint for x in lines]
SecondPoint = [x.EndPoint for x in lines]
if isinstance(IN[1], list):
	pipetype = UnwrapElement(IN[1])
else:
	pipetype = [UnwrapElement(IN[1])]
ptl = len(pipetype)

if isinstance(IN[2], list):
	systemtype = UnwrapElement(IN[2])
else:
	systemtype = [UnwrapElement(IN[2])]
stl = len(systemtype)
if isinstance(IN[3], list):
	level = UnwrapElement(IN[3])
else:
	level = [UnwrapElement(IN[3])]
ll = len(level)
if isinstance(IN[4], list):
	diameter = IN[4]
else:
	diameter = [IN[4]]
dl = len(diameter)

elements = []

TransactionManager.Instance.EnsureInTransaction(doc)
for i,x in enumerate(FirstPoint):
	try:
		levelid = level[i%ll].Id
		systypeid = systemtype[i%stl].Id
		pipetypeid = pipetype[i%ptl].Id
		diam = diameter[i%dl]
		
		pipe = Autodesk.Revit.DB.Plumbing.Pipe.Create(doc,systypeid,pipetypeid,levelid,x.ToXyz(),SecondPoint[i].ToXyz())
		
		param = pipe.get_Parameter(BuiltInParameter.RBS_PIPE_DIAMETER_PARAM)
		param.SetValueString(diam.ToString())
	
		elements.append(pipe.ToDSType(False))	
	except:
		elements.append(None)

TransactionManager.Instance.TransactionTaskDone()


OUT = elements
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="6937baaa-cb31-48f7-a206-b4f827b4681b" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="482" y="205" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Pipes" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="191fbde5-9ce3-4ac0-8bf0-dc4a96d403cb" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="60" y="167" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Lines" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="7b80d37a-7ec0-4f8b-a680-dd88fc1d5801" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="58" y="243" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="PipeType" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="a3b1118c-af11-4c70-ba9b-9d2ada82bc5f" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="55" y="311" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="SystemType" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="6ca9ad69-7ada-4e07-8b7b-763de137809d" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="64" y="392" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Level" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="5e7ca54d-5bf3-4295-966c-bfc1a58536fb" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="65" y="471" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Diameter" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="5c6492d1-408b-4d49-ad51-5a968872a90a" start_index="0" end="6937baaa-cb31-48f7-a206-b4f827b4681b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="191fbde5-9ce3-4ac0-8bf0-dc4a96d403cb" start_index="0" end="5c6492d1-408b-4d49-ad51-5a968872a90a" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7b80d37a-7ec0-4f8b-a680-dd88fc1d5801" start_index="0" end="5c6492d1-408b-4d49-ad51-5a968872a90a" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a3b1118c-af11-4c70-ba9b-9d2ada82bc5f" start_index="0" end="5c6492d1-408b-4d49-ad51-5a968872a90a" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6ca9ad69-7ada-4e07-8b7b-763de137809d" start_index="0" end="5c6492d1-408b-4d49-ad51-5a968872a90a" end_index="3" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5e7ca54d-5bf3-4295-966c-bfc1a58536fb" start_index="0" end="5c6492d1-408b-4d49-ad51-5a968872a90a" end_index="4" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>