<Workspace Version="1.3.1.1736" X="-462" Y="-160" zoom="1" ScaleFactor="1" Name="PipeSegment.SetName" Description="Changes the name of the pipe segment (found under MEP Settings)" ID="f265a90d-5f4d-482a-8677-b489e8657a7e" Category="MEPover.Revit.Parameters">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="ebd64649-687d-4b19-8144-fcd7f1e6d1b3" type="PythonNodeModels.PythonNode" nickname="Python Script" x="960" y="484" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)
#The inputs to this node will be stored as a list in the IN variables.
segments = UnwrapElement(IN[0])

names = IN[1]


TransactionManager.Instance.EnsureInTransaction(doc)

segments.Name = names

TransactionManager.Instance.TransactionTaskDone()

#Assign your output to the OUT variable.
OUT = segments</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="2474ab9d-7e20-4bb1-a19f-72cfb68b1155" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="615" y="455" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Pipe Segments" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="0c9888db-1451-4696-a77b-e84c740cdba0" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="627" y="589" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Name : string" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="a176b24c-40a5-4484-b466-aacd4aecd41c" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1203" y="500" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Pipe Segments" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="ebd64649-687d-4b19-8144-fcd7f1e6d1b3" start_index="0" end="a176b24c-40a5-4484-b466-aacd4aecd41c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2474ab9d-7e20-4bb1-a19f-72cfb68b1155" start_index="0" end="ebd64649-687d-4b19-8144-fcd7f1e6d1b3" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0c9888db-1451-4696-a77b-e84c740cdba0" start_index="0" end="ebd64649-687d-4b19-8144-fcd7f1e6d1b3" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>