<Workspace Version="1.3.2.2480" X="-44.4502374479295" Y="-81.4417384066925" zoom="1.26333177263822" ScaleFactor="1" Name="RoomAtPoint" Description="Returns the room at the location of the point. Returns null if no room is there" ID="9f195bcb-2396-4141-96b3-b582576f937f" Category="MEPover.Revit.RoomsAndSpaces">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="f6ac1adb-0bb3-4e5f-94e4-71d05a5b4dc7" type="PythonNodeModels.PythonNode" nickname="Python Script" x="315" y="233" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

if IN[2] != None:
	doc = IN[2]

if isinstance(IN[0], list):
	point = [x.ToXyz() for x in IN[0]]
	toggle = 0
else:
	point = [IN[0].ToXyz()]
	toggle = 1
phase = UnwrapElement(IN[1])

listout = []
for p in point:
	space = doc.GetRoomAtPoint(p,phase)
	listout.append(space)

if toggle:
	OUT = space
else:
	OUT = listout</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="8be8973b-e19e-409b-a855-d99bbd8d61e3" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="196.740838681434" y="232.300731906804" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Point" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="d24a5ef6-787e-46b0-b0e2-44bff548f4e5" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="184.388251648014" y="312.70492514959" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Phase" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="289768df-c202-4e9f-bbd6-765acd2e4821" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="495.196592834406" y="239.990413173225" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Room" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="4fe95472-c551-4816-9294-54cd7f33afdd" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="125.78384519403" y="422.942503645644" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Document = null" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="f6ac1adb-0bb3-4e5f-94e4-71d05a5b4dc7" start_index="0" end="289768df-c202-4e9f-bbd6-765acd2e4821" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8be8973b-e19e-409b-a855-d99bbd8d61e3" start_index="0" end="f6ac1adb-0bb3-4e5f-94e4-71d05a5b4dc7" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d24a5ef6-787e-46b0-b0e2-44bff548f4e5" start_index="0" end="f6ac1adb-0bb3-4e5f-94e4-71d05a5b4dc7" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4fe95472-c551-4816-9294-54cd7f33afdd" start_index="0" end="f6ac1adb-0bb3-4e5f-94e4-71d05a5b4dc7" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>