<Workspace Version="1.2.0.2831" X="0" Y="0" zoom="1" Name="Rooms place automatically for all levels" Description="This node will attempt to create rooms automatically for every level" ID="8c3667d4-0905-44f6-9150-a65a755c2518" Category="MEPover.Revit.RoomsAndSpaces">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="7afe70be-f6fe-4ff1-8bf2-429be89961c1" type="PythonNodeModels.PythonNode" nickname="Python Script" x="246" y="203" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

collector = FilteredElementCollector(doc)
levels = collector.OfClass(Level).ToElements()

phase = UnwrapElement(IN[0])
limitoffset = 8
listout = []

for j,level in enumerate(levels):
	try:
		planTopology = doc.get_PlanTopology(level)
		rooms = []
		
		for i,plancircuit in enumerate(planTopology.Circuits):
			if plancircuit.IsRoomLocated == True:
				continue
			TransactionManager.Instance.EnsureInTransaction(doc)
			room = doc.Create.NewRoom(phase)
			room.Name = "Name" + str(i)
			room.Number = str(j) + "." + str(i)
			room.LimitOffset = limitoffset
			try:
				room2 = doc.Create.NewRoom(room,plancircuit)
			except:
				continue
			TransactionManager.Instance.TransactionTaskDone()
			rooms.append(room2)
		listout.append(rooms)
	except:
		continue


OUT = listout</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="45803d41-1d89-47cb-8d5d-51b1ec187566" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="63" y="184" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Phase" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="84ef594f-b99f-4d20-97a7-b07587c13250" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="444" y="208" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Rooms" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="7afe70be-f6fe-4ff1-8bf2-429be89961c1" start_index="0" end="84ef594f-b99f-4d20-97a7-b07587c13250" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="45803d41-1d89-47cb-8d5d-51b1ec187566" start_index="0" end="7afe70be-f6fe-4ff1-8bf2-429be89961c1" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>