<Workspace Version="1.3.2.2480" X="0" Y="0" zoom="1" ScaleFactor="1" Name="SpaceAtPoint" Description="Returns the space at the location of the point. Returns null if no space is there" ID="7e019e5a-8dc5-4418-8cee-2998b48d9e83" Category="MEPover.Revit.RoomsAndSpaces">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="205dd756-2c1f-4aa2-b3e7-9b8925991c93" type="PythonNodeModels.PythonNode" nickname="Python Script" x="289" y="179" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

if isinstance(IN[0], list):
	point = [x.ToXyz() for x in IN[0]]
	toggle = 0
else:
	point = [IN[0].ToXyz()]
	toggle = 1
phase = UnwrapElement(IN[1])

listout = []
for p in point:
	space = doc.GetSpaceAtPoint(p,phase)
	listout.append(space)

if toggle:
	OUT = space
else:
	OUT = listout</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="dcbc7a9e-1809-4faf-aa75-a7e09ddf6e4f" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="86" y="136" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Point" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="022f8ec2-a6ad-458e-951b-2305a1ceaaf4" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="85" y="274" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Phase" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="c03d8471-1771-465d-a3fc-1c2c2926a4b5" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="509" y="178" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Space" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="205dd756-2c1f-4aa2-b3e7-9b8925991c93" start_index="0" end="c03d8471-1771-465d-a3fc-1c2c2926a4b5" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="dcbc7a9e-1809-4faf-aa75-a7e09ddf6e4f" start_index="0" end="205dd756-2c1f-4aa2-b3e7-9b8925991c93" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="022f8ec2-a6ad-458e-951b-2305a1ceaaf4" start_index="0" end="205dd756-2c1f-4aa2-b3e7-9b8925991c93" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>