<Workspace Version="1.2.1.3083" X="129" Y="-52" zoom="1" Name="Space number to duct network concatenate" Description="This node will attempt to write the space numbers to connected duct objects in the network. Input AirTerminals need to be placed in spaces. ParameterName is the parameter to write the space number to. Numbers will be concatenated if they serve multiple spaces. Multiple Categories supported" ID="5afcf4db-1561-493e-9e3b-958203697f8b" Category="MEPover.Revit.RoomsAndSpaces">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="66131311-bdba-441e-93b3-9e8038b2de3b" type="PythonNodeModels.PythonNode" nickname="Python Script" x="301" y="221" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="4">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <PortInfo index="3" default="False" />
      <Script>
import clr
import math

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)
#The inputs to this node will be stored as a list in the IN variables.
if isinstance(IN[0], list):
	elements = UnwrapElement(IN[0])
else:
	elements = [UnwrapElement(IN[0])]
	
def getSize(x):
	try:
		conns = x.ConnectorManager.Connectors
	except:
		conns = x.MEPModel.ConnectorManager.Connectors
	maxsize = 0
	for c in conns:
		if c.Shape == ConnectorProfileType.Round:
			startsize = c.Radius * 2
		elif c.Shape == ConnectorProfileType.Invalid:
			continue
		else:
			area = c.Width * c.Height
			startsize = (math.sqrt(area/math.pi) * 2)
		if startsize &gt; maxsize:
			maxsize = startsize
	return maxsize
	
phaseId = elements[0].CreatedPhaseId
phase = doc.GetElement(phaseId)
name = IN[1]
if isinstance(IN[2], list):
	category = UnwrapElement(IN[2])
else:
	category = [UnwrapElement(IN[2])]
	
factor = IN[3]

catIds = []
for c in category:
	catIds.append(c.Id)

def checkParameter(param):
	for p in param:
		internal = p.Definition
		if internal.BuiltInParameter != BuiltInParameter.INVALID:
			return p
	return param[0]


def nextElement(elem,sys):
	sysname = next.get_Parameter(BuiltInParameter.RBS_SYSTEM_CLASSIFICATION_PARAM).AsString()
	for s in sysname.split(","):
		if s in sys.split(","):
			break
	else:
		return 4
	if "Return Air" in sysname:
		direction = FlowDirectionType.In
	else:
		direction = FlowDirectionType.Out
	try:
		connectors = elem.ConnectorManager.Connectors
		for conn in connectors:
			if conn.Domain != Domain.DomainHvac:
				continue
			elif conn.Direction == direction:
				continue
			else:
				endconn = conn
		for c in endconn.AllRefs:
			if c.Owner.Id.Equals(elem.Id):
				continue
			elif c.Owner.GetType() == Mechanical.MechanicalSystem:
				return 0
			else:
				newelem = c.Owner
		return newelem
	except AttributeError:
		connectors = elem.MEPModel.ConnectorManager.Connectors
		if connectors.Size == 1:
			for conn in connectors:
				if conn.Domain != Domain.DomainHvac:
					continue
				endconn = conn
			if endconn.AllRefs.Size == 1:
				for c in endconn.AllRefs:
					if c.Owner.GetType() == Mechanical.MechanicalSystem:
						return 1
			for c in endconn.AllRefs:
				if c.Owner.Id.Equals(elem.Id):
					continue
				elif c.Owner.GetType() == Mechanical.MechanicalSystem:
					continue
				else:
					newelem = c.Owner
			return newelem
		elif connectors.Size == 2:
			for conn in connectors:
				if conn.Domain != Domain.DomainHvac:
					continue
				if conn.Direction == direction:
					continue
				else:
					endconn = conn
			if endconn.AllRefs.Size == 1:
				for c in endconn.AllRefs:
					if c.Owner.GetType() == Mechanical.MechanicalSystem:
						return 2
			for c in endconn.AllRefs:
				if c.Owner.Id.Equals(elem.Id):
					continue
				elif c.Owner.GetType() == Mechanical.MechanicalSystem:
					continue
				else:
					newelem = c.Owner
			return newelem
		else:
			for conn in connectors:
				if conn.Domain != Domain.DomainHvac:
					continue
				if conn.Direction != direction:
					endconn = conn
			if endconn.AllRefs.Size == 1:
				for c in endconn.AllRefs:
					if c.Owner.GetType() == Mechanical.MechanicalSystem:
						return 3
			for c in endconn.AllRefs:
				if c.Owner.Id.Equals(elem.Id):
					continue
				elif c.Owner.GetType() == Mechanical.MechanicalSystem:
					continue
				else:
					newelem = c.Owner
			return newelem



listout = []
result = []
for j,x in enumerate(elements):
	ids = []
	space = x.Space[phase]
	if space == None:
		listout.append("ElementId "+str(x.Id)+" is not in a space")
		continue
	spacenumber = space.Number
	sysclass = x.get_Parameter(BuiltInParameter.RBS_SYSTEM_CLASSIFICATION_PARAM).AsString()
	startsize = getSize(x)
	next = x
	i = 0
	while True:
		if i &gt; 1000:
			break
		try:
			next = nextElement(next,sysclass)
		except:
			result.append("error")
			break
		if isinstance(next, int):
			result.append("can't get next element")
			i += 1
			break
		i += 1
		nextsize = getSize(next)
		if nextsize &gt; startsize * factor:
			result.append("size end")
			break
		if next.Category.Id not in catIds:
			i += 1
			continue
		if next.Id in ids:
			result.append("double element")
			break
		p = next.GetParameters(name)
		if len(p) == 0:
			result.append("no param")
			break
		else:
			param = checkParameter(p)
		elem_num = param.AsString()
		if spacenumber in str(elem_num):
			continue
		else:
			if elem_num == "" or elem_num == None:
				newvalue = spacenumber
			else:
				newvalue = elem_num +","+ spacenumber
			TransactionManager.Instance.EnsureInTransaction(doc)
			param.Set(newvalue)
			TransactionManager.Instance.TransactionTaskDone()
			ids.append(next.Id)
	listout.append(x)

#Assign your output to the OUT variable.
OUT = listout, result</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="82664288-c379-4bb1-bb71-984486fc3cd2" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="29" y="198" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Air Terminals" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="6ba477a6-d971-49e9-ba57-99ec81cc11d9" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-53" y="276" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="ParameterName: string" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="624c3113-5bb6-42c8-9366-7a020ba9a87f" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-27" y="354" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Category" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="daf050cc-fca8-4a53-8ea7-6a239a5df557" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-79" y="447" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="SizeLimitFactor: int = 20" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="95e5c59e-b21a-4bfa-8132-2dba486d22ce" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="595" y="220" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Elements" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="b888e468-1f56-4a6e-a1ac-ce46ab0fc715" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="472" y="224" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="x[0];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="66131311-bdba-441e-93b3-9e8038b2de3b" start_index="0" end="b888e468-1f56-4a6e-a1ac-ce46ab0fc715" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="82664288-c379-4bb1-bb71-984486fc3cd2" start_index="0" end="66131311-bdba-441e-93b3-9e8038b2de3b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6ba477a6-d971-49e9-ba57-99ec81cc11d9" start_index="0" end="66131311-bdba-441e-93b3-9e8038b2de3b" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="624c3113-5bb6-42c8-9366-7a020ba9a87f" start_index="0" end="66131311-bdba-441e-93b3-9e8038b2de3b" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="daf050cc-fca8-4a53-8ea7-6a239a5df557" start_index="0" end="66131311-bdba-441e-93b3-9e8038b2de3b" end_index="3" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b888e468-1f56-4a6e-a1ac-ce46ab0fc715" start_index="0" end="95e5c59e-b21a-4bfa-8132-2dba486d22ce" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>