<Workspace Version="1.2.1.3083" X="-50" Y="0" zoom="1" Name="Tap.By2MEPCurves" Description="Create a new TakeoffFitting or Tap by takeoff pipe and through pipe" ID="c0f195d1-9db3-4b45-be67-78a98a5a8c69" Category="MEPover.Revit.Elements">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="4be06110-c6dc-439c-9fa0-eed91994da47" type="PythonNodeModels.PythonNode" nickname="Python Script" x="281" y="297" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

if isinstance(IN[0], list):
	pipe1 = UnwrapElement(IN[0])
else:
	pipe1 = [UnwrapElement(IN[0])]
if isinstance(IN[1], list):
	pipe2 = UnwrapElement(IN[1])
else:
	pipe2 = [UnwrapElement(IN[1])]

def closest_connectors(pipe1, pipe2):
	conn1 = pipe1.ConnectorManager.Connectors
	line = pipe2.Location.Curve
	
	dist = 100000000
	conn = None
	for c in conn1:
		conndist = line.Project(c.Origin).Distance
		if conndist &lt; dist:
			dist = conndist
			conn = c
	return conn

	
fittings = []

for i,x in enumerate(pipe2):
	connector = closest_connectors(pipe1[i],pipe2[i])
	
	TransactionManager.Instance.EnsureInTransaction(doc)
	
	fitting = doc.Create.NewTakeoffFitting(connector,x)
	fittings.append(fitting.ToDSType(False))
		
	TransactionManager.Instance.TransactionTaskDone()

			

OUT = fittings</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="93d6a4ba-3d96-471d-8bc9-c2469cf5dd9e" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="491" y="272" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Fittings" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="852a44b2-5abc-4342-b28e-1c57aa45faf5" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="51" y="257" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Branch MEPCurve" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="9a95015b-305e-48c6-ad05-4e64a54a3417" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="58" y="359" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Main MEPCurve" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="4be06110-c6dc-439c-9fa0-eed91994da47" start_index="0" end="93d6a4ba-3d96-471d-8bc9-c2469cf5dd9e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="852a44b2-5abc-4342-b28e-1c57aa45faf5" start_index="0" end="4be06110-c6dc-439c-9fa0-eed91994da47" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9a95015b-305e-48c6-ad05-4e64a54a3417" start_index="0" end="4be06110-c6dc-439c-9fa0-eed91994da47" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>