<Workspace Version="1.2.1.3083" X="-191.8825" Y="164.0575" zoom="0.8425" Name="Tee.By3MEPCurves" Description="Creates a new Tee fitting for the 3 input MEP curves (conduit, cable tray, duct or pipe). Only works with a perpendicular branch MEPCurve" ID="a18b738a-bbfe-460b-a2f3-e03c43bed16a" Category="MEPover.Revit.Elements">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="5946a1e1-fb10-4813-b6f2-6771c6aacfe3" type="PythonNodeModels.PythonNode" nickname="Python Script" x="444" y="285" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

if isinstance(IN[0], list):
	pipe1 = UnwrapElement(IN[0])
else:
	pipe1 = [UnwrapElement(IN[0])]
if isinstance(IN[1], list):
	pipe2 = UnwrapElement(IN[1])
else:
	pipe2 = [UnwrapElement(IN[1])]
if isinstance(IN[2], list):
	pipe3 = UnwrapElement(IN[2])
else:
	pipe3 = [UnwrapElement(IN[2])]

def closest_connectors(pipe1, pipe2,pipe3):
	conn1 = pipe1.ConnectorManager.Connectors
	conn2 = pipe2.ConnectorManager.Connectors
	conn3 = pipe3.ConnectorManager.Connectors
	
	dist1 = 100000000
	dist2 = 100000000
	connset = []
	for c in conn1:
		for d in conn2:
			conndist = c.Origin.DistanceTo(d.Origin)
			if conndist &lt; dist1:
				dist1 = conndist
				c1 = c
				d1 = d
		for e in conn3:
			conndist = c.Origin.DistanceTo(e.Origin)
			if conndist &lt; dist2:
				dist2 = conndist
				e1 = e
		connset = [c1,d1,e1]
	return connset

	
fittings = []
TransactionManager.Instance.EnsureInTransaction(doc)
for p1,p2,p3 in zip(pipe1,pipe2,pipe3):
	connectors = closest_connectors(p1,p2,p3)
	try:
		fitting = doc.Create.NewTeeFitting(connectors[0],connectors[1],connectors[2])
		fittings.append(fitting.ToDSType(False))
	except:
		fittings.append(None)
		
TransactionManager.Instance.TransactionTaskDone()

			

OUT = fittings</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="85b41225-a026-4e26-838e-6be5ea211ad4" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="154" y="207" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Main MEPCurve" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="c665a071-6e63-42bd-a9dd-4940e850b780" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="172" y="297" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Main MEPCurve" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="c27e2e45-df0b-421d-8fc6-901da8cde4e2" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="184" y="408" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Branch MEPCurve" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="a130e714-c994-4860-be49-0c8f455ce794" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="658" y="279" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Tee" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="5946a1e1-fb10-4813-b6f2-6771c6aacfe3" start_index="0" end="a130e714-c994-4860-be49-0c8f455ce794" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="85b41225-a026-4e26-838e-6be5ea211ad4" start_index="0" end="5946a1e1-fb10-4813-b6f2-6771c6aacfe3" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c665a071-6e63-42bd-a9dd-4940e850b780" start_index="0" end="5946a1e1-fb10-4813-b6f2-6771c6aacfe3" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c27e2e45-df0b-421d-8fc6-901da8cde4e2" start_index="0" end="5946a1e1-fb10-4813-b6f2-6771c6aacfe3" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>