<Workspace Version="1.2.1.3083" X="-143.616372947398" Y="24.7789697101662" zoom="1.07925372895183" Name="Tee.By2MEPCurves" Description="Creates a tee by a main curve and a branch MEP curve (duct, pipe, conduit, cable tray). Only works with perpendicular brand curves" ID="d4b6ac73-2a7e-40fd-9082-3560ac9dd731" Category="MEPover.Revit.Elements">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="8f7a9e6d-113b-43a6-ab7f-fdb6c6361c96" type="PythonNodeModels.PythonNode" nickname="Python Script" x="361" y="324" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
import math

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit	
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

from System.Collections.Generic import List

if isinstance(IN[0],list):
	curves1 = UnwrapElement(IN[0])
else:
	curves1 = [UnwrapElement(IN[0])]
if isinstance(IN[1],list):
	curves2 = UnwrapElement(IN[1])
else:
	curves2 = [UnwrapElement(IN[1])]
	
	
def closest_connectors(pipe1, pipe2,pipe3):
	conn1 = pipe1.ConnectorManager.Connectors
	conn2 = pipe2.ConnectorManager.Connectors
	conn3 = pipe3.ConnectorManager.Connectors
	
	dist1 = 100000000
	dist2 = 100000000
	connset = []
	for c in conn1:
		for d in conn3:
			conndist = c.Origin.DistanceTo(d.Origin)
			if conndist &lt; dist1:
				dist1 = conndist
				c1 = c
				d1 = d
		for e in conn2:
			conndist = c.Origin.DistanceTo(e.Origin)
			if conndist &lt; dist2:
				dist2 = conndist
				e1 = e
		connset = [c1,d1,e1]
	return connset
	

def newTee(conn1,conn2,conn3):
	fitting = doc.Create.NewTeeFitting(conn1,conn2,conn3)
	return fitting

fittings = []
	
TransactionManager.Instance.EnsureInTransaction(doc)
for curve1,curve2 in zip(curves1,curves2):
	try:
		try:
			width = curve2.Diameter
		except:
			width = curve2.Width
		#get startpoint and endpoint of curve1
		curve1Line = curve1.Location.Curve
		startpoint = curve1Line.GetEndPoint(0)
		endpoint = curve1Line.GetEndPoint(1)
		
		#get point perpendicular of curve2
		curve2Line = curve2.Location.Curve
		curve2start = curve2Line.GetEndPoint(0)
		pointmid = curve1Line.Project(curve2start).XYZPoint
		len1 = startpoint.DistanceTo(pointmid)
		len2 = len1 - width/2
		len3 = len1 + width/2
		
		midstart = curve1Line.Evaluate((len2/curve1Line.Length),True)
		midend = curve1Line.Evaluate((len3/curve1Line.Length),True)
		
		#change startpoint and endpoints so the longest piece of mepcurve is retained
		toggle = False
		if startpoint.DistanceTo(pointmid) &lt; endpoint.DistanceTo(pointmid):
			toggle = True
			temppoint = startpoint
			startpoint = endpoint
			endpoint = temppoint
			
			tempmid = midstart
			midstart = midend
			midend = tempmid
		
		#disconnect curve1:
		connectors1 = curve1.ConnectorManager.Connectors
		for conn in connectors1:
			if conn.Origin.IsAlmostEqualTo(startpoint):
				startconn = conn
			elif conn.Origin.IsAlmostEqualTo(endpoint):
				endconn = conn
		
		otherfitting = None
		for conn in endconn.AllRefs:
			if conn.IsConnectedTo(endconn):
				if conn.Owner.GetType() == FamilyInstance:
					otherfitting = conn.Owner
				endconn.DisconnectFrom(conn)
				
		#shorten existing curve and copy it
		if toggle:
			curve1.Location.Curve = Line.CreateBound(midstart,startpoint)
		else:
			curve1.Location.Curve = Line.CreateBound(startpoint,midstart)
		doc.Regenerate()
		OffsetZ = (midstart.Z - endpoint.Z)*-1
		OffsetX = (midstart.X - endpoint.X)*-1
		OffsetY = (midstart.Y - endpoint.Y)*-1
		direction = XYZ(OffsetX,OffsetY,OffsetZ)
		newelem = ElementTransformUtils.CopyElement(doc,curve1.Id,direction)
		curve3 = doc.GetElement(newelem[0])
		doc.Regenerate()
		
		#shorten new curve
		curve3.Location.Curve = Line.CreateBound(endpoint,midend)
		doc.Regenerate()
		
		connectors = closest_connectors(curve1,curve2,curve3)
	#	try:
		fitting = newTee(connectors[0],connectors[1],connectors[2])
		fittings.append(fitting.ToDSType(False))
		
		if otherfitting != None:
			connectors3 = curve3.ConnectorManager.Connectors
			for conn in connectors3:
				for conn2 in otherfitting.MEPModel.ConnectorManager.Connectors:
					if conn.Origin.IsAlmostEqualTo(conn2.Origin):
						conn.ConnectTo(conn2)
						break
	except:
		fittings.append(None)

	
TransactionManager.Instance.TransactionTaskDone()



#Assign your output to the OUT variable.
OUT = fittings</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="5abad73a-6e68-4703-a69a-9d48e692b940" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="148" y="277" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Main MEPCurve" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="03252ad2-3dec-4479-b89a-80ec7d9e6853" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="166" y="393" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Branch MEPCurve" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="f01bc70f-1262-4914-a901-b3af11901b8e" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="548" y="319" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Tee" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="8f7a9e6d-113b-43a6-ab7f-fdb6c6361c96" start_index="0" end="f01bc70f-1262-4914-a901-b3af11901b8e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5abad73a-6e68-4703-a69a-9d48e692b940" start_index="0" end="8f7a9e6d-113b-43a6-ab7f-fdb6c6361c96" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="03252ad2-3dec-4479-b89a-80ec7d9e6853" start_index="0" end="8f7a9e6d-113b-43a6-ab7f-fdb6c6361c96" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>