<Workspace Version="1.3.2.2480" X="-104" Y="-162" zoom="1" ScaleFactor="1" Name="Zone.AddSpaces" Description="Will add the spaces to zone" ID="2968a2b0-597a-4bd0-8bf7-8db3da3c58e5" Category="MEPover.Revit.RoomsAndSpaces">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="fbeacab1-682c-4f03-81aa-cb139570a38e" type="PythonNodeModels.PythonNode" nickname="Python Script" x="460" y="347" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)


def AddToZone(zone,spaces):
	TransactionManager.Instance.EnsureInTransaction(doc)
	if hasattr(spaces, "__iter__"):		
		for space in spaces:
			try:
				spaceset = Mechanical.SpaceSet()
				spaceset.Insert(space)
				zone.AddSpaces(spaceset)				
			except:
				pass
	else:
		try:
			spaceset = Mechanical.SpaceSet()
			spaceset.Insert(space)
			zone.AddSpaces(spaceset)
		except:
			pass
	TransactionManager.Instance.TransactionTaskDone()
	return zone

listout = []
if isinstance(IN[0], list):
	for i,zone in enumerate(UnwrapElement(IN[0])):
		listout.append(AddToZone(zone,UnwrapElement(IN[1])[i]))
else:
	listout.append(AddToZone(UnwrapElement(IN[0]),UnwrapElement(IN[1])))

OUT = listout</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="f92eb88f-00d4-48ff-9b87-b2c31a37cfb7" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="260" y="316" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Zone" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="7ddefec3-927d-4359-b210-4b96887c71f3" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="278" y="406" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Spaces" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="c8364b18-823a-42a8-9d38-295b04b8a934" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="666" y="354" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Zone" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="fbeacab1-682c-4f03-81aa-cb139570a38e" start_index="0" end="c8364b18-823a-42a8-9d38-295b04b8a934" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f92eb88f-00d4-48ff-9b87-b2c31a37cfb7" start_index="0" end="fbeacab1-682c-4f03-81aa-cb139570a38e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7ddefec3-927d-4359-b210-4b96887c71f3" start_index="0" end="fbeacab1-682c-4f03-81aa-cb139570a38e" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>