<Workspace Version="1.3.2.2480" X="249.048076177674" Y="181.261432099545" zoom="0.594339614371454" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Nodes.DSModelElementsSelection guid="03e3d315-04c1-453c-810d-25e072178de7" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="-596.79064936962" y="-15.943399458661" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <instance id="2904eef8-0955-4a07-81b4-9018fe744f99-001634c2" />
      <instance id="2904eef8-0955-4a07-81b4-9018fe744f99-001634eb" />
      <instance id="2904eef8-0955-4a07-81b4-9018fe744f99-00163526" />
      <instance id="2904eef8-0955-4a07-81b4-9018fe744f99-00163553" />
    </Dynamo.Nodes.DSModelElementsSelection>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="4a377d9e-c3d1-4cd5-921a-abca44d5c420" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="DetailCurve.Curve" x="-281.551159527501" y="27.8443530490297" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.DetailCurve.Curve">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="9f84fad3-e0d4-4ecc-84dc-50fc481dea9a" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="46.3249838214912" y="12.2661408882232" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Flatten@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="fc453161-beb6-4669-9cb0-0db5056425b1" type="PythonNodeModels.PythonNode" nickname="Python Script" x="338.484358340003" y="8.51023291400435" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference("ProtoGeometry")
from Autodesk.DesignScript.Geometry import *
clr.AddReference('DSCoreNodes') 
import DSCore
from DSCore import *


#The inputs to this node will be stored as a list in the IN variables.
if isinstance(IN[0], list):
    lines = UnwrapElement(IN[0])
else:
    lines = [UnwrapElement(IN[0])]

OUT = []
pershape = []

def line_intersects(p1sp,p1ep,p2sp,p2ep):
	xdiff = (p1sp.X - p1ep.X, p2sp.X - p2ep.X)
	ydiff = (p1sp.Y - p1ep.Y, p2sp.Y - p2ep.Y)
	
	def det(a1,a2,b1,b2):
		return a1 * b2 - a2 * b1
	
	div = det(xdiff[0],xdiff[1],ydiff[0],ydiff[1])
	if div &lt;&gt; 0:
		d = (det(p1sp.X,p1sp.Y,p1ep.X,p1ep.Y), det(p2sp.X,p2sp.Y,p2ep.X,p2ep.Y))
		x = det(d[0],d[1], xdiff[0],xdiff[1]) / div
		y = det(d[0],d[1], ydiff[0],ydiff[1]) / div
		if x &gt; p1sp.X and x &lt; p1ep.X and y &gt; p2sp.Y and y &lt; p2ep.Y:
			return Point.ByCoordinates(x,y)
for f in range(0, len(lines)):			
	for l1 in lines:
		p1sp = l1.StartPoint 
		p1ep = l1.EndPoint
		data = []
		for l2 in lines:
			if l1 != l2:
				p2sp = l2.StartPoint
				p2ep = l2.EndPoint
				if  p1sp.X &lt; p2sp.X and p1ep.X &gt; p2ep.X  or p1sp.Y &gt; p2sp.Y and p1ep.Y &lt; p2ep.Y:
					if not (line_intersects(p1sp,p1ep,p2sp,p2ep) is None):
						data.append(line_intersects(p1sp,p1ep,p2sp,p2ep))
		if len(data) &gt; 0:
			pershape.append(data)
	if len(pershape) &gt; 0:
		OUT.append(pershape)
		pershape = []
	else:
		OUT.append('No intersections found')
		pershape = []</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="03e3d315-04c1-453c-810d-25e072178de7" start_index="0" end="4a377d9e-c3d1-4cd5-921a-abca44d5c420" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4a377d9e-c3d1-4cd5-921a-abca44d5c420" start_index="0" end="9f84fad3-e0d4-4ecc-84dc-50fc481dea9a" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9f84fad3-e0d4-4ecc-84dc-50fc481dea9a" start_index="0" end="fc453161-beb6-4669-9cb0-0db5056425b1" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="8e3f2010-8756-4c9a-b06a-6269f18e5cda" annotationText="GET INTERSECTION POINTS" left="328.484358340003" top="-109.489767085996" width="207.703333333333" height="211" fontSize="30" InitialTop="8.51023291400435" InitialHeight="123" TextblockHeight="108" backgrouund="#FFC1D676">
      <Models ModelGuid="fc453161-beb6-4669-9cb0-0db5056425b1" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>