<Workspace Version="1.3.2.2480" X="327.569812652586" Y="299.765445712946" zoom="0.873239338949518" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="d24f65ee-e735-4cc2-aad8-8fb5b00a9c83" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="RIE.IntersectionsFromListOfLines" x="162.167937576242" y="55.9648446882022" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <ID value="42e2c8c4-1dba-4a24-aaae-5f5a52f94a1f" />
      <Name value="RIE.IntersectionsFromListOfLines" />
      <Description value="Outputs points on which lines in a list intersect" />
      <Inputs>
        <Input value="Lines" />
      </Inputs>
      <Outputs>
        <Output value="Points" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Nodes.DSModelElementsSelection guid="03e3d315-04c1-453c-810d-25e072178de7" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="-596.79064936962" y="-13.6136717981784" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <instance id="fc326867-c7ef-40da-9332-40c5e0f6a26a-005850bd" />
      <instance id="fc326867-c7ef-40da-9332-40c5e0f6a26a-005850be" />
      <instance id="fc326867-c7ef-40da-9332-40c5e0f6a26a-005850bf" />
      <instance id="fc326867-c7ef-40da-9332-40c5e0f6a26a-005850c0" />
      <instance id="fc326867-c7ef-40da-9332-40c5e0f6a26a-005850c1" />
      <instance id="fc326867-c7ef-40da-9332-40c5e0f6a26a-005850c2" />
      <instance id="fc326867-c7ef-40da-9332-40c5e0f6a26a-005850c3" />
      <instance id="fc326867-c7ef-40da-9332-40c5e0f6a26a-005850c4" />
      <instance id="fc326867-c7ef-40da-9332-40c5e0f6a26a-005850c5" />
    </Dynamo.Nodes.DSModelElementsSelection>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="8cb1971d-4534-4d85-81a3-8af66c2bdc7c" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Geometry.Intersect" x="-14.7206440574997" y="-180.68587589013" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Geometry.Intersect@Autodesk.DesignScript.Geometry.Geometry">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="cd210600-29b9-4959-bbd1-ee1e671ad23e" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Geometry.IntersectAll" x="224.586912883306" y="211.812767125873" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Geometry.IntersectAll@Autodesk.DesignScript.Geometry.Geometry[]">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="be479012-5d8c-44db-9eeb-4a202868c05a" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="RIE.IntersectionsFromListOfLines" x="-172.933516655243" y="-18.9571616791039" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <ID value="42e2c8c4-1dba-4a24-aaae-5f5a52f94a1f" />
      <Name value="RIE.IntersectionsFromListOfLines" />
      <Description value="Outputs points on which lines in a list intersect" />
      <Inputs>
        <Input value="Lines" />
      </Inputs>
      <Outputs>
        <Output value="Points" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <PythonNodeModels.PythonNode guid="05da3d01-5287-405e-92c3-9c0cc00d7ee3" type="PythonNodeModels.PythonNode" nickname="Python Script" x="-56.5532563444589" y="407.334929985231" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference("ProtoGeometry")
from Autodesk.DesignScript.Geometry import *
clr.AddReference('DSCoreNodes') 
import DSCore
from DSCore import *


import sys
pyt_path = r'C:\Program Files (x86)\IronPython 2.7\Lib'
sys.path.append(pyt_path)
import os
#The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN
OUT = []
pershape = []

def line_intersects(p1sp,p1ep,p2sp,p2ep):
	xdiff = (p1sp.X - p1ep.X, p2sp.X - p2ep.X)
	ydiff = (p1sp.Y - p1ep.Y, p2sp.Y - p2ep.Y)
	
	def det(a1,a2,b1,b2):
		return a1 * b2 - a2 * b1
	
	div = det(xdiff[0],xdiff[1],ydiff[0],ydiff[1])
	if div &lt;&gt; 0:
		d = (det(p1sp.X,p1sp.Y,p1ep.X,p1ep.Y), det(p2sp.X,p2sp.Y,p2ep.X,p2ep.Y))
		x = det(d[0],d[1], xdiff[0],xdiff[1]) / div
		y = det(d[0],d[1], ydiff[0],ydiff[1]) / div
		if x &gt; p1sp.X and x &lt; p1ep.X and y &gt; p2sp.Y and y &lt; p2ep.Y:
			return Point.ByCoordinates(x,y)
for f in range(0, IN[0].Count):			
	for l1 in IN[0][f]:
		p1sp = l1.StartPoint 
		p1ep = l1.EndPoint
		data = []
		for l2 in IN[0][f]:
			if l1 &lt;&gt; l2:
				p2sp = l2.StartPoint
				p2ep = l2.EndPoint
				if  p1sp.X &lt; p2sp.X and p1ep.X &gt; p2ep.X  or p1sp.Y &gt; p2sp.Y and p1ep.Y &lt; p2ep.Y:
					if not (line_intersects(p1sp,p1ep,p2sp,p2ep) is None):
						data.append(line_intersects(p1sp,p1ep,p2sp,p2ep))
		if data.Count &gt; 0:
			pershape.append(data)
	if pershape.Count &gt; 0:
		OUT.append(pershape)
		pershape = []
	else:
		OUT.append('No intersections found')
		pershape = []</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="03e3d315-04c1-453c-810d-25e072178de7" start_index="0" end="d24f65ee-e735-4cc2-aad8-8fb5b00a9c83" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="03e3d315-04c1-453c-810d-25e072178de7" start_index="0" end="05da3d01-5287-405e-92c3-9c0cc00d7ee3" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>