<Workspace Version="1.3.2.2480" X="389.110588452905" Y="195.756901190838" zoom="0.542771801861599" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Nodes.DSModelElementsSelection guid="03e3d315-04c1-453c-810d-25e072178de7" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="-596.79064936962" y="-15.943399458661" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <instance id="2904eef8-0955-4a07-81b4-9018fe744f99-001634c2" />
      <instance id="2904eef8-0955-4a07-81b4-9018fe744f99-001634eb" />
      <instance id="2904eef8-0955-4a07-81b4-9018fe744f99-00163526" />
      <instance id="2904eef8-0955-4a07-81b4-9018fe744f99-00163553" />
      <instance id="2804ef66-651c-47a2-ba6a-6815c52f1b0d-00163d1b" />
      <instance id="2804ef66-651c-47a2-ba6a-6815c52f1b0d-00163d1c" />
    </Dynamo.Nodes.DSModelElementsSelection>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="4a377d9e-c3d1-4cd5-921a-abca44d5c420" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="DetailCurve.Curve" x="-281.551159527501" y="27.8443530490297" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.DetailCurve.Curve">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="9f84fad3-e0d4-4ecc-84dc-50fc481dea9a" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="436.912702772406" y="-103.804737856624" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Flatten@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="fc453161-beb6-4669-9cb0-0db5056425b1" type="PythonNodeModels.PythonNode" nickname="Python Script" x="338.484358340003" y="8.51023291400435" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference("ProtoGeometry")
from Autodesk.DesignScript.Geometry import *
clr.AddReference('DSCoreNodes') 
import DSCore
from DSCore import *


#The inputs to this node will be stored as a list in the IN variables.
if isinstance(IN[0], list):
    lines = UnwrapElement(IN[0])
else:
    lines = [UnwrapElement(IN[0])]

OUT = []
pershape = []

def line_intersects(p1sp,p1ep,p2sp,p2ep):
	xdiff = (p1sp.X - p1ep.X, p2sp.X - p2ep.X)
	ydiff = (p1sp.Y - p1ep.Y, p2sp.Y - p2ep.Y)
	
	def det(a1,a2,b1,b2):
		return a1 * b2 - a2 * b1
	
	div = det(xdiff[0],xdiff[1],ydiff[0],ydiff[1])
	if div &lt;&gt; 0:
		d = (det(p1sp.X,p1sp.Y,p1ep.X,p1ep.Y), det(p2sp.X,p2sp.Y,p2ep.X,p2ep.Y))
		x = det(d[0],d[1], xdiff[0],xdiff[1]) / div
		y = det(d[0],d[1], ydiff[0],ydiff[1]) / div
		if x &gt; p1sp.X and x &lt; p1ep.X and y &gt; p2sp.Y and y &lt; p2ep.Y:
			return Point.ByCoordinates(x,y)
for f in range(0, len(lines)):			
	for l1 in lines:
		p1sp = l1.StartPoint 
		p1ep = l1.EndPoint
		data = []
		for l2 in lines:
			if l1 != l2:
				p2sp = l2.StartPoint
				p2ep = l2.EndPoint
				if  p1sp.X &lt; p2sp.X and p1ep.X &gt; p2ep.X  or p1sp.Y &gt; p2sp.Y and p1ep.Y &lt; p2ep.Y:
					if not (line_intersects(p1sp,p1ep,p2sp,p2ep) is None):
						data.append(line_intersects(p1sp,p1ep,p2sp,p2ep))
		if len(data) &gt; 0:
			pershape.append(data)
	if len(pershape) &gt; 0:
		OUT.append(pershape)
		pershape = []
	else:
		OUT.append('No intersections found')
		pershape = []</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="d0b2d7bf-a839-4cd6-8bbe-8bf96b839da6" type="PythonNodeModels.PythonNode" nickname="Python Script" x="553.287915049781" y="224.677979788794" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference("ProtoGeometry")
from Autodesk.DesignScript.Geometry import *
clr.AddReference('DSCoreNodes') 
import DSCore
from DSCore import *


#The inputs to this node will be stored as a list in the IN variables.
if isinstance(IN[0], list):
    lines = UnwrapElement(IN[0])
else:
    lines = [UnwrapElement(IN[0])]
check = 0
OUT = []
pershape = []

def line_intersects(p1sp,p1ep,p2sp,p2ep):
	xdiff = (p1sp.X - p1ep.X, p2sp.X - p2ep.X)
	ydiff = (p1sp.Y - p1ep.Y, p2sp.Y - p2ep.Y)
	
	def det(a1,a2,b1,b2):
		return a1 * b2 - a2 * b1
	
	div = det(xdiff[0],xdiff[1],ydiff[0],ydiff[1])
	if div &lt;&gt; 0:
		d = (det(p1sp.X,p1sp.Y,p1ep.X,p1ep.Y), det(p2sp.X,p2sp.Y,p2ep.X,p2ep.Y))
		x = det(d[0],d[1], xdiff[0],xdiff[1]) / div
		y = det(d[0],d[1], ydiff[0],ydiff[1]) / div
		if x &gt; p1sp.X and x &lt; p1ep.X and y &gt; p2sp.Y and y &lt; p2ep.Y:
			return Point.ByCoordinates(x,y)
for f in range(0,len(lines)):			
	for l1 in lines:
		p1sp = l1.StartPoint 
		p1ep = l1.EndPoint
		data = []
		for l2 in lines:
			if l1 != l2:
				p2sp = l2.StartPoint
				p2ep = l2.EndPoint
				if  p1sp.X &lt; p2sp.X and p1ep.X &gt; p2ep.X  or p1sp.Y &gt; p2sp.Y and p1ep.Y &lt; p2ep.Y:
					if not (line_intersects(p1sp,p1ep,p2sp,p2ep) is None):
						data.append(line_intersects(p1sp,p1ep,p2sp,p2ep))
						check = 5
		if len(data) &gt; 0:
			pershape.append(data)
	if len(pershape) &gt; 0:
		OUT.append(pershape)
		pershape = []
	else:
		#OUT.append('No intersections found')
		OUT = check
		pershape = []</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="43143016-4a44-428f-a731-047775f4a145" type="PythonNodeModels.PythonNode" nickname="Python Script" x="350.054228275514" y="503.948545850169" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference("ProtoGeometry")
from Autodesk.DesignScript.Geometry import *
clr.AddReference('DSCoreNodes') 
import DSCore
from DSCore import *


#The inputs to this node will be stored as a list in the IN variables.
if isinstance(IN[0], list):
    lines = UnwrapElement(IN[0])
else:
    lines = [UnwrapElement(IN[0])]
check = 0
OUT = []
pershape = []

def line_intersects(p1sp,p1ep,p2sp,p2ep):
	xdiff = (p1sp.X - p1ep.X, p2sp.X - p2ep.X)
	ydiff = (p1sp.Y - p1ep.Y, p2sp.Y - p2ep.Y)
	
	def det(a1,a2,b1,b2):
		return a1 * b2 - a2 * b1
	
	div = det(xdiff[0],xdiff[1],ydiff[0],ydiff[1])
	if div != 0:
		d = (det(p1sp.X,p1sp.Y,p1ep.X,p1ep.Y), det(p2sp.X,p2sp.Y,p2ep.X,p2ep.Y))
		x = det(d[0],d[1], xdiff[0],xdiff[1]) / div
		y = det(d[0],d[1], ydiff[0],ydiff[1]) / div
		if x &gt; p1sp.X and x &lt; p1ep.X and y &gt; p2sp.Y and y &lt; p2ep.Y:
			return Point.ByCoordinates(x,y)
			
f = 0			
while f &lt; len(lines):			
	for l1 in lines:
		p1sp = l1.StartPoint 
		p1ep = l1.EndPoint
		data = []
		for l2 in lines:
			if l1 != l2:
				p2sp = l2.StartPoint
				p2ep = l2.EndPoint
				if  p1sp.X &lt; p2sp.X and p1ep.X &gt; p2ep.X  or p1sp.Y &gt; p2sp.Y and p1ep.Y &lt; p2ep.Y:
					if not (line_intersects(p1sp,p1ep,p2sp,p2ep) is None):
						data.append(line_intersects(p1sp,p1ep,p2sp,p2ep))
						check = 5
		if len(data) &gt; 0:
			pershape.append(data)
	f = f+1
	if len(pershape) &gt; 0:
		OUT.append(pershape)
		pershape = []
	else:
		#OUT.append('No intersections found')
		#OUT = len(lines)
		OUT = check
		pershape = []</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="b8e99b4d-34eb-4b12-9052-3a22a573dac5" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.GetItemAtIndex" x="22.3014856173177" y="513.813310479264" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.GetItemAtIndex@var[]..[],int">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="a2598cd9-29ca-46cb-99c9-b26d678875d3" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="-250" y="350" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="0;" ShouldFocus="false" />
    <PythonNodeModels.PythonNode guid="4bd9aba7-120b-45a2-9b82-4c7b6e9e74d1" type="PythonNodeModels.PythonNode" nickname="Python Script" x="-38.343451415629" y="-161.039701565384" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference("ProtoGeometry")
from Autodesk.DesignScript.Geometry import *
clr.AddReference('DSCoreNodes') 
import DSCore
from DSCore import *


from shapely.geometry import LineString

line1 = LineString([(0,0), (1,0), (1,1)])
line2 = LineString([(0,1), (1,1)])

point = (line1.intersection(line2))
#Assign your output to the OUT variable.
OUT = point</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="d9b8568d-95cb-4a1c-9b4e-ba6f4bbf6b7f" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Curve.IntersectAll" x="17.5151261571626" y="43.1946485311962" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="C:\Users\dcleary\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\bimorphNodes\bin\BimorphNodes.dll" function="Curve.IntersectAll@Autodesk.DesignScript.Geometry.Curve[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="03e3d315-04c1-453c-810d-25e072178de7" start_index="0" end="4a377d9e-c3d1-4cd5-921a-abca44d5c420" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4a377d9e-c3d1-4cd5-921a-abca44d5c420" start_index="0" end="9f84fad3-e0d4-4ecc-84dc-50fc481dea9a" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4a377d9e-c3d1-4cd5-921a-abca44d5c420" start_index="0" end="b8e99b4d-34eb-4b12-9052-3a22a573dac5" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4a377d9e-c3d1-4cd5-921a-abca44d5c420" start_index="0" end="d9b8568d-95cb-4a1c-9b4e-ba6f4bbf6b7f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9f84fad3-e0d4-4ecc-84dc-50fc481dea9a" start_index="0" end="43143016-4a44-428f-a731-047775f4a145" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b8e99b4d-34eb-4b12-9052-3a22a573dac5" start_index="0" end="fc453161-beb6-4669-9cb0-0db5056425b1" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a2598cd9-29ca-46cb-99c9-b26d678875d3" start_index="0" end="b8e99b4d-34eb-4b12-9052-3a22a573dac5" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="8e3f2010-8756-4c9a-b06a-6269f18e5cda" annotationText="GET INTERSECTION POINTS" left="328.484358340003" top="-109.489767085996" width="207.703333333333" height="211" fontSize="30" InitialTop="8.51023291400435" InitialHeight="123" TextblockHeight="108" backgrouund="#FFC1D676">
      <Models ModelGuid="fc453161-beb6-4669-9cb0-0db5056425b1" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="0221a116-4502-4a50-a22f-90613e13bc83" annotationText="current" left="340.054228275514" top="457.948545850169" width="144" height="139" fontSize="30" InitialTop="503.948545850169" InitialHeight="123" TextblockHeight="36" backgrouund="#FFC1D676">
      <Models ModelGuid="43143016-4a44-428f-a731-047775f4a145" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="0.564064465117398" eyeY="4.81163747676561" eyeZ="-0.36519571823086" lookX="0.00177320330306496" lookY="-1.26979456051807" lookZ="-0.147369750887252" upX="0.0113759795203805" upY="0.325568169355392" upZ="-0.945450127124786" />
  </Cameras>
</Workspace>