<Workspace Version="1.3.1.1736" X="-243.499737913967" Y="-122.345133117351" zoom="1.33823125" ScaleFactor="1" Name="Floor.Area" Description="This node return floor area. " ID="ca67720f-9719-431b-9d33-fddf2a96285b" Category="archilab.Revit.Floors">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="7b5c0d9e-47d9-4bc7-a75e-92a803368ae4" type="PythonNodeModels.PythonNode" nickname="Python Script" x="568.130048590775" y="232.982400117108" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script># Copyright(c) 2016, Konrad K Sobon
# @arch_laboratory, http://archi-lab.net

# Import RevitAPI
import clr
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

#The inputs to this node will be stored as a list in the IN variable.
dataEnteringNode = IN

def Unwrap(item):
	return UnwrapElement(item)

def ProcessList(_func, _list):
    return map( lambda x: process_list(_func, x) if type(x)==list else _func(x), _list )

def FloorArea(item):
	return item.get_Parameter(BuiltInParameter.HOST_AREA_COMPUTED).AsValueString()

if isinstance(IN[0], list):
	elements = ProcessList(Unwrap, IN[0])
else:
	elements = [Unwrap(IN[0])]

#Assign your output to the OUT variable
OUT = ProcessList(FloorArea, elements)</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="bee368f6-9411-4503-a73c-d47d2b91d8f2" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="440.008459858713" y="230.910614128924" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Floor" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="90691b13-0070-4a37-9c73-ff3e004d59a7" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="734.426932002448" y="232.903294143433" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Area" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="7b5c0d9e-47d9-4bc7-a75e-92a803368ae4" start_index="0" end="90691b13-0070-4a37-9c73-ff3e004d59a7" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="bee368f6-9411-4503-a73c-d47d2b91d8f2" start_index="0" end="7b5c0d9e-47d9-4bc7-a75e-92a803368ae4" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
</Workspace>