<Workspace Version="1.3.1.1736" X="-183.790543040273" Y="-329.725440437525" zoom="1.78359936238281" ScaleFactor="1" Name="FloorPlan.ByRoom" Description="This node takes input of a Room and creates a Floor Plan View with Crop Box set around that room. " ID="aa6de0ed-082c-4ecc-a410-863746b0ee55" Category="archilab.Revit.View">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="c48efa1a-34e1-4d9b-bbd5-7085d8702e23" type="PythonNodeModels.PythonNode" nickname="Python Script" x="524" y="267" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="4">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <PortInfo index="3" default="False" />
      <Script># Copyright(c) 2015, Konrad K Sobon
# @arch_laboratory, http://archi-lab.net

import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import Element wrapper extension methods
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

# Import geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

import System
from System import Array
from System.Collections.Generic import *

import sys
pyt_path = r'C:\Program Files (x86)\IronPython 2.7\Lib'
sys.path.append(pyt_path)

#The inputs to this node will be stored as a list in the IN variable.
dataEnteringNode = IN

if isinstance(IN[0], list):
	rooms = UnwrapElement(IN[0])
else:
	rooms = [UnwrapElement(IN[0])]
namePrefix = IN[1]
bboxOffset = IN[2]
runMe = IN[3]

def OffsetBBox(bbox, offset):
	bboxMinX = bbox.Min.X - offset
	bboxMinY = bbox.Min.Y - offset
	bboxMinZ = bbox.Min.Z - offset
	bboxMaxX = bbox.Max.X + offset
	bboxMaxY = bbox.Max.Y + offset
	bboxMaxZ = bbox.Max.Z + offset
	newBbox = BoundingBoxXYZ()
	newBbox.Min = XYZ(bboxMinX, bboxMinY, bboxMinZ)
	newBbox.Max = XYZ(bboxMaxX, bboxMaxY, bboxMaxZ)
	return newBbox

try:
	errorReport = None
	if runMe:
		viewTypes = FilteredElementCollector(doc).OfClass(ViewFamilyType)
		for i in viewTypes:
			if i.ViewFamily == ViewFamily.FloorPlan:
				viewTypeId = i.Id
				break
			else:
				continue
		
		existingPlans = FilteredElementCollector(doc).OfClass(View).ToElements()
		
		existingPlanNames, existingPlanElements = [], []
		for i in existingPlans:
			if not i.IsTemplate:
				if i.ViewType == ViewType.FloorPlan:
					existingPlanNames.append(i.ToDSType(True).Name)
					existingPlanElements.append(i)
					
		# Start Transaction
		TransactionManager.Instance.EnsureInTransaction(doc)
		
		floorPlans = []
		for i in rooms:
			levelId = i.LevelId
			bbox = i.BoundingBox[doc.ActiveView]
			newBbox = OffsetBBox(bbox, bboxOffset)
			viewName = namePrefix + "-" + i.get_Parameter(BuiltInParameter.ROOM_NUMBER).AsString() + "-" + i.get_Parameter(BuiltInParameter.ROOM_NAME).AsString()
			if viewName in existingPlanNames:
				view = existingPlanElements[existingPlanNames.index(viewName)]
				view.CropBox = newBbox
				view.CropBoxActive = True
				view.CropBoxVisible = False
				floorPlans.append(view)
			else:
				newView = ViewPlan.Create(doc, viewTypeId, levelId)
				newView.ViewName = viewName
				newView.CropBox = newBbox
				newView.CropBoxActive = True
				view.CropBoxVisible = False
				floorPlans.append(newView)
	
		# End Transaction
		TransactionManager.Instance.TransactionTaskDone()
	else:
		errorReport = "Run Me set to False"
except:
	# if error accurs anywhere in the process catch it
	import traceback
	errorReport = traceback.format_exc()

#Assign your output to the OUT variable
if errorReport == None:
	OUT = floorPlans
else:
	OUT = errorReport
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="50652642-37b0-4d19-860a-ef87ce337c8a" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="263.955321452525" y="266.161476870743" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Room" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="5bffba89-b752-4dea-b07d-5f5c4a8e770e" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="262.650088449283" y="324.84729469242" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Prefix:string=&quot;RDS&quot;" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="407c2260-2332-41d4-921e-eec3a09d137e" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="259.754815842057" y="383.625064989317" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Offset:int=4" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="130b9c3d-00bc-45a1-b378-bd816c1300f2" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="261.34485544604" y="440.72084320701" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="RunIt:bool=false" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="1acb8419-aa65-4ce4-b3bb-5fea84c406e6" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="696.787949834182" y="266.161476870743" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="FloorPlanView" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="c48efa1a-34e1-4d9b-bbd5-7085d8702e23" start_index="0" end="1acb8419-aa65-4ce4-b3bb-5fea84c406e6" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="50652642-37b0-4d19-860a-ef87ce337c8a" start_index="0" end="c48efa1a-34e1-4d9b-bbd5-7085d8702e23" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5bffba89-b752-4dea-b07d-5f5c4a8e770e" start_index="0" end="c48efa1a-34e1-4d9b-bbd5-7085d8702e23" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="407c2260-2332-41d4-921e-eec3a09d137e" start_index="0" end="c48efa1a-34e1-4d9b-bbd5-7085d8702e23" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="130b9c3d-00bc-45a1-b378-bd816c1300f2" start_index="0" end="c48efa1a-34e1-4d9b-bbd5-7085d8702e23" end_index="3" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
</Workspace>