<Workspace Version="1.3.2.2480" X="-280.768458945709" Y="448.691808186103" zoom="4" ScaleFactor="1" Name="RIE.ElementsByView" Description="Selects elements that are visible in input view. Forked from Marc" ID="2c1b6fb5-a090-44e3-b89e-8dd92cbeca0b" Category="RIE.Elements">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="1d99d5d1-6cdd-4506-8a9b-edb53d29d610" type="PythonNodeModels.PythonNode" nickname="Elements in views" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Made by Marc Tavenier @marctavenier
import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager

doc = DocumentManager.Instance.CurrentDBDocument

def tolist(obj):
	if isinstance(obj, list):
		return UnwrapElement(obj)
	else:
		return [UnwrapElement(obj)]

views = tolist(IN[0])
elems = []

for view in views:
	filter = FilteredElementCollector(doc, view.Id)
	elems.append(filter.ToElements())

if len(elems) == 1:
	OUT = elems[0]
else:
	OUT = elems</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="69ec9d5a-7784-4d25-b043-a3e996429c47" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="177" y="-2" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Views" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="6272b66c-4a32-4212-94eb-312b31523646" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="377" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Elements" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="1d99d5d1-6cdd-4506-8a9b-edb53d29d610" start_index="0" end="6272b66c-4a32-4212-94eb-312b31523646" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="69ec9d5a-7784-4d25-b043-a3e996429c47" start_index="0" end="1d99d5d1-6cdd-4506-8a9b-edb53d29d610" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>