<Workspace Version="1.3.2.2480" X="59.116506915114" Y="322.465654062794" zoom="1.545620359375" ScaleFactor="1" Name="RIE.CreateSheets" Description="Create sheets with inputs; Sheet Name, Number and Titleblock" ID="83eb1625-6917-428b-b682-8d0e69c3a2da" Category="RIE.Views">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="2baafcf7-fc44-4da4-8b80-dc19ac72652f" type="PythonNodeModels.PythonNode" nickname="Name Number Titleblock" x="248.706021185688" y="0.646989407155843" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>#Make Sheets
import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

def tolist(obj):
	if isinstance(obj, list):
		return UnwrapElement(obj)
	else:
		return [UnwrapElement(obj)]


doc = DocumentManager.Instance.CurrentDBDocument
sheetnames = tolist(IN[0])
sheetnumbers = tolist(IN[1])
titleblock = tolist(IN[2]) #unwrapped titleblock
sheetlist = list()



TransactionManager.Instance.EnsureInTransaction(doc) # you need an active transaction as you will create elements
 

for number in range(len(sheetnumbers)):
	if len(titleblock) &gt; 1:
		newsheet = ViewSheet.Create(doc,titleblock[number].Id) # create a new sheet where titleblock.Id is the id of the titleblock
	else:
		newsheet = ViewSheet.Create(doc,titleblock[0].Id) # create a new sheet where titleblock.Id is the id of the titleblock
	newsheet.Name = sheetnames[number]
	newsheet.SheetNumber = sheetnumbers[number]
	sheetlist.append(newsheet.ToDSType(False))

	
TransactionManager.Instance.TransactionTaskDone()
OUT = sheetlist</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="b5727d1c-1243-4e3c-a91e-3445bebaf8aa" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="SheetName" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="85a36b1a-73d5-4fec-ba19-a017a3e7ed75" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="150" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="SheetNumber" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="893d2836-6279-4647-bb74-a43acc9a7b9e" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="300" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="TitleBlock" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="93cb430c-51b8-4d66-85c1-9ec7bfa00403" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="492" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Sheets" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="2baafcf7-fc44-4da4-8b80-dc19ac72652f" start_index="0" end="93cb430c-51b8-4d66-85c1-9ec7bfa00403" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b5727d1c-1243-4e3c-a91e-3445bebaf8aa" start_index="0" end="2baafcf7-fc44-4da4-8b80-dc19ac72652f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="85a36b1a-73d5-4fec-ba19-a017a3e7ed75" start_index="0" end="2baafcf7-fc44-4da4-8b80-dc19ac72652f" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="893d2836-6279-4647-bb74-a43acc9a7b9e" start_index="0" end="2baafcf7-fc44-4da4-8b80-dc19ac72652f" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>