<Workspace Version="1.3.2.2480" X="-196.17446902213" Y="221.88214333636" zoom="1.9242700729927" ScaleFactor="1" Name="RIE.GraphicOverrideElementsInViews" Description="Overrides elements in views with input color for both lines and fill. Requires you to have a fill pattern named &quot;Solid fill&quot;" ID="03527136-6aa7-457b-a9ea-64dc3448539f" Category="RIE.Views">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="77600b6f-33ed-42bb-8dd0-eb9177318065" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Color.Green" x="292.537798979732" y="280.545837317852" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.Color.Green">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="bb0701aa-9bbd-43bc-ac82-6dd4bc3f91c8" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Color.Red" x="292.537798979732" y="172.545837317852" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.Color.Red">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="29c61bc0-c8f0-4426-bb18-a8f05a829ecb" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Color.Blue" x="292.537798979732" y="388.545837317852" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.Color.Blue">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="b8a5623e-a9fc-4377-a54c-a5189c1104e0" type="PythonNodeModels.PythonNode" nickname="Convert Dyn color to Rev color" x="518.537798979732" y="252.545837317852" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

color = Color(IN[0],IN[1],IN[2])

OUT = color</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="476f09d8-5068-45c5-8b1c-1d60f7eeb790" type="PythonNodeModels.PythonNode" nickname="Override graphics of elements in views" x="793.537798979732" y="93.5458373178518" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

# Import DocumentManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

def tolist(obj):
	if isinstance(obj, list):
		return UnwrapElement(obj)
	else:
		return [UnwrapElement(obj)]

elements = tolist(IN[0])
views = tolist(IN[1])
color = IN[2]
target = FillPatternTarget.Model
fillname = 'Solid fill'
drafting = "x"

try:
	errorReport = None
	if drafting:
		fillPatTarget = FillPatternTarget.Drafting
	else:
		fillPatTarget = FillPatternTarget.Model
	fillPat = FillPatternElement.GetFillPatternElementByName(doc, fillPatTarget, fillname)
except:
	drafting = "y"
	
opt = OverrideGraphicSettings()
opt.SetProjectionLineColor(color)
opt.SetProjectionFillColor(color)
opt.SetProjectionFillPatternId(fillPat.Id)

TransactionManager.Instance.EnsureInTransaction(doc)
for view in views:
	for element in elements:
		view.SetElementOverrides(element.Id, opt)
TransactionManager.Instance.TransactionTaskDone()

OUT = elements</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="bb82aa24-b8b8-43c9-b14a-9db902e0f366" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="117.537798979732" y="34.5458373178518" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="elements" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="d9e53732-3a9c-4268-98bf-9d25d38df2d4" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="117.537798979732" y="117.545837317852" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="views" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="1cef9667-a56d-43f7-86d5-cdb417c93e7f" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="118.537798979732" y="280.545837317852" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="color" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="534f8e78-8a5c-4790-9b15-22e87f7308c8" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1109.53779897973" y="94.5458373178518" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="elements;" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="77600b6f-33ed-42bb-8dd0-eb9177318065" start_index="0" end="b8a5623e-a9fc-4377-a54c-a5189c1104e0" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="bb0701aa-9bbd-43bc-ac82-6dd4bc3f91c8" start_index="0" end="b8a5623e-a9fc-4377-a54c-a5189c1104e0" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="29c61bc0-c8f0-4426-bb18-a8f05a829ecb" start_index="0" end="b8a5623e-a9fc-4377-a54c-a5189c1104e0" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b8a5623e-a9fc-4377-a54c-a5189c1104e0" start_index="0" end="476f09d8-5068-45c5-8b1c-1d60f7eeb790" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="476f09d8-5068-45c5-8b1c-1d60f7eeb790" start_index="0" end="534f8e78-8a5c-4790-9b15-22e87f7308c8" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="bb82aa24-b8b8-43c9-b14a-9db902e0f366" start_index="0" end="476f09d8-5068-45c5-8b1c-1d60f7eeb790" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d9e53732-3a9c-4268-98bf-9d25d38df2d4" start_index="0" end="476f09d8-5068-45c5-8b1c-1d60f7eeb790" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1cef9667-a56d-43f7-86d5-cdb417c93e7f" start_index="0" end="bb0701aa-9bbd-43bc-ac82-6dd4bc3f91c8" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1cef9667-a56d-43f7-86d5-cdb417c93e7f" start_index="0" end="77600b6f-33ed-42bb-8dd0-eb9177318065" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1cef9667-a56d-43f7-86d5-cdb417c93e7f" start_index="0" end="29c61bc0-c8f0-4426-bb18-a8f05a829ecb" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="18706.2283142103" eyeY="77390.041523907" eyeZ="-42690.9321461394" lookX="8205.03291625843" lookY="-72780.041523907" lookZ="20503.0122242644" upX="-0.370394768958617" upY="-0.0784590957278451" upZ="-0.925554906759001" />
  </Cameras>
</Workspace>