<Workspace Version="1.3.2.2480" X="376" Y="324" zoom="1" ScaleFactor="1" Name="RIE.SetRevitSelection" Description="Input elements to select in Revit model" ID="bfccc532-4371-4c15-bc58-98374747ea02" Category="RIE.Elements">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="94301b29-4c54-49c9-9bfd-8fefffc0ceb7" type="PythonNodeModels.PythonNode" nickname="Python Script" x="210.5" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script># Copyright(c) 2017, Dimitar Venkov
# @5devene, dimitar.ven@gmail.com
# www.badmonkeys.net

import clr
import System

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference('RevitServices')
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference('System')
from System.Collections.Generic import List

clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import *

def tolist(obj1):
	if hasattr(obj1,"__iter__"): return obj1
	else: return [obj1]

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application
uidoc=DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument

eleId=[]

for i in UnwrapElement(IN[0]):
	eleId.append(i.Id)
	
elemIds = List[ElementId](eleId)

try:
	uidoc.Selection.SetElementIds(elemIds)
	OUT = IN[0]
except:
	OUT = "Failed to set selection"</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="ba95a0c9-3010-4402-b9ee-a16a2e8b95d0" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="14.5" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Elements" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="f4db1158-1b5d-4d9f-a728-3c3752b8e9f0" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="434.5" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Selection" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="94301b29-4c54-49c9-9bfd-8fefffc0ceb7" start_index="0" end="f4db1158-1b5d-4d9f-a728-3c3752b8e9f0" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ba95a0c9-3010-4402-b9ee-a16a2e8b95d0" start_index="0" end="94301b29-4c54-49c9-9bfd-8fefffc0ceb7" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>