<Workspace Version="1.3.1.1736" X="121.316633267348" Y="260.442287248347" zoom="0.802145231256963" ScaleFactor="1" Name="All Families Of Category" Description="Gets all famiies of a given category in the model  (does *not *work for system families)" ID="2a75c2fa-c410-434d-87af-f9d59ee44c4b" Category="Clockwork.Revit.Selection.ByCollector">
  <NamespaceResolutionMap>
    <ClassMap partialName="List" resolvedName="DSCore.List" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="Category" resolvedName="Revit.Elements.Category" assemblyName="RevitNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="7051506d-0987-4906-8b5b-68f643bb6941" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="46.9720494834005" y="-16.6745209062134" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="category : Category" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="27647f3a-c7d7-48fa-bf00-8adabac27375" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="788.972049483401" y="40.3254790937866" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="families" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="86e66cba-645b-41a1-95de-0dd4a0c548c9" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="46.9720494834005" y="66.3254790937866" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="toggle : bool = true" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="5445afc6-1f3c-4d71-8248-25ab27252a13" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="46.9720494834005" y="149.325479093787" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="// Use only if you want to query a linked model&#xD;&#xA;docOrRevitLinkInstance : var = null" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <PythonNodeModels.PythonNode guid="5eb9f97a-6719-4ea0-b86e-f6bb1326c880" type="PythonNodeModels.PythonNode" nickname="Python Script" x="564.972049483401" y="40.3254790937866" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>import System
import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

def ElementTypesByCategory(cat, doc):
	collector = FilteredElementCollector(doc).OfClass(Family)
	return [x for x in collector.ToElements() if x.FamilyCategoryId.IntegerValue == cat.Id]

inputdoc = UnwrapElement(IN[2])
if not inputdoc: doc = DocumentManager.Instance.CurrentDBDocument
elif inputdoc.GetType().ToString() == "Autodesk.Revit.DB.RevitLinkInstance": doc = inputdoc.GetLinkDocument()
elif inputdoc.GetType().ToString() == "Autodesk.Revit.DB.Document": doc = inputdoc
else: doc = DocumentManager.Instance.CurrentDBDocument

if isinstance(IN[0], list): OUT = [ElementTypesByCategory(x, doc) for x in IN[0]]
else: OUT = ElementTypesByCategory(IN[0], doc)</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="7051506d-0987-4906-8b5b-68f643bb6941" start_index="0" end="5eb9f97a-6719-4ea0-b86e-f6bb1326c880" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="86e66cba-645b-41a1-95de-0dd4a0c548c9" start_index="0" end="5eb9f97a-6719-4ea0-b86e-f6bb1326c880" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5445afc6-1f3c-4d71-8248-25ab27252a13" start_index="0" end="5eb9f97a-6719-4ea0-b86e-f6bb1326c880" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5eb9f97a-6719-4ea0-b86e-f6bb1326c880" start_index="0" end="27647f3a-c7d7-48fa-bf00-8adabac27375" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>