<Workspace Version="1.3.1.1736" X="115" Y="237" zoom="1" ScaleFactor="1" Name="CurtainPanel.HostPanel" Description="Retrieves the host panel of a given curtain panel. This is typcially needed when wanting to access wall elements used as curtain panels. If no host panel is found, the node will return the input panel instead." ID="339cd350-3d18-462d-8417-32e3ac42fc28" Category="Clockwork.Revit.Elements.CurtainPanel.Query">
  <NamespaceResolutionMap>
    <ClassMap partialName="CurtainPanel" resolvedName="Revit.Elements.CurtainPanel" assemblyName="RevitNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="43b82910-2637-4de6-a425-e535efc29a37" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="200.691302478035" y="-59" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="curtainPanel" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="bb04f9ec-a5fc-49e3-8429-de049bda8ce3" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="653.691302478035" y="-59" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="hostPanel" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="0ef11c39-59d8-4b17-80ce-6817d210a323" type="PythonNodeModels.PythonNode" nickname="Python Script" x="429.691302478035" y="-59" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

def GetHostPanel(item):
	if hasattr(item, "FindHostPanel"):
		hpId = item.FindHostPanel()
		if hpId.IntegerValue &gt; 0: return item.Document.GetElement(hpId).ToDSType(True)
		else: return item
	else: return item

items = UnwrapElement(IN[0])

if isinstance(IN[0], list): OUT = [GetHostPanel(x) for x in items]
else: OUT = GetHostPanel(items)</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="43b82910-2637-4de6-a425-e535efc29a37" start_index="0" end="0ef11c39-59d8-4b17-80ce-6817d210a323" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0ef11c39-59d8-4b17-80ce-6817d210a323" start_index="0" end="bb04f9ec-a5fc-49e3-8429-de049bda8ce3" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>