<Workspace Version="1.3.1.1736" X="0" Y="0" zoom="1" ScaleFactor="1" Name="CurtainPanel.IsPhantomPanel" Description="Checks whether a given curtain panel is not an actual model element. (These types of objects get generated when curtain grid segments are deleted or in other words when multiple cells of the curtain grid are merged into one panel)" ID="49d6f667-4043-4248-bdbf-c5ee06672703" Category="Clockwork.Revit.Elements.CurtainPanel.Query">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="6a4bc0c3-cd43-4560-889e-c92d3e3775e1" type="PythonNodeModels.PythonNode" nickname="Python Script" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

def IsPhantomPanel(item):
	try: 
		if item.get_Parameter(BuiltInParameter.HOST_AREA_COMPUTED).HasValue: return False
		else: return True
	except: return False

items = UnwrapElement(IN[0])

if isinstance(IN[0], list): OUT = [IsPhantomPanel(x) for x in items]
else: OUT = IsPhantomPanel(items)</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="bd053498-6d8a-4db1-9fd8-17096d5f9a2c" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="curtainPanel" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="10a43722-8e2a-4f4d-a59f-cb1460085eaf" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="449" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="bool" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="6a4bc0c3-cd43-4560-889e-c92d3e3775e1" start_index="0" end="10a43722-8e2a-4f4d-a59f-cb1460085eaf" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="bd053498-6d8a-4db1-9fd8-17096d5f9a2c" start_index="0" end="6a4bc0c3-cd43-4560-889e-c92d3e3775e1" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>