<Workspace Version="1.3.0.875" X="87.7872012981285" Y="440.757094766027" zoom="1.17691128698145" ScaleFactor="1" Name="Curve.ClosedLoopThroughPoints" Description="Creates a *closed* loop of curves based on a given list of points" ID="576880d2-5f2c-4e34-9183-359361aaa077" Category="Clockwork.Geometry.Curve.Create">
  <NamespaceResolutionMap>
    <ClassMap partialName="PolyCurve" resolvedName="Autodesk.DesignScript.Geometry.PolyCurve" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Autodesk.Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="ce17390f-1522-4ac4-b6e6-9152d83e7a97" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-101.791682947826" y="48.5942986496884" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="points : Autodesk.Point[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="0199b100-662e-48cb-ab5c-f6a4ed55d5cf" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="952.208317052174" y="77.5942986496884" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Curves" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="5392ff84-69ed-4330-a05d-385131ee9cd8" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="PolyCurve.ByPoints" x="234.208317052174" y="77.5942986496884" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.PolyCurve.ByPoints@Autodesk.DesignScript.Geometry.Point[],bool">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <CoreNodeModels.Input.BoolSelector guid="d54deaab-e6eb-4ef1-858b-8790c179262a" type="CoreNodeModels.Input.BoolSelector" nickname="Boolean" x="-101.791682947826" y="132.594298649688" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.Boolean>True</System.Boolean>
    </CoreNodeModels.Input.BoolSelector>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="638b4830-596f-4c5b-ad11-53164281e348" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="PolyCurve.Curves" x="628.208317052174" y="77.5942986496884" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.PolyCurve.Curves">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="ce17390f-1522-4ac4-b6e6-9152d83e7a97" start_index="0" end="5392ff84-69ed-4330-a05d-385131ee9cd8" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5392ff84-69ed-4330-a05d-385131ee9cd8" start_index="0" end="638b4830-596f-4c5b-ad11-53164281e348" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d54deaab-e6eb-4ef1-858b-8790c179262a" start_index="0" end="5392ff84-69ed-4330-a05d-385131ee9cd8" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="638b4830-596f-4c5b-ad11-53164281e348" start_index="0" end="0199b100-662e-48cb-ab5c-f6a4ed55d5cf" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>