<Workspace Version="1.3.1.1736" X="113" Y="247" zoom="1" ScaleFactor="1" Name="DesignOption.DesignOptionSet" Description="Returns the design option set of a given design option" ID="c135da75-96f9-404d-9643-3b3d0b998dc1" Category="Clockwork.Revit.Elements.DesignOption.Query">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="fb993e26-7f3a-497e-b854-118019aae8d3" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="231.351071794381" y="-67.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="designOption" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="b1442ac8-b8bf-4bb0-bba8-d890a991e818" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="684.351071794381" y="-67.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="designOptionSet" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="3ebdfcb3-675c-48d9-82ee-12926bae512b" type="PythonNodeModels.PythonNode" nickname="Python Script" x="460.351071794381" y="-67.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

def GetDesignOptionSet(item):
	try: return item.Document.GetElement(item.get_Parameter(BuiltInParameter.OPTION_SET_ID).AsElementId()).ToDSType(True)
	except: return None

items = UnwrapElement(IN[0])

if isinstance(IN[0], list): OUT = [GetDesignOptionSet(x) for x in items]
else: OUT = GetDesignOptionSet(items)</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="fb993e26-7f3a-497e-b854-118019aae8d3" start_index="0" end="3ebdfcb3-675c-48d9-82ee-12926bae512b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3ebdfcb3-675c-48d9-82ee-12926bae512b" start_index="0" end="b1442ac8-b8bf-4bb0-bba8-d890a991e818" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>