<Workspace Version="1.3.1.1736" X="444" Y="327" zoom="1" ScaleFactor="1" Name="DesignOption.IsPrimary" Description="Determines whether a given design option is the primary option in its set" ID="b5fa6e00-d029-473c-a9cd-76c7279cbc79" Category="Clockwork.Revit.Elements.DesignOption.Query">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="1ff7eedb-99dd-4e29-a568-8d79aab89c09" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="231.807416209728" y="-67" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="designOption" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="d5a7f917-0efd-4b56-a46e-50f87cba49aa" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="684.807416209728" y="-67" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="bool" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="e41c02d3-2c76-4566-b034-72377f195c85" type="PythonNodeModels.PythonNode" nickname="Python Script" x="460.807416209728" y="-67" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
import System
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

def DesignOptionIsPrimary(item):
	if hasattr(item, "IsPrimary"): return item.IsPrimary
	else: return False

items = UnwrapElement(IN[0])

if isinstance(IN[0], list): OUT = [DesignOptionIsPrimary(x) for x in items]
else: OUT = DesignOptionIsPrimary(items)</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="1ff7eedb-99dd-4e29-a568-8d79aab89c09" start_index="0" end="e41c02d3-2c76-4566-b034-72377f195c85" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e41c02d3-2c76-4566-b034-72377f195c85" start_index="0" end="d5a7f917-0efd-4b56-a46e-50f87cba49aa" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>