<Workspace Version="1.3.1.1736" X="285.3204375" Y="351.49804375" zoom="0.70823125" ScaleFactor="1" Name="DirectShape.FromRevitGeometry" Description="Creates a DirectShape from native Revit geometry objects" ID="6a060a4d-58fe-4070-a0ce-44cc24c9802b" Category="Clockwork.Revit.Elements.DirectShape.Create">
  <NamespaceResolutionMap>
    <ClassMap partialName="Element" resolvedName="Revit.Elements.Element" assemblyName="RevitNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="58a0f303-7847-45ad-8c36-2a1e6b6c9507" type="PythonNodeModels.PythonNode" nickname="Python Script" x="637.559840977082" y="-52.7383314065851" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script># This script is based on code from the node
# DirectShape.ByGeometry from package SpringNodes.
# Thanks Dimitar for doing all the hard work for me... ;-)

import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
geometry = UnwrapElement(IN[0])
cat = UnwrapElement(IN[1])
names = IN[2]
counter = 0
elementlist = list()

dsLib = DirectShapeLibrary.GetDirectShapeLibrary(doc)

TransactionManager.Instance.EnsureInTransaction(doc)
for geom in geometry:
	# delete old DS type if the name already exists
	if dsLib.ContainsType(names[counter]):
		old_type = dsLib.FindDefinitionType(names[counter])
		try: doc.Delete(old_type)
		except: pass
	try:
		# create new DS type
		newDStype = DirectShapeType.Create(doc, names[counter], cat.Id)
		newDStype.SetShape(geom)
		dsLib.AddDefinitionType(names[counter], newDStype.Id)
		# create new DS instance
		newDS =  DirectShape.CreateElementInstance(doc, newDStype.Id, cat.Id, names[counter], Transform.Identity, "Dynamo","Clockwork")
		newDS.SetTypeId(newDStype.Id)
		elementlist.append(newDS)
	except: elementlist.append(None)
	counter += 1
TransactionManager.Instance.TransactionTaskDone()

OUT = elementlist</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="c604ae40-1466-47cf-9324-5574ca7f4315" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="393.559840977082" y="-109.738331406585" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="revitGeometry" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="d85bd526-71ed-4eba-9a2f-f8c828395cfc" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="393.559840977082" y="-26.7383314065851" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="category" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="a34cc9c1-6ef2-47d4-b1f6-f7424a169c97" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="393.559840977082" y="56.2616685934149" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="name" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="5341e7e6-7465-4d09-9e2b-082da1593e2d" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="859.559840977082" y="-52.7383314065851" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="directShape" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="58a0f303-7847-45ad-8c36-2a1e6b6c9507" start_index="0" end="5341e7e6-7465-4d09-9e2b-082da1593e2d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c604ae40-1466-47cf-9324-5574ca7f4315" start_index="0" end="58a0f303-7847-45ad-8c36-2a1e6b6c9507" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d85bd526-71ed-4eba-9a2f-f8c828395cfc" start_index="0" end="58a0f303-7847-45ad-8c36-2a1e6b6c9507" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a34cc9c1-6ef2-47d4-b1f6-f7424a169c97" start_index="0" end="58a0f303-7847-45ad-8c36-2a1e6b6c9507" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>