<Workspace Version="1.3.1.1736" X="29.9999999999999" Y="368.047308319739" zoom="1.16802610114193" ScaleFactor="1" Name="Document.Worksets" Description="Returns all Worksets in the current document" ID="90dc6979-b53e-49a6-805d-ecfeba189414" Category="Clockwork.Revit.Document.Query">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="54d637dc-517c-456b-bddd-3ee945668544" type="PythonNodeModels.PythonNode" nickname="Python Script" x="473.236033519552" y="-120.956005586592" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
import Autodesk

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

inputdoc = UnwrapElement(IN[1])
if inputdoc == None:
	doc = DocumentManager.Instance.CurrentDBDocument
elif inputdoc.GetType().ToString() == "Autodesk.Revit.DB.RevitLinkInstance":
	doc = inputdoc.GetLinkDocument()
elif inputdoc.GetType().ToString() == "Autodesk.Revit.DB.Document":
	doc = inputdoc
else: doc = None

collector = FilteredWorksetCollector(doc)
OUT = collector.ToWorksets()</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="eec3102c-a5ff-4977-ab73-a84a4fd6acfb" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="697.236033519552" y="-120.956005586592" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="worksets" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="9fb55589-0cfa-45b8-95e9-6c8f19c9a19d" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-44.7639664804476" y="-149.956005586592" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="toggle : bool = true" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="b3d8f7a9-26bf-47af-97bd-bd44d7b24919" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-44.7639664804476" y="-65.9560055865917" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="// Use only if you want to query a linked model&#xD;&#xA;docOrRevitLinkInstance : var = null" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="54d637dc-517c-456b-bddd-3ee945668544" start_index="0" end="eec3102c-a5ff-4977-ab73-a84a4fd6acfb" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9fb55589-0cfa-45b8-95e9-6c8f19c9a19d" start_index="0" end="54d637dc-517c-456b-bddd-3ee945668544" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b3d8f7a9-26bf-47af-97bd-bd44d7b24919" start_index="0" end="54d637dc-517c-456b-bddd-3ee945668544" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>