<Workspace Version="1.3.1.1736" X="-2" Y="148" zoom="1" ScaleFactor="1" Name="Document.ElementTypes" Description="Retrieves a list of all Revit element types" ID="5e1ec0e8-c357-408d-9927-f95aab5d753e" Category="Clockwork.Revit.Document.Query">
  <NamespaceResolutionMap>
    <ClassMap partialName="Revit.Element" resolvedName="Revit.Elements.Element" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="Revit.Elements.Element" resolvedName="Revit.Elements.Element" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="Revit.Elements.Element.Element" resolvedName="Revit.Elements.Element" assemblyName="RevitNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="088ea15b-c5c0-45a3-8593-67460ce59dd5" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.SortByKey" x="655.700591370788" y="0" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.SortByKey@var[]..[],var[]..[]">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="80960194-b87c-4782-b74d-4ad4aa590693" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Element.Name+" x="407.133202194047" y="77.6561291411593" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <ID value="9266cc47-e982-46fc-9fd4-59bd7fb19a53" />
      <Name value="Element.Name+" />
      <Description value="Gets an element's name (Dynamo's built-in Name nodes don't work for all element types, e.g. worksets...)" />
      <Inputs>
        <Input value="element" />
      </Inputs>
      <Outputs>
        <Output value="name" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <PythonNodeModels.PythonNode guid="e1965a80-a5ff-41c1-b2da-69aeac4b2314" type="PythonNodeModels.PythonNode" nickname="Python Script" x="250" y="1.71014154689667" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" inputcount="0">
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
import Autodesk
clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.Elements)
import System.Reflection
import System.AppDomain

rAssembly = [x for x in System.AppDomain.CurrentDomain.GetAssemblies() if x.GetName().Name == 'RevitAPI'][0]
rElement = [x for x in rAssembly.GetTypes() if x.Name == 'Element' and x.Namespace == 'Autodesk.Revit.DB'][0]
OUT = [x for x in rAssembly.GetTypes() if x.IsClass and x.Namespace == 'Autodesk.Revit.DB' and x.IsSubclassOf(rElement)]</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="a60d9835-1406-4dea-9a6a-794b7cc0f25b" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="945.700591370788" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="elementTypes" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="088ea15b-c5c0-45a3-8593-67460ce59dd5" start_index="0" end="a60d9835-1406-4dea-9a6a-794b7cc0f25b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="80960194-b87c-4782-b74d-4ad4aa590693" start_index="0" end="088ea15b-c5c0-45a3-8593-67460ce59dd5" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e1965a80-a5ff-41c1-b2da-69aeac4b2314" start_index="0" end="80960194-b87c-4782-b74d-4ad4aa590693" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e1965a80-a5ff-41c1-b2da-69aeac4b2314" start_index="0" end="088ea15b-c5c0-45a3-8593-67460ce59dd5" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>