<Workspace Version="1.3.1.1736" X="30" Y="366.786078098472" zoom="1.21561969439728" ScaleFactor="1" Name="Document.IsWorkshared" Description="Returns true if the current project is workshared" ID="070f6953-0854-4645-8eb5-9b4663673b79" Category="Clockwork.Revit.Document.Query">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="8391a372-b113-4e1a-b6ea-aa1f0875826c" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="523" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="bool" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="9360058e-8acd-40b3-8a55-a4891ad83340" type="PythonNodeModels.PythonNode" nickname="Python Script" x="299" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

inputdoc = UnwrapElement(IN[1])
if inputdoc == None:
	doc = DocumentManager.Instance.CurrentDBDocument
elif inputdoc.GetType().ToString() == "Autodesk.Revit.DB.RevitLinkInstance":
	doc = inputdoc.GetLinkDocument()
elif inputdoc.GetType().ToString() == "Autodesk.Revit.DB.Document":
	doc = inputdoc
else: doc = None

if doc.IsWorkshared: OUT = True
else: OUT = False</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="2dd78b85-8bdf-45da-a512-2936e10fd86e" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="7.40363128491623" y="-23.0335195530727" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="toggle : bool = true" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="1bb94522-f9ed-4ec4-a58f-1f3b5499beed" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-212.237430167599" y="60.2276536312851" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="// Use only if you want to query a linked model&#xD;&#xA;docOrRevitLinkInstance : var = null" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="9360058e-8acd-40b3-8a55-a4891ad83340" start_index="0" end="8391a372-b113-4e1a-b6ea-aa1f0875826c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2dd78b85-8bdf-45da-a512-2936e10fd86e" start_index="0" end="9360058e-8acd-40b3-8a55-a4891ad83340" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1bb94522-f9ed-4ec4-a58f-1f3b5499beed" start_index="0" end="9360058e-8acd-40b3-8a55-a4891ad83340" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>