<Workspace Version="1.3.1.1736" X="30" Y="367.481727574751" zoom="1.18936877076412" ScaleFactor="1" Name="Document.Phases" Description="Retrieves all phases in the active document in *chronological* order" ID="4131ba2c-da9b-40bd-9ce1-b74a9ad5b5da" Category="Clockwork.Revit.Document.Query">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="e874cbdc-e1a9-4250-a29f-6462ee786257" type="PythonNodeModels.PythonNode" nickname="Python Script" x="299" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
import Autodesk

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

inputdoc = UnwrapElement(IN[1])
if inputdoc == None:
	doc = DocumentManager.Instance.CurrentDBDocument
elif inputdoc.GetType().ToString() == "Autodesk.Revit.DB.RevitLinkInstance":
	doc = inputdoc.GetLinkDocument()
elif inputdoc.GetType().ToString() == "Autodesk.Revit.DB.Document":
	doc = inputdoc
else: doc = None

elementlist = []
for phase in doc.Phases:
	elementlist.append(phase.ToDSType(True))
OUT = elementlist</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="90287dab-a9bc-4442-822f-66ce34f17eff" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="523" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Phases" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="a2e52334-7c6c-4d47-9124-5797504e17cc" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="18.4972067039106" y="-24.3826815642458" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="toggle : bool = true" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="8b1cc71d-48f2-49e7-befd-c420585ad2db" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-200.106145251397" y="55.0865921787708" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="// Use only if you want to query a linked model&#xD;&#xA;docOrRevitLinkInstance : var = null" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="e874cbdc-e1a9-4250-a29f-6462ee786257" start_index="0" end="90287dab-a9bc-4442-822f-66ce34f17eff" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a2e52334-7c6c-4d47-9124-5797504e17cc" start_index="0" end="e874cbdc-e1a9-4250-a29f-6462ee786257" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8b1cc71d-48f2-49e7-befd-c420585ad2db" start_index="0" end="e874cbdc-e1a9-4250-a29f-6462ee786257" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>