<Workspace Version="1.3.2.2480" X="114.842273338013" Y="331.215080490699" zoom="0.471913125459589" ScaleFactor="1" Name="Element.CopyByVector" Description="Copies an element or a list of elements by a given vector." ID="baf73550-ccd9-4c94-8543-5eb088bfd742" Category="Clockwork.Revit.Elements.Element.Actions">
  <NamespaceResolutionMap>
    <ClassMap partialName="List" resolvedName="DSCore.List" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="Level" resolvedName="Revit.Elements.Level" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="Vector" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="a322c46d-7e6d-407d-b51a-37c7e0d978fd" type="PythonNodeModels.PythonNode" nickname="Python Script" x="491.938130562526" y="49.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>import clr
from System.Collections.Generic import *
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
import Autodesk

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
items = UnwrapElement(IN[0])
xyz = UnwrapElement(IN[1]).ToXyz()
rehost = IN[2]

ids = list()
for item in items:
	ids.append(item.Id)	
itemlist = List[ElementId](ids)

TransactionManager.Instance.EnsureInTransaction(doc)
if rehost:
	newitems = ElementTransformUtils.CopyElements(doc,itemlist,doc,Transform.CreateTranslation(xyz),None)
else:
	newitems = ElementTransformUtils.CopyElements(doc,itemlist,xyz)
TransactionManager.Instance.TransactionTaskDone()

elementlist = list()
for item in newitems:
	elementlist.append(doc.GetElement(item).ToDSType(False))

OUT = elementlist</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="76e7fd82-e446-45ed-88e1-3cd1c149d94c" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="TurnIntoList" x="222.938130562526" y="8.5" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <ID value="cd09ad33-8c34-4850-ac26-24448d92c38f" />
      <Name value="TurnIntoList" />
      <Description value="Turns an element (or a nested list) into a flat list" />
      <Inputs>
        <Input value="unknownItem" />
      </Inputs>
      <Outputs>
        <Output value="seq" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="6beafa4d-8247-4b62-9fe2-504317432db8" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Vector.AsPoint" x="222.938130562526" y="116.5" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Vector.AsPoint">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="39901164-f868-406d-b202-6a462356d2d2" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-35.0618694374735" y="8.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="element" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="f73e03f0-ce11-4fd7-8db1-e5d38b080889" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-35.0618694374735" y="116.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="vector : Vector" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="573c1475-5f36-479d-add1-48e7c9cbd930" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="715.938130562526" y="49.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="newElement" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="d3e0d0bb-df6c-4ecf-a112-1aa6cb230163" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-44.0618694374735" y="248.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="rehostToClosestLevel : bool = false" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="a322c46d-7e6d-407d-b51a-37c7e0d978fd" start_index="0" end="573c1475-5f36-479d-add1-48e7c9cbd930" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="76e7fd82-e446-45ed-88e1-3cd1c149d94c" start_index="0" end="a322c46d-7e6d-407d-b51a-37c7e0d978fd" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6beafa4d-8247-4b62-9fe2-504317432db8" start_index="0" end="a322c46d-7e6d-407d-b51a-37c7e0d978fd" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="39901164-f868-406d-b202-6a462356d2d2" start_index="0" end="76e7fd82-e446-45ed-88e1-3cd1c149d94c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f73e03f0-ce11-4fd7-8db1-e5d38b080889" start_index="0" end="6beafa4d-8247-4b62-9fe2-504317432db8" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d3e0d0bb-df6c-4ecf-a112-1aa6cb230163" start_index="0" end="a322c46d-7e6d-407d-b51a-37c7e0d978fd" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>