<Workspace Version="1.3.2.2480" X="-132.82123694723" Y="274.905717891621" zoom="0.931811528498331" ScaleFactor="1" Name="Element.Category+" Description="Returns the category of a given element. Unlike the OOTB node Element.GetCategory, it will work for families, schedules, subcategories and graphics styles as well." ID="59ab539a-8b69-4b1d-9496-839b33050232" Category="Clockwork.Revit.Elements.Element.Query">
  <NamespaceResolutionMap>
    <ClassMap partialName="Math" resolvedName="DSCore.Math" assemblyName="DSCoreNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="2e1acfe9-550b-4433-b0ca-485276816750" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="285.461111590123" y="181.744630690073" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="element" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="4f6ba5eb-e7f3-472f-bca4-72ef40b1087d" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="697.461111590123" y="181.744630690073" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="category" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="b4b979ee-8b54-4c80-8efd-2356bf9eec69" type="PythonNodeModels.PythonNode" nickname="Python Script" x="473.461111590123" y="181.744630690073" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

def GetCategory(item):
	objtype = item.GetType().ToString()
	returnID = None
	if objtype == "Autodesk.Revit.DB.ViewSchedule": returnID = item.Definition.CategoryId
	elif objtype == "Autodesk.Revit.DB.Family": returnID = item.FamilyCategoryId
	elif objtype == "Autodesk.Revit.DB.GraphicsStyle":  returnID = item.GraphicsStyleCategory.Id
	elif objtype == "Autodesk.Revit.DB.Category": 
		if item.Parent: returnID = item.Parent.Id
	elif hasattr(item, "Category"): returnID = item.Category.Id
	if returnID:
		try: return Revit.Elements.Category.ById(returnID.IntegerValue)
		except: return None
	else: return None

items = UnwrapElement(IN[0])

if isinstance(IN[0], list): OUT = [GetCategory(x) for x in items]
else: OUT = GetCategory(items)</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="2e1acfe9-550b-4433-b0ca-485276816750" start_index="0" end="b4b979ee-8b54-4c80-8efd-2356bf9eec69" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b4b979ee-8b54-4c80-8efd-2356bf9eec69" start_index="0" end="4f6ba5eb-e7f3-472f-bca4-72ef40b1087d" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>