<Workspace Version="1.3.1.1736" X="-81.017391249148" Y="154.399505225983" zoom="1.17546062129157" ScaleFactor="1" Name="Element.ByID" Description="Gets the Revit element(s) for a list of IDs (or a single ID). Optionally retrieves elements from linked documents as well." ID="a4dd8f6e-689f-4998-b8ef-4a04146d12c2" Category="Clockwork.Revit.Selection.Miscellaneous">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="fa29cb8b-f089-477d-b2d6-dca041cf0cd4" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="203.517901997317" y="43.6348627971962" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="ID/UniqueId : var[]..[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="2e336885-b168-45a0-8404-14791edb75f3" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="945.517901997317" y="72.6348627971962" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="element" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="7d81bbbf-ee9c-4ab5-a88a-8cac90cd4fbb" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="203.517901997317" y="127.634862797196" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="// Use only if you want to query a linked model&#xD;&#xA;docOrRevitLinkInstance : var = null" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <PythonNodeModels.PythonNode guid="d38901e7-018a-498d-9dd8-ce194a40dcbe" type="PythonNodeModels.PythonNode" nickname="Python Script" x="721.517901997317" y="72.6348627971962" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

def ElementById(item, doc):
	try: 
		return doc.GetElement(item).ToDSType(True)
	except:
		try:
			return doc.GetElement(ElementId(item)).ToDSType(True)
		except:
			return None

items = UnwrapElement(IN[0])
inputdoc = UnwrapElement(IN[1])
if not inputdoc: doc = DocumentManager.Instance.CurrentDBDocument
elif inputdoc.GetType().ToString() == "Autodesk.Revit.DB.RevitLinkInstance": doc = inputdoc.GetLinkDocument()
elif inputdoc.GetType().ToString() == "Autodesk.Revit.DB.Document": doc = inputdoc
else: doc = DocumentManager.Instance.CurrentDBDocument

if isinstance(IN[0], list): OUT = [ElementById(x, doc) for x in items]
else: OUT = ElementById(items, doc)</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="fa29cb8b-f089-477d-b2d6-dca041cf0cd4" start_index="0" end="d38901e7-018a-498d-9dd8-ce194a40dcbe" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7d81bbbf-ee9c-4ab5-a88a-8cac90cd4fbb" start_index="0" end="d38901e7-018a-498d-9dd8-ce194a40dcbe" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d38901e7-018a-498d-9dd8-ce194a40dcbe" start_index="0" end="2e336885-b168-45a0-8404-14791edb75f3" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>