<Workspace Version="1.3.1.1736" X="153" Y="385" zoom="1" ScaleFactor="1" Name="Element.Workset" Description="Retrieves the workset of a given element" ID="35d5bbd0-79d7-43a9-af54-2b366d290d4a" Category="Clockwork.Revit.Elements.Element.Query">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="e295ad66-1e6e-47f9-aa71-ef76096c2d8f" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="356.820070968837" y="168.749571777649" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="element" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="cb693fa3-ded7-4ad1-a6ea-eb0a07cbc985" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="768.820070968837" y="168.749571777649" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="workset" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="45d7aa4e-1c83-4abb-97fe-244854705e2b" type="PythonNodeModels.PythonNode" nickname="Python Script" x="544.820070968837" y="168.749571777649" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

def GetWorkset(item):
	if hasattr(item, "WorksetId"): return item.Document.GetWorksetTable().GetWorkset(item.WorksetId)
	else: return None

items = UnwrapElement(IN[0])

if isinstance(IN[0], list): OUT = [GetWorkset(x) for x in items]
else: OUT = GetWorkset(items)</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="e295ad66-1e6e-47f9-aa71-ef76096c2d8f" start_index="0" end="45d7aa4e-1c83-4abb-97fe-244854705e2b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="45d7aa4e-1c83-4abb-97fe-244854705e2b" start_index="0" end="cb693fa3-ded7-4ad1-a6ea-eb0a07cbc985" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>