<Workspace Version="1.3.1.1736" X="281.874596249512" Y="394.101877604934" zoom="0.982642311367967" ScaleFactor="1" Name="Element.Group" Description="Retrieves the group an element belongs to (if any)" ID="d12b8b5d-946b-407f-8b74-4faf00e43fc5" Category="Clockwork.Revit.Elements.Element.Query">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="bf4f5baf-f491-4961-8056-d30a089f1db8" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="232.796348210027" y="-60.5636216089884" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="element" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="a52e4894-e2ef-470d-af33-865b78da656c" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="644.796348210027" y="-60.5636216089884" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="group" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="801a2af4-c1b6-4408-b3f6-fbb5205baa48" type="PythonNodeModels.PythonNode" nickname="Python Script" x="420.796348210027" y="-60.5636216089884" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

def GetGroup(item):
	if hasattr(item, "GroupId"): return item.Document.GetElement(item.GroupId)
	else: return None

items = UnwrapElement(IN[0])

if isinstance(IN[0], list): OUT = [GetGroup(x) for x in items]
else: OUT = GetGroup(items)</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="bf4f5baf-f491-4961-8056-d30a089f1db8" start_index="0" end="801a2af4-c1b6-4408-b3f6-fbb5205baa48" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="801a2af4-c1b6-4408-b3f6-fbb5205baa48" start_index="0" end="a52e4894-e2ef-470d-af33-865b78da656c" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>