<Workspace Version="1.3.1.1736" X="195.389962425175" Y="157.311437901972" zoom="1.17131835730765" ScaleFactor="1" Name="Element.Name+" Description="Gets an element's name. Unlike the OOTB node, this node should work for all Revit elements that have names and will also return the localized names of system parameters, parameter groups, display unit types, parameter types, unit symbol types and unit types." ID="9266cc47-e982-46fc-9fd4-59bd7fb19a53" Category="Clockwork.Revit.Elements.Element.Query">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="87f38510-c9e9-4c95-8119-d85d995c924f" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="351.41596757146" y="264.501720867205" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="element" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="8f1bdb12-4403-406c-90d6-7cefe95d4b2d" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="763.41596757146" y="264.501720867205" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="name" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="fe1345c4-af28-4ad4-8eee-6a5bbea61e11" type="PythonNodeModels.PythonNode" nickname="Python Script" x="539.41596757146" y="264.501720867205" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

def GetName(item):
	unwrapped = UnwrapElement(item)
	if not unwrapped: return None
	elif unwrapped.GetType().ToString() in ("Autodesk.Revit.DB.BuiltInParameter", "Autodesk.Revit.DB.BuiltInParameterGroup", "Autodesk.Revit.DB.DisplayUnitType", "Autodesk.Revit.DB.ParameterType", "Autodesk.Revit.DB.UnitSymbolType", "Autodesk.Revit.DB.UnitType"): return LabelUtils.GetLabelFor(unwrapped)
	elif unwrapped.GetType().ToString() == "Autodesk.Revit.DB.Parameter": return unwrapped.Definition.Name
	elif hasattr(unwrapped, "Name"): return unwrapped.Name
	elif hasattr(item, "Name"): return item.Name
	else: return None

items = IN[0]

if isinstance(IN[0], list): OUT = [GetName(x) for x in IN[0]]
else: OUT = GetName(IN[0])</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="87f38510-c9e9-4c95-8119-d85d995c924f" start_index="0" end="fe1345c4-af28-4ad4-8eee-6a5bbea61e11" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="fe1345c4-af28-4ad4-8eee-6a5bbea61e11" start_index="0" end="8f1bdb12-4403-406c-90d6-7cefe95d4b2d" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>