<Workspace Version="1.3.1.1736" X="191" Y="222" zoom="1" ScaleFactor="1" Name="Family.PlacementType" Description="Returns the expected host class of a family (if any)" ID="5674bc6d-91d0-4aa8-8027-83dbef965a18" Category="Clockwork.Revit.Elements.Family.Query">
  <NamespaceResolutionMap>
    <ClassMap partialName="Math" resolvedName="DSCore.Math" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="Family" resolvedName="Revit.Elements.Family" assemblyName="RevitNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="842959c6-5473-4118-b7b7-01d21209ecc7" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="196.811457602108" y="118.256101840112" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="family : Family" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="9a77316f-5cf9-41b0-83fc-376eb35c855d" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="674.811457602108" y="118.256101840112" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="placementType" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="443dcae8-d89c-46a8-911e-d21cb39fd2be" type="PythonNodeModels.PythonNode" nickname="Python Script" x="450.811457602108" y="118.256101840112" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

def GetPlacementType(item):
	if hasattr(item, "FamilyPlacementType"): return item.FamilyPlacementType
	else: return None

items = UnwrapElement(IN[0])

if isinstance(IN[0], list): OUT = [GetPlacementType(x) for x in items]
else: OUT = GetPlacementType(items)</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="842959c6-5473-4118-b7b7-01d21209ecc7" start_index="0" end="443dcae8-d89c-46a8-911e-d21cb39fd2be" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="443dcae8-d89c-46a8-911e-d21cb39fd2be" start_index="0" end="9a77316f-5cf9-41b0-83fc-376eb35c855d" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>