<Workspace Version="1.3.1.1736" X="30.0000000000001" Y="287.028443113772" zoom="1.2185628742515" ScaleFactor="1" Name="Floor.SlabShapeByPoints" Description="Transform a slab shape based on a list of Points" ID="43aab40b-2645-4c59-b2e8-bf17b48b5fb9" Category="Clockwork.Revit.Elements.Floor.Actions">
  <NamespaceResolutionMap>
    <ClassMap partialName="Floor" resolvedName="Revit.Elements.Floor" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="Autodesk.Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="5bb0ff9a-2415-49dc-ba60-3dcc5445ee1c" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="points : Autodesk.Point[]..[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="ef4556c3-fc58-4ae1-9fee-d7d62f9d2795" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="84" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="floor" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="e34a3b6a-6497-4e21-b5f4-d6ace55f2c7b" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="602.820638820639" y="29" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="floor" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="918e92e6-5881-4f86-a959-f72c3eb96d06" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Roof.SlabShapeByPoints" x="340" y="29" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <ID value="d145e1db-d069-452f-b46d-7ad9b0fd906d" />
      <Name value="Roof.SlabShapeByPoints" />
      <Description value="Transform a slab shape based on a list of Points." />
      <Inputs>
        <Input value="points" />
        <Input value="roof" />
      </Inputs>
      <Outputs>
        <Output value="roof" />
        <Output value="success" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="a91fe14c-4fe1-4b47-b1bd-b11494b3e13c" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="599.447174447175" y="101.520884520884" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="success" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="5bb0ff9a-2415-49dc-ba60-3dcc5445ee1c" start_index="0" end="918e92e6-5881-4f86-a959-f72c3eb96d06" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ef4556c3-fc58-4ae1-9fee-d7d62f9d2795" start_index="0" end="918e92e6-5881-4f86-a959-f72c3eb96d06" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="918e92e6-5881-4f86-a959-f72c3eb96d06" start_index="0" end="e34a3b6a-6497-4e21-b5f4-d6ace55f2c7b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="918e92e6-5881-4f86-a959-f72c3eb96d06" start_index="1" end="a91fe14c-4fe1-4b47-b1bd-b11494b3e13c" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>