<Workspace Version="1.3.2.2480" X="226.850067765562" Y="346.976546100149" zoom="0.471913125459589" ScaleFactor="1" Name="Material.Assets" Description="Retrieves all assets from a given material" ID="5a405c02-63c8-4fb6-aa97-8720390aa791" Category="Clockwork.Revit.Elements.Material.Query">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="f82ee752-6d35-4ea2-ac73-0a652c99a088" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="682.41119908191" y="45.5463839701239" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="seq[0];&#xA;seq[1];&#xA;seq[2];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="11e79b2d-1eaf-4cb1-bdda-17568a406d73" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="262.41119908191" y="41.3330506367905" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Material" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="73240b28-e029-473e-85cc-7f24148adfa0" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="903.41119908191" y="-24.0936160298761" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="AppearanceAsset" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="2a089e3e-912d-4ce6-b29c-edb40535ef24" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="903.41119908191" y="58.9063839701239" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="ThermalAsset" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="cd5815f8-1494-4760-8c0b-d8c521070079" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="903.41119908191" y="141.906383970124" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="StructuralAsset" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="0264b073-6e9e-43ac-9935-9748adbc5274" type="PythonNodeModels.PythonNode" nickname="Python Script" x="458.41119908191" y="41.3330506367905" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

mats = UnwrapElement(IN[0])

def GetMaterialAssets(material):
	if hasattr(material, "AppearanceAssetId"): return (material.Document.GetElement(material.AppearanceAssetId), material.Document.GetElement(material.ThermalAssetId), material.Document.GetElement(material.StructuralAssetId))
	else: return (None, None, None)

if isinstance(IN[0], list): OUT = map(list, zip(*[GetMaterialAssets(x) for x in mats]))
else: OUT = GetMaterialAssets(mats)</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="f82ee752-6d35-4ea2-ac73-0a652c99a088" start_index="0" end="73240b28-e029-473e-85cc-7f24148adfa0" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f82ee752-6d35-4ea2-ac73-0a652c99a088" start_index="1" end="2a089e3e-912d-4ce6-b29c-edb40535ef24" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f82ee752-6d35-4ea2-ac73-0a652c99a088" start_index="2" end="cd5815f8-1494-4760-8c0b-d8c521070079" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="11e79b2d-1eaf-4cb1-bdda-17568a406d73" start_index="0" end="0264b073-6e9e-43ac-9935-9748adbc5274" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0264b073-6e9e-43ac-9935-9748adbc5274" start_index="0" end="f82ee752-6d35-4ea2-ac73-0a652c99a088" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>