<Workspace Version="1.3.1.1736" X="214.413443777226" Y="145.553399941166" zoom="0.899691736191744" ScaleFactor="1" Name="ModelCurve.Type" Description="Gets the type of a given model curve" ID="c7d59894-4fec-48c7-9ff1-3912148225ef" Category="Clockwork.Revit.Elements.ModelCurve.Query">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="7d675e6f-ff05-4b4b-89eb-be20b050e79e" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-32.668628703978" y="175.966607950104" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="modelCurve" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="f6657b38-376f-4e7b-9fb8-9538314be35d" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="403.331371296022" y="175.966607950104" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="type" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="0296ff7f-8a93-4d3f-b88d-9dc867dd0119" type="PythonNodeModels.PythonNode" nickname="Python Script" x="179.331371296022" y="175.966607950104" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

def GetCurveType(item):
	if hasattr(item, "CurveElementType"): return item.CurveElementType
	else: return None

items = UnwrapElement(IN[0])

if isinstance(IN[0], list): OUT = [GetCurveType(x) for x in items]
else: OUT = GetCurveType(items)</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="7d675e6f-ff05-4b4b-89eb-be20b050e79e" start_index="0" end="0296ff7f-8a93-4d3f-b88d-9dc867dd0119" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0296ff7f-8a93-4d3f-b88d-9dc867dd0119" start_index="0" end="f6657b38-376f-4e7b-9fb8-9538314be35d" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>