<Workspace Version="1.3.1.1736" X="333.885045436811" Y="63.899025083586" zoom="1" ScaleFactor="1" Name="RevitBoundingBox.FromDynamoBoundingBox" Description="Turns a Dynamo bounding box into a Revit bounding box." ID="de89b4c8-ede5-4ecb-bb7f-25a5605b2e6f" Category="Clockwork.Revit.Elements.BoundingBox.Create">
  <NamespaceResolutionMap>
    <ClassMap partialName="BoundingBox" resolvedName="Autodesk.DesignScript.Geometry.BoundingBox" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="869b2c81-2a0c-4c2f-a636-de6b0aee396b" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="72.1149545631895" y="202.350974916414" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="DynamoBoundingBox : BoundingBox" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="fa745a47-f3a0-45dd-a5fb-5a06583a1c80" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1014.11495456319" y="189.350974916414" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="RevitBoundingBox" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="8c3c2b23-a2dd-4b5a-a182-d533d10bc7ef" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="BoundingBox.MinPoint" x="458.114954563189" y="148.350974916414" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.BoundingBox.MinPoint">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="5df189c2-d567-40f3-a640-7193e11ec783" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="BoundingBox.MaxPoint" x="458.114954563189" y="256.350974916414" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.BoundingBox.MaxPoint">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="583480e3-c369-4a6a-b0c1-bf5a73ac8606" type="PythonNodeModels.PythonNode" nickname="Python Script" x="790.114954563189" y="189.350974916414" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

def MakeBoundingBox(min, max):
	try:
		newbox = BoundingBoxXYZ()
		newbox.Max = max.ToXyz()
		newbox.Min = min.ToXyz()
		return newbox
	except: return None

doc = DocumentManager.Instance.CurrentDBDocument
TransactionManager.Instance.EnsureInTransaction(doc)
if isinstance(IN[0], list): OUT = [MakeBoundingBox(x, y) for x, y in zip(IN[0], IN[1])]
else: OUT = MakeBoundingBox(IN[0], IN[1])
TransactionManager.Instance.TransactionTaskDone()</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="869b2c81-2a0c-4c2f-a636-de6b0aee396b" start_index="0" end="8c3c2b23-a2dd-4b5a-a182-d533d10bc7ef" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="869b2c81-2a0c-4c2f-a636-de6b0aee396b" start_index="0" end="5df189c2-d567-40f3-a640-7193e11ec783" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8c3c2b23-a2dd-4b5a-a182-d533d10bc7ef" start_index="0" end="583480e3-c369-4a6a-b0c1-bf5a73ac8606" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5df189c2-d567-40f3-a640-7193e11ec783" start_index="0" end="583480e3-c369-4a6a-b0c1-bf5a73ac8606" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="583480e3-c369-4a6a-b0c1-bf5a73ac8606" start_index="0" end="fa745a47-f3a0-45dd-a5fb-5a06583a1c80" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>