<Workspace Version="1.3.1.1736" X="149" Y="204" zoom="1" ScaleFactor="1" Name="Roof.SlabShapeHasBeenModified" Description="Checks if the shape of a roof slab has been modified with the shape editing tools" ID="5522a73c-f9bd-45b1-a63b-5c2262fe1f98" Category="Clockwork.Revit.Elements.Roof.Query">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="8140bed9-2577-4b57-84f8-8195304bdd55" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="208.75" y="28.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="roof" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="4a19ace1-1126-4eeb-baec-f8f1677b06bd" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="595.75" y="28.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="bool" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="705e800a-799e-46d4-9590-09d28ea5ff0c" type="PythonNodeModels.PythonNode" nickname="Python Script" x="371.75" y="28.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

def SlabShapeHasBeenModified(item):
	if hasattr(item, "SlabShapeEditor"):
		if item.SlabShapeEditor.SlabShapeCreases.IsEmpty == True or item.SlabShapeEditor.SlabShapeVertices.IsEmpty == True: return False
		else: return True
	else: return False

items = UnwrapElement(IN[0])

if isinstance(IN[0], list): OUT = [SlabShapeHasBeenModified(x) for x in items]
else: OUT = SlabShapeHasBeenModified(items)</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="8140bed9-2577-4b57-84f8-8195304bdd55" start_index="0" end="705e800a-799e-46d4-9590-09d28ea5ff0c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="705e800a-799e-46d4-9590-09d28ea5ff0c" start_index="0" end="4a19ace1-1126-4eeb-baec-f8f1677b06bd" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>