<Workspace Version="1.3.1.1736" X="30" Y="304.411588411588" zoom="1.28071928071928" ScaleFactor="1" Name="Roof.Kind" Description="Retrieves the roof kind (Basic, Glazed, Other). PLEASE NOTE: Roofs that were created by face will be identified as 'Other'" ID="4d3d6106-8c84-4d80-aa4c-4ef91744e3c4" Category="Clockwork.Revit.Elements.Roof.Query">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="4d7090a5-55aa-4d07-aa91-3d027092bbd0" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="270.486349453978" y="69.7219188767553" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="roof" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="2724754f-5a11-4d34-922f-0d3f831e9f6d" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="657.486349453978" y="69.7219188767553" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="kind" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="20291e61-2b6f-45ee-b789-a8cc6b2ea2fa" type="PythonNodeModels.PythonNode" nickname="Python Script" x="433.486349453978" y="69.7219188767553" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

def GetRoofKind(item):
	if hasattr(item, "CurtainGrids"):
		if item.CurtainGrids: return "Glazed"
		else: return "Basic"
	else: 
		if not item: return None
		elif item.GetType().Name == 'RoofBase': 
			if item.Document.GetElement(item.GetTypeId()).GetCompoundStructure(): return "Basic"
			else: return "Glazed"
		elif item.GetType().Name == 'FamilyInstance': return 'In-Place'
		else: return None

items = UnwrapElement(IN[0])

if isinstance(IN[0], list): OUT = [GetRoofKind(x) for x in items]
else: OUT = GetRoofKind(items)</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="4d7090a5-55aa-4d07-aa91-3d027092bbd0" start_index="0" end="20291e61-2b6f-45ee-b789-a8cc6b2ea2fa" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="20291e61-2b6f-45ee-b789-a8cc6b2ea2fa" start_index="0" end="2724754f-5a11-4d34-922f-0d3f831e9f6d" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>