<Workspace Version="1.3.1.1736" X="30" Y="304.411588411588" zoom="1.28071928071928" ScaleFactor="1" Name="Roof.CreationMethod" Description="Retrieves the creation method of a given roof" ID="4b33f269-13d6-418d-bc2a-5be83f3bd85c" Category="Clockwork.Revit.Elements.Roof.Query">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="4d7090a5-55aa-4d07-aa91-3d027092bbd0" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="272.828783151326" y="81.2971918876755" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="roof" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="2724754f-5a11-4d34-922f-0d3f831e9f6d" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="659.828783151326" y="81.2971918876755" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="creationMethod" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="3fdf8f28-ab49-427a-a048-37c08ddd04fd" type="PythonNodeModels.PythonNode" nickname="Python Script" x="435.828783151326" y="81.2971918876755" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

def GetRoofCreationMethod(item):
	if not item: return None
	elif item.GetType().Name == 'FootPrintRoof': return 'By Footprint'
	elif item.GetType().Name == 'ExtrusionRoof': return 'By Extrusion'
	elif item.GetType().Name == 'RoofBase': return 'By Face'
	elif item.GetType().Name == 'FamilyInstance': return 'In-Place'
	else: return None

roofs = UnwrapElement(IN[0])

if isinstance(IN[0], list): OUT = [GetRoofCreationMethod(x) for x in roofs]
else: OUT = GetRoofCreationMethod(roofs)</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="4d7090a5-55aa-4d07-aa91-3d027092bbd0" start_index="0" end="3fdf8f28-ab49-427a-a048-37c08ddd04fd" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3fdf8f28-ab49-427a-a048-37c08ddd04fd" start_index="0" end="2724754f-5a11-4d34-922f-0d3f831e9f6d" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>