<Workspace Version="1.3.1.1736" X="391.3392333766" Y="234.946805101146" zoom="0.943688925978591" ScaleFactor="1" Name="Roof.SlabShapeByPoints" Description="Transform a slab shape based on a list of Points." ID="d145e1db-d069-452f-b46d-7ad9b0fd906d" Category="Clockwork.Revit.Elements.Roof.Actions">
  <NamespaceResolutionMap>
    <ClassMap partialName="Autodesk.Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="753cd253-79a4-4c4b-ab10-aee58856bc74" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-69.7757259220978" y="-38.4598453845157" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="points : Autodesk.Point[]..[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="8391a372-b113-4e1a-b6ea-aa1f0875826c" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="753.224274077902" y="-51.4598453845157" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="roof" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="386d7dbc-4d19-4934-b5e2-d1bfa63d2158" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-69.7757259220978" y="45.5401546154843" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="roof" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="c1f03f36-e4e1-4dc4-9104-af25bc260631" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.FirstItem" x="490.224274077902" y="-63.4598453845157" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.FirstItem@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="b31bea3e-1863-48c5-80dd-6b97444e2597" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.LastItem" x="490.224274077902" y="44.5401546154843" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.LastItem@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="c357e32b-5d15-4178-bdbb-c6f8e6bb3035" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="753.224274077902" y="32.5401546154843" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="success" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="c7afee10-e851-46dd-a85d-7ec0c9fb92f5" type="PythonNodeModels.PythonNode" nickname="Python Script" x="266.224274077902" y="-9.45984538451572" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

def AddPointToSlabShape(item, point):
	if hasattr(item, "SlabShapeEditor") and hasattr(point, "ToXyz"):
		try:
			item.SlabShapeEditor.DrawPoint(point.ToXyz())
			return True
		except: return False
	else: return False

doc = DocumentManager.Instance.CurrentDBDocument
items = UnwrapElement(IN[1])

TransactionManager.Instance.EnsureInTransaction(doc)
if isinstance(IN[1], list):
	if isinstance(IN[0], list):
		OUT = []
		for item, points in zip(items, IN[0]):
			if isinstance(points, list): OUT.append((item, [AddPointToSlabShape(item, x) for x in points]))
			else: OUT.append((item, AddPointToSlabShape(item, points)))
	else: OUT = [(x, AddPointToSlabShape(x, IN[0])) for x in items]
	OUT = map(list, zip(*OUT))
else:
	if isinstance(IN[0], list): OUT = items, [AddPointToSlabShape(items, x) for x in IN[0]]
	else: OUT = items, AddPointToSlabShape(items, IN[0])
TransactionManager.Instance.TransactionTaskDone()</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="753cd253-79a4-4c4b-ab10-aee58856bc74" start_index="0" end="c7afee10-e851-46dd-a85d-7ec0c9fb92f5" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="386d7dbc-4d19-4934-b5e2-d1bfa63d2158" start_index="0" end="c7afee10-e851-46dd-a85d-7ec0c9fb92f5" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c1f03f36-e4e1-4dc4-9104-af25bc260631" start_index="0" end="8391a372-b113-4e1a-b6ea-aa1f0875826c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b31bea3e-1863-48c5-80dd-6b97444e2597" start_index="0" end="c357e32b-5d15-4178-bdbb-c6f8e6bb3035" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c7afee10-e851-46dd-a85d-7ec0c9fb92f5" start_index="0" end="c1f03f36-e4e1-4dc4-9104-af25bc260631" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c7afee10-e851-46dd-a85d-7ec0c9fb92f5" start_index="0" end="b31bea3e-1863-48c5-80dd-6b97444e2597" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>