<Workspace Version="1.3.1.1736" X="352.907190824699" Y="300.600541109339" zoom="0.505499004765837" ScaleFactor="1" Name="Subcategory.ByName" Description="Creates a new subcategory for a given element category (unless a subcategory of that name already exists - in that case it returns the existing subcategory)." ID="c228eea3-78a1-4aca-8fab-8678c97f17c0" Category="Clockwork.Revit.Elements.Subcategory.Create">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="d6d71d1f-01c6-41d4-b96d-c508f552dfe6" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="388.7300607589" y="137.021307324387" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="category" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="f7e2d305-757e-4518-af0c-2158ef95c640" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="388.7300607589" y="221.021307324387" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="name : string" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="bbf8d8cc-b3aa-492f-ba7f-c4d5c2147b92" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="849.7300607589" y="166.021307324387" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="subCategory" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="cbe4eace-d62f-451c-9adf-5b69faf85052" type="PythonNodeModels.PythonNode" nickname="Python Script" x="625.7300607589" y="166.021307324387" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
cat = UnwrapElement(IN[0])
subcatname = IN[1]
subcat = [x for x in cat.SubCategories if x.Name == subcatname]
if len(subcat) == 1: subcat = subcat[0]
else:
	TransactionManager.Instance.EnsureInTransaction(doc)
	try: subcat = doc.Settings.Categories.NewSubcategory(cat, subcatname)
	except: subcat = None
	TransactionManager.Instance.TransactionTaskDone()
OUT = subcat</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="d6d71d1f-01c6-41d4-b96d-c508f552dfe6" start_index="0" end="cbe4eace-d62f-451c-9adf-5b69faf85052" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f7e2d305-757e-4518-af0c-2158ef95c640" start_index="0" end="cbe4eace-d62f-451c-9adf-5b69faf85052" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="cbe4eace-d62f-451c-9adf-5b69faf85052" start_index="0" end="bbf8d8cc-b3aa-492f-ba7f-c4d5c2147b92" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>