<Workspace Version="1.3.1.1736" X="-300.642353931828" Y="324.242626406377" zoom="0.939154117974764" ScaleFactor="1" Name="UnitType.DisplayUnitType" Description="Retrieves the display unit type for a given unit type. " ID="896ba009-854c-4290-bd05-42c87ddcdb7c" Category="Clockwork.Revit.Elements.UnitType.Query">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="0b8b9d6e-eb6e-48a4-82ca-100cf22959c2" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1002" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="displayUnitType" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="82ef5a2b-909a-4de6-b9a3-032388240f02" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1002" y="84" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="unitSymbol" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="9f543a24-6050-4acf-8008-cd1d6c618f42" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="774" y="37.4366666666667" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="seq[0];&#xA;seq[1];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <PythonNodeModels.PythonNode guid="4c659fc2-17fc-4335-8ed1-1becc5063311" type="PythonNodeModels.PythonNode" nickname="Python Script" x="550" y="33.2183333333333" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

dynunittype = IN[0]

if str(dynunittype) == 'DynamoUnits.Area':
	unittype = UnitType.UT_Area
elif str(dynunittype) == 'DynamoUnits.Length':
	unittype = UnitType.UT_Length
elif str(dynunittype) == 'DynamoUnits.Volume':
	unittype = UnitType.UT_Volume
else:
	unittype = None

doc = DocumentManager.Instance.CurrentDBDocument
formatoptions = doc.GetUnits().GetFormatOptions(unittype)
dispunits = formatoptions.DisplayUnits
symtype = formatoptions.UnitSymbol
if symtype == UnitSymbolType.UST_NONE:
	dispsym = None
else:
	dispsym = LabelUtils.GetLabelFor(symtype)
OUT = (dispunits,dispsym)</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="8b667420-e63c-4ba0-8039-cdc15097c99d" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="386.019200034436" y="33.2183333333333" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="unitType" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="9f543a24-6050-4acf-8008-cd1d6c618f42" start_index="0" end="0b8b9d6e-eb6e-48a4-82ca-100cf22959c2" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9f543a24-6050-4acf-8008-cd1d6c618f42" start_index="1" end="82ef5a2b-909a-4de6-b9a3-032388240f02" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4c659fc2-17fc-4335-8ed1-1becc5063311" start_index="0" end="9f543a24-6050-4acf-8008-cd1d6c618f42" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8b667420-e63c-4ba0-8039-cdc15097c99d" start_index="0" end="4c659fc2-17fc-4335-8ed1-1becc5063311" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>