<Workspace Version="1.3.0.875" X="30" Y="299.27579281647" zoom="1.46780551905388" ScaleFactor="1" Name="UV.RoundDownToPrecision" Description="Rounds a UV coordinate *down* to a specified precision" ID="78f6e079-065d-4551-8bac-25631bf471d8" Category="Clockwork.Geometry.UV.Actions">
  <NamespaceResolutionMap>
    <ClassMap partialName="Math" resolvedName="DSCore.Math" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="UV" resolvedName="Autodesk.DesignScript.Geometry.UV" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="0f4478a4-0043-4c64-9f92-03784bb7ff13" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="uv : UV" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="fe9a8650-8bc5-44c2-9a4e-aba62d053e0e" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="692" y="68.1266666666667" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="uv" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="325c9c10-55b8-4128-8851-ed072e2f79dc" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="83.5633333333333" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Precision : double" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="8aee3c71-9bd7-470b-99c6-dd754ddf72f4" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="282" y="37.2183333333333" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="a = {uc.U,uc.V};&#xA;ar = Math.Floor(a/pr)*pr;&#xA;UV.ByCoordinates(ar[0],ar[1]);" ShouldFocus="false">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="0f4478a4-0043-4c64-9f92-03784bb7ff13" start_index="0" end="8aee3c71-9bd7-470b-99c6-dd754ddf72f4" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="325c9c10-55b8-4128-8851-ed072e2f79dc" start_index="0" end="8aee3c71-9bd7-470b-99c6-dd754ddf72f4" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8aee3c71-9bd7-470b-99c6-dd754ddf72f4" start_index="2" end="fe9a8650-8bc5-44c2-9a4e-aba62d053e0e" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>