<Workspace Version="1.3.1.1736" X="437.548906106798" Y="306.236743548049" zoom="0.755143051356643" ScaleFactor="1" Name="View.Duplicate" Description="Duplicates a given view" ID="237e943c-c1a0-4936-9269-1b5ad1dc8b4c" Category="Clockwork.Revit.Views.View.Actions">
  <NamespaceResolutionMap>
    <ClassMap partialName="View" resolvedName="Revit.Elements.Views.View" assemblyName="RevitNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="426563f5-9c8e-4016-8c0c-a9f1debb81fb" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="209.26577515706" y="186.7999865782" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="view" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="c6ad3ceb-20c6-4892-be23-446170905627" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="720.26577515706" y="215.7999865782" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="view" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="6d7b32fb-c733-4519-af8c-c6159799483a" type="PythonNodeModels.PythonNode" nickname="Python Script" x="496.26577515706" y="215.7999865782" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
import Autodesk

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

def DuplicateView(view, name, doc):
	try:
		newViewId = view.Duplicate(Autodesk.Revit.DB.ViewDuplicateOption.Duplicate)
		newView = doc.GetElement(newViewId)
		try: newView.Name = name
		except: pass
		return newView
	except: return None

doc = DocumentManager.Instance.CurrentDBDocument
views = UnwrapElement(IN[0])

TransactionManager.Instance.EnsureInTransaction(doc)
if isinstance(IN[0], list):
	OUT = []
	for view, name in zip(views, IN[1]):
		if isinstance(name, list): OUT.append([DuplicateView(view, x, doc) for x in name])
		else: OUT.append(DuplicateView(view, name, doc))
else: 
	if isinstance(IN[1], list): OUT = [DuplicateView(views, x, doc) for x in IN[1]]
	else: OUT = DuplicateView(views, IN[1], doc)
TransactionManager.Instance.TransactionTaskDone()</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="25c42aef-7c4e-4223-ac0f-39bc94a8d5c3" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="194.698998729417" y="291.988025018408" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="name : string[]..[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="426563f5-9c8e-4016-8c0c-a9f1debb81fb" start_index="0" end="6d7b32fb-c733-4519-af8c-c6159799483a" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6d7b32fb-c733-4519-af8c-c6159799483a" start_index="0" end="c6ad3ceb-20c6-4892-be23-446170905627" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="25c42aef-7c4e-4223-ac0f-39bc94a8d5c3" start_index="0" end="6d7b32fb-c733-4519-af8c-c6159799483a" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>