<Workspace Version="1.3.1.1736" X="224.459907634555" Y="335.855180815734" zoom="0.945969319358178" ScaleFactor="1" Name="View3D.IsLocked" Description="Checks if a given 3D view is locked. PLEASE NOTE: Due to a bug in DynamoRevit this currently only works for isometric view, not for perspective views." ID="76a987d5-ecf6-4340-a9be-3e992068314b" Category="Clockwork.Revit.Views.View3D.Query">
  <NamespaceResolutionMap>
    <ClassMap partialName="Autodesk.View3D" resolvedName="Autodesk.Revit.DB.View3D" assemblyName="" />
    <ClassMap partialName="View" resolvedName="Revit.Elements.Views.View" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="Elements.View3D" resolvedName="Revit.Elements.Views.View3D" assemblyName="RevitNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="0368d3bb-b96b-431a-b2a7-0e280a656216" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="142.352574102964" y="83.2878286881272" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="view3d : Elements.View3D" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="dfc0bccd-15b4-453d-b0a0-8b2030e49f1e" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="694.352574102964" y="83.2878286881272" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="bool" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="79afa201-ce51-4df0-87d9-f6c1bc819a89" type="PythonNodeModels.PythonNode" nickname="Python Script" x="470.352574102964" y="83.2878286881272" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

views = UnwrapElement(IN[0])

if isinstance(IN[0], list): OUT = [x.IsLocked for x in views]
else: OUT = views.IsLocked</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="0368d3bb-b96b-431a-b2a7-0e280a656216" start_index="0" end="79afa201-ce51-4df0-87d9-f6c1bc819a89" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="79afa201-ce51-4df0-87d9-f6c1bc819a89" start_index="0" end="dfc0bccd-15b4-453d-b0a0-8b2030e49f1e" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>