<Workspace Version="1.3.1.1736" X="100" Y="176" zoom="1" ScaleFactor="1" Name="View.Direction" Description="Returns the direction of a view" ID="07195267-53da-4fa3-8410-62807cdbab46" Category="Clockwork.Revit.Views.View.Query">
  <NamespaceResolutionMap>
    <ClassMap partialName="Plane" resolvedName="Autodesk.DesignScript.Geometry.Plane" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="788d7d58-fa3c-4d89-8bba-7725473064ab" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="360.990694185428" y="233.31641327983" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="view" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="8fb30b93-8ee5-4815-8a6e-e62632447bdf" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="747.990694185428" y="233.31641327983" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="vector" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="542a73da-013c-4c5f-8e34-0ed4e523fb2c" type="PythonNodeModels.PythonNode" nickname="Python Script" x="523.990694185428" y="233.31641327983" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

def ViewDirection(view):
	if hasattr(view, "ViewDirection"):
		return view.ViewDirection.ToVector()
	else: return None

views = UnwrapElement(IN[0])

if isinstance(IN[0], list): OUT = [ViewDirection(x) for x in views]
else: OUT = ViewDirection(views)</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="788d7d58-fa3c-4d89-8bba-7725473064ab" start_index="0" end="542a73da-013c-4c5f-8e34-0ed4e523fb2c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="542a73da-013c-4c5f-8e34-0ed4e523fb2c" start_index="0" end="8fb30b93-8ee5-4815-8a6e-e62632447bdf" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>