<Workspace Version="1.3.1.1736" X="64" Y="170" zoom="1" ScaleFactor="1" Name="View.Phase" Description="Returns the phase of a given view" ID="3ec49111-4bea-4ab6-aaa6-736c8a865a57" Category="Clockwork.Revit.Views.View.Query">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="18587205-51d9-4f3f-9d6e-3457ab1d5939" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="368" y="117" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="view" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="111be0db-044d-4bae-a43f-f74d4f5b389e" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="755" y="117" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="phase" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="3ff00859-515d-4020-b061-b3b8a6e47b60" type="PythonNodeModels.PythonNode" nickname="Python Script" x="531" y="117" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

def GetViewPhase(view):
	try: return view.Document.GetElement(view.get_Parameter(BuiltInParameter.VIEW_PHASE).AsElementId())
	except: return None

views = UnwrapElement(IN[0])

if isinstance(IN[0], list): OUT = [GetViewPhase(x) for x in views]
else: OUT = GetViewPhase(views)</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="18587205-51d9-4f3f-9d6e-3457ab1d5939" start_index="0" end="3ff00859-515d-4020-b061-b3b8a6e47b60" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3ff00859-515d-4020-b061-b3b8a6e47b60" start_index="0" end="111be0db-044d-4bae-a43f-f74d4f5b389e" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>