<Workspace Version="1.3.1.1736" X="300" Y="51" zoom="1" ScaleFactor="1" Name="View.SolarStudyTotalFrames" Description="Retrieves the number of frames of a solar study for a given view (if the view's sun and shadow settings are indeed set to single or multi day study)" ID="00af2afb-f2dc-4d29-a9e3-9e614019121e" Category="Clockwork.Revit.Views.View.Query">
  <NamespaceResolutionMap>
    <ClassMap partialName="Revit.View" resolvedName="Revit.Elements.Views.View" assemblyName="RevitNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="ccda5752-042b-4428-bf6c-2706887c5b5b" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="12.25" y="463.449044564025" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="view : Revit.View" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="f47b50f4-ba9f-4d2e-8a1d-ffbcd8b17d77" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="817.25" y="463.449044564025" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="int" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="c1e02154-7f78-4c8e-8d2f-b0cbc464682c" type="PythonNodeModels.PythonNode" nickname="Python Script" x="282.25" y="463.449044564025" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

def GetFrameNum(view):
	if hasattr(view, 'SunAndShadowSettings'):
		if hasattr(view.SunAndShadowSettings, 'NumberOfFrames'): return view.SunAndShadowSettings.NumberOfFrames
		else: return 0
	else: return 0

views = UnwrapElement(IN[0])

if isinstance(views, list): OUT = [GetFrameNum(x) for x in views]
else: OUT = GetFrameNum(views)</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="f168ade5-5e94-4c58-ab00-b8915c3fb35f" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Math.Floor" x="506.25" y="463.449044564025" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.Math.Floor@double">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="ccda5752-042b-4428-bf6c-2706887c5b5b" start_index="0" end="c1e02154-7f78-4c8e-8d2f-b0cbc464682c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c1e02154-7f78-4c8e-8d2f-b0cbc464682c" start_index="0" end="f168ade5-5e94-4c58-ab00-b8915c3fb35f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f168ade5-5e94-4c58-ab00-b8915c3fb35f" start_index="0" end="f47b50f4-ba9f-4d2e-8a1d-ffbcd8b17d77" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>