<Workspace Version="1.3.1.1736" X="30" Y="283.901109989909" zoom="1.29364278506559" ScaleFactor="1" Name="WallType.Kind" Description="Retrieves the wall kind of a given wall type" ID="b8c59c96-a8e9-46bf-b9f7-1041b7439858" Category="Clockwork.Revit.Elements.WallType.Query">
  <NamespaceResolutionMap>
    <ClassMap partialName="WallType" resolvedName="Revit.Elements.WallType" assemblyName="RevitNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="7d675e6f-ff05-4b4b-89eb-be20b050e79e" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="167.760530421217" y="33.4352574102965" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="wallType : WallType" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="f6657b38-376f-4e7b-9fb8-9538314be35d" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="678.760530421217" y="33.4352574102965" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="kind" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="eaa260f4-edab-4800-840e-ca73e37d6f11" type="PythonNodeModels.PythonNode" nickname="Python Script" x="454.760530421217" y="33.4352574102965" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

def WallTypeKind(walltype):
	if hasattr(walltype,"Kind"): return str(walltype.Kind)
	else: return None

walltypes = UnwrapElement(IN[0])

if isinstance(IN[0], list): OUT = [WallTypeKind(x) for x in walltypes]
else: OUT = WallTypeKind(walltypes)</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="7d675e6f-ff05-4b4b-89eb-be20b050e79e" start_index="0" end="eaa260f4-edab-4800-840e-ca73e37d6f11" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="eaa260f4-edab-4800-840e-ca73e37d6f11" start_index="0" end="f6657b38-376f-4e7b-9fb8-9538314be35d" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>