<Workspace Version="1.3.2.2480" X="-26.1725792843384" Y="263.508028903523" zoom="0.994948216942867" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="7a753eb8-28b3-445c-8480-3787b62047b6" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="ElectricalSystem.RemoveFromCircuit" x="218.83231482371" y="58.8866294552926" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <ID value="786eda69-1371-40be-947b-1b87bd5b45e9" />
      <Name value="ElectricalSystem.RemoveFromCircuit" />
      <Description value="Removes the elements from the circuit" />
      <Inputs>
        <Input value="Circuit" />
        <Input value="Elements" />
      </Inputs>
      <Outputs>
        <Output value="Success" />
        <Output value="Failed" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Nodes.DSModelElementsSelection guid="c2906099-8d25-4902-b8c7-766ca3385a78" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="-1028.91654694292" y="47.4828435249263" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="5c7e692d-667f-40d1-83d0-f506f17e20d5" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="ElementFilter.ByCategory" x="-700.760822286041" y="63.7832050486324" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="C:\Users\dcleary\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\Beaker\bin\Beaker.dll" function="Revit.ElementFilter.ByCategory@Revit.Elements.Element[],Revit.Elements.Category">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <DSRevitNodesUI.Categories guid="f852344f-3dbd-41d9-990b-8b9eeadbdaf9" type="DSRevitNodesUI.Categories" nickname="Categories" x="-1023.57002717362" y="297.649195897037" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="249:LightingFixtures" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="f530285a-ac6b-4156-89f8-dff4a1f9f173" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="ElementFilter.ByNameBeginsWith" x="-394.454922404855" y="113.018220432892" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="C:\Users\dcleary\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\Beaker\bin\Beaker.dll" function="Revit.ElementFilter.ByNameBeginsWith@Revit.Elements.Element[],string">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="cdeb0729-3591-4f28-9db5-766ec9b3622a" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="-710" y="193" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="&quot;L&quot;;" ShouldFocus="false" />
    <PythonNodeModels.PythonNode guid="eea9127a-196b-4eef-8972-b24263c985ea" type="PythonNodeModels.PythonNode" nickname="Python Script" x="-57.3653196941108" y="-89.8734011954757" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

#The inputs to this node will be stored as a list in the IN variables.
if isinstance(IN[0],list):
	toggle = 0
	element = UnwrapElement(IN[0])
else:
	toggle = 1
	element = [UnwrapElement(IN[0])]

def getSystem(elem):
	system = elem.MEPModel.ElectricalSystems
	
	if system.Size == 0:
		return None
	elif system.Size == 1:	
		for sys in system:
			return sys
	else:
		return [x for x in system]

listout = []	
for x in element:
	try:
		system = getSystem(x)
		listout.append(system)
	except:
		listout.append(None)
#Assign your output to the OUT variable.
if toggle:
	OUT = system
else:
	OUT = listout</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="c2906099-8d25-4902-b8c7-766ca3385a78" start_index="0" end="5c7e692d-667f-40d1-83d0-f506f17e20d5" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5c7e692d-667f-40d1-83d0-f506f17e20d5" start_index="0" end="f530285a-ac6b-4156-89f8-dff4a1f9f173" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f852344f-3dbd-41d9-990b-8b9eeadbdaf9" start_index="0" end="5c7e692d-667f-40d1-83d0-f506f17e20d5" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f530285a-ac6b-4156-89f8-dff4a1f9f173" start_index="0" end="7a753eb8-28b3-445c-8480-3787b62047b6" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f530285a-ac6b-4156-89f8-dff4a1f9f173" start_index="0" end="eea9127a-196b-4eef-8972-b24263c985ea" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="cdeb0729-3591-4f28-9db5-766ec9b3622a" start_index="0" end="f530285a-ac6b-4156-89f8-dff4a1f9f173" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="eea9127a-196b-4eef-8972-b24263c985ea" start_index="0" end="7a753eb8-28b3-445c-8480-3787b62047b6" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="29825400-c21e-4ba6-9a6b-8043901aa078" annotationText="Get Electrical Circuit from Element" left="-67.3653196941108" top="-279.873401195476" width="144" height="283" fontSize="30" InitialTop="-89.8734011954757" InitialHeight="123" TextblockHeight="180" backgrouund="#FFC1D676">
      <Models ModelGuid="eea9127a-196b-4eef-8972-b24263c985ea" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>