<Workspace Version="1.2.1.3083" X="0" Y="0" zoom="1" Name="Copy element to location" Description="This node will copy level-hosted elements to the given locations and rehost to the nearest level.(does not work for curve based elements) " ID="b53c45a6-02b9-4f70-9e52-3667cc4c9761" Category="MEPover.Revit.Elements">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="68ec4a51-6d3b-4070-8e9c-3a2f9d571a84" type="PythonNodeModels.PythonNode" nickname="Python Script" x="981.61983494987" y="501.514813930651" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

from System.Collections.Generic import List
#The inputs to this node will be stored as a list in the IN variables.
if isinstance(IN[0],list):
	elements = UnwrapElement(IN[0])
else:
	elements = [UnwrapElement(IN[0])]
if isinstance(IN[1], list):
	newlocations = [x.ToXyz() for x in IN[1]]
else:
	newlocations = [IN[1].ToXyz()]

newelements = []

options = CopyPasteOptions()
elementlist = List[ElementId]()
	
TransactionManager.Instance.EnsureInTransaction(doc)
for element,loc in zip(elements,newlocations):
	try:
		oldloc = element.Location.Point
		
		elementlist.Add(element.Id)
		OffsetZ = (oldloc.Z - loc.Z)*-1
		OffsetX = (oldloc.X - loc.X)*-1
		OffsetY = (oldloc.Y - loc.Y)*-1
		direction = XYZ(OffsetX,OffsetY,OffsetZ)
		trans = Transform.CreateTranslation(direction)
		newelementId = ElementTransformUtils.CopyElements(doc,elementlist,doc,trans,options)
		elementlist.Clear()
		newelement = doc.GetElement(newelementId[0])
		newelements.append(newelement.ToDSType(False))
	except:
		newelements.append(None)

TransactionManager.Instance.TransactionTaskDone()
#Assign your output to the OUT variable.
OUT = newelements</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="0eeecf63-c32d-42e4-8560-ef9763767ec0" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="643" y="482" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Element" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="cc04aee5-7453-4a4e-948f-7782c7949206" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="647" y="646" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Location" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="fc1b7c75-a252-4389-8c99-2bd317988d64" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1244" y="527" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="New Element" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="68ec4a51-6d3b-4070-8e9c-3a2f9d571a84" start_index="0" end="fc1b7c75-a252-4389-8c99-2bd317988d64" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0eeecf63-c32d-42e4-8560-ef9763767ec0" start_index="0" end="68ec4a51-6d3b-4070-8e9c-3a2f9d571a84" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="cc04aee5-7453-4a4e-948f-7782c7949206" start_index="0" end="68ec4a51-6d3b-4070-8e9c-3a2f9d571a84" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="152.585494995117" eyeY="2767.08471679688" eyeZ="6472.72265625" lookX="1337.45983886719" lookY="-1448.91479492188" lookZ="-6464.38916015625" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>