<Workspace Version="1.3.1.1736" X="0" Y="0" zoom="1" ScaleFactor="1" Name="Elements change Level" Description="Change the elements to the selected level without moving the elements. Only works for non-hosted (level-hosted) MEP elements." ID="4f35420e-9e02-445f-826f-afce5a6659d3" Category="MEPover.Revit.Parameters">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="3ac70c21-6402-44ae-a7d0-f6b81fccce18" type="PythonNodeModels.PythonNode" nickname="Python Script" x="378" y="267" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

element = UnwrapElement(IN[0])
ref_level = UnwrapElement(IN[1])
listout = []

TransactionManager.Instance.EnsureInTransaction(doc)

for i,x in enumerate(element):
	ref_levelid = ref_level.Id
	
	#familyinstances
	try:
		object_param_level = x.get_Parameter(BuiltInParameter.FAMILY_LEVEL_PARAM)
	
		object_level = doc.GetElement(object_param_level.AsElementId())
	
		object_param_offset = x.get_Parameter(BuiltInParameter.INSTANCE_FREE_HOST_OFFSET_PARAM)
	
		object_newoffset = object_param_offset.AsDouble() + object_level.Elevation - ref_level.Elevation
	
		object_param_level.Set(ref_levelid)
		object_param_offset.Set(object_newoffset)
		listout.append(x)
	#system families
	except:
		try:
			object_param_level = x.get_Parameter(BuiltInParameter.RBS_START_LEVEL_PARAM)
			
			object_param_level.Set(ref_levelid)
			listout.append(x)
		except:
			pass

TransactionManager.Instance.TransactionTaskDone()

OUT = listout</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="5dc6d6e9-40d5-4c61-a899-8ecb0dc8c1a9" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="141" y="240" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Elements" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="755d0fc7-b586-4e31-aa62-ce71c3aa96d1" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="164" y="358" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Level" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="fd92df11-68cd-4bda-b6ee-434cb2bdbabe" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="588" y="271" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Succeeded" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="3ac70c21-6402-44ae-a7d0-f6b81fccce18" start_index="0" end="fd92df11-68cd-4bda-b6ee-434cb2bdbabe" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5dc6d6e9-40d5-4c61-a899-8ecb0dc8c1a9" start_index="0" end="3ac70c21-6402-44ae-a7d0-f6b81fccce18" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="755d0fc7-b586-4e31-aa62-ce71c3aa96d1" start_index="0" end="3ac70c21-6402-44ae-a7d0-f6b81fccce18" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>