<Workspace Version="1.3.1.1736" X="74.0307625" Y="-162.754048191145" zoom="1.33823125" ScaleFactor="1" Name="Elements on Sheet" Description="This node will return elements on sheet." ID="c97ab529-0007-4aff-855b-ee90a0dcfbce" Category="archilab.Revit.Sheet">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="2799c943-505f-48c0-a92f-57a87e5c474f" type="PythonNodeModels.PythonNode" nickname="Python Script" x="350" y="306.076645571851" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Copyright(c) 2015, Konrad Sobon
# @arch_laboratory, http://archi-lab.net

import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import ToDSType(bool) extension method
clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.Elements)

# Import DocumentManager and TransactionManager
clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# Import RevitAPI
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument

#The inputs to this node will be stored as a list in the IN variable.
dataEnteringNode = IN

elements = []
for i in IN[0]:
	elements.append(UnwrapElement(i))

TransactionManager.Instance.EnsureInTransaction(doc)

schName, schId, ids = [], [], []
for i in elements:
	trans = SubTransaction(doc)
	trans.Start()
	ids.append(doc.Delete(i.Id))
	trans.RollBack()

TransactionManager.Instance.TransactionTaskDone()



elementsOnSheet = []
elementsOnSheet1 = []
for i in ids:
	for j in i:
		if doc.GetElement(j) != None:
			elementsOnSheet.append(doc.GetElement(j).GetType())
			elementsOnSheet1.append(doc.GetElement(j))

OUT = elementsOnSheet1</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="9e49e75f-1e54-4b0f-893a-b19a17c972d9" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Transaction.End" x="548.558696530004" y="256" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Transaction.Transaction.End@var">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="5c8b7904-b4b6-4d3c-86c6-8a5b40b25cb0" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="186.5493071545" y="301.465776704246" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Sheets" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="8830807d-f385-4714-a7ac-baa425d0d703" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="739.518011180803" y="298.476756682483" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="OUT" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="2799c943-505f-48c0-a92f-57a87e5c474f" start_index="0" end="9e49e75f-1e54-4b0f-893a-b19a17c972d9" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9e49e75f-1e54-4b0f-893a-b19a17c972d9" start_index="0" end="8830807d-f385-4714-a7ac-baa425d0d703" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5c8b7904-b4b6-4d3c-86c6-8a5b40b25cb0" start_index="0" end="2799c943-505f-48c0-a92f-57a87e5c474f" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
</Workspace>