<Workspace Version="1.3.2.2480" X="-751.239096406088" Y="276.583105548088" zoom="0.185602701480781" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="49c62cc1-f7de-4f38-ba8c-9de88c114546" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.GetLocation" x="5109.86204216157" y="1192.4058615458" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.Element.GetLocation">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="2f541abb-a108-4389-ac2c-25d309d85ce9" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.GetLocation" x="5109.86204216157" y="1302.4058615458" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.Element.GetLocation">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="3d4e331b-08b5-4c8f-bd92-e02b01e23f62" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Vector.ByTwoPoints" x="5455.10494911524" y="1233.93745954727" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Vector.ByTwoPoints@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Nodes.DSModelElementSelection guid="086ee24b-7549-401b-8b29-324d6bbd3e5c" type="Dynamo.Nodes.DSModelElementSelection" nickname="Select Model Element" x="4797.04304477541" y="976.396518140269" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="true">
      <instance id="6ac6cf25-6c05-4841-bc68-40388aa73431-00002657" />
    </Dynamo.Nodes.DSModelElementSelection>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="adba1743-1027-48ab-9936-ff33a39b7256" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="4780.05579185967" y="870.975099262879" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="End Element Location;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="53fa46ae-437b-4d21-b98a-d69d22b05852" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="4483.50352268835" y="887.036476408709" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Origin Element Location;" ShouldFocus="false" />
    <Dynamo.Nodes.DSModelElementSelection guid="bfb63b45-3f9e-4665-aa6b-e135424e5509" type="Dynamo.Nodes.DSModelElementSelection" nickname="Select Model Element" x="4503.0844301981" y="983.307578941969" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="true">
      <instance id="6ac6cf25-6c05-4841-bc68-40388aa73431-00002628" />
    </Dynamo.Nodes.DSModelElementSelection>
    <Dynamo.Nodes.DSModelElementsSelection guid="c43b2eb5-fcc1-4eda-9817-b4997d01fdb9" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="5411.33852262634" y="1431.2938419247" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <instance id="6ac6cf25-6c05-4841-bc68-40388aa73431-00002499" />
      <instance id="6ac6cf25-6c05-4841-bc68-40388aa73431-000025f9" />
      <instance id="6ac6cf25-6c05-4841-bc68-40388aa73431-00002603" />
      <instance id="6ac6cf25-6c05-4841-bc68-40388aa73431-0000260c" />
    </Dynamo.Nodes.DSModelElementsSelection>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="93e2cc88-fbc4-48b6-8e8b-df92418699a6" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Vector.AsPoint" x="5687.22368632082" y="1333.3710482343" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Vector.AsPoint">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="199ad7e1-207c-4c71-af48-2c54dbd3a9c3" type="PythonNodeModels.PythonNode" nickname="Python Script" x="6248.86269880673" y="1512.18155259454" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="4">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <PortInfo index="3" default="False" />
      <Script>import clr

clr.AddReference('RevitServices')
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

from System.Collections.Generic import List

clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

def singleton(x):
	if hasattr(x,'__iter__'): return x[0]
	else : return x

def tolist(x):
	if hasattr(x,'__iter__'): return x
	else : return [x]


source = UnwrapElement(singleton(IN[0]) )
dest = UnwrapElement(singleton(IN[1]) )
elements = UnwrapElement(tolist(IN[2]) )
tf1 = singleton(IN[3])

if tf1 is not None:
	tf1 = tf1.ToTransform(True)

eId = List[ElementId](e.Id for e in elements if hasattr(e, "Id") )

TransactionManager.Instance.EnsureInTransaction(doc)
copy = ElementTransformUtils.CopyElements(source, eId, dest, tf1, None)
TransactionManager.Instance.TransactionTaskDone()

OUT = [doc.GetElement(i).ToDSType(False) for i in copy]</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="3c82de92-4a15-4ae1-b8e0-50134dcea64f" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="CoordinateSystem.ByOrigin" x="5913.12354146216" y="1444.40166011699" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.CoordinateSystem.ByOrigin@Autodesk.DesignScript.Geometry.Point">
      <PortInfo index="0" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <DSRevitNodesUI.Views guid="1b8ffa10-6322-4d80-944a-9b12137946f6" type="DSRevitNodesUI.Views" nickname="Views" x="5474.97627012381" y="1593.84748428417" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="3:Level 1 Orignal" />
    <DSRevitNodesUI.Views guid="054d7b6f-8234-48a9-a007-1ad1454cdeac" type="DSRevitNodesUI.Views" nickname="Views" x="5424.47494529461" y="1704.42634704892" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="5:Level 1 Duplicate Elements and tags" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="49c62cc1-f7de-4f38-ba8c-9de88c114546" start_index="0" end="3d4e331b-08b5-4c8f-bd92-e02b01e23f62" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2f541abb-a108-4389-ac2c-25d309d85ce9" start_index="0" end="3d4e331b-08b5-4c8f-bd92-e02b01e23f62" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3d4e331b-08b5-4c8f-bd92-e02b01e23f62" start_index="0" end="93e2cc88-fbc4-48b6-8e8b-df92418699a6" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="086ee24b-7549-401b-8b29-324d6bbd3e5c" start_index="0" end="2f541abb-a108-4389-ac2c-25d309d85ce9" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="bfb63b45-3f9e-4665-aa6b-e135424e5509" start_index="0" end="49c62cc1-f7de-4f38-ba8c-9de88c114546" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c43b2eb5-fcc1-4eda-9817-b4997d01fdb9" start_index="0" end="199ad7e1-207c-4c71-af48-2c54dbd3a9c3" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="93e2cc88-fbc4-48b6-8e8b-df92418699a6" start_index="0" end="3c82de92-4a15-4ae1-b8e0-50134dcea64f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3c82de92-4a15-4ae1-b8e0-50134dcea64f" start_index="0" end="199ad7e1-207c-4c71-af48-2c54dbd3a9c3" end_index="3" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1b8ffa10-6322-4d80-944a-9b12137946f6" start_index="0" end="199ad7e1-207c-4c71-af48-2c54dbd3a9c3" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="054d7b6f-8234-48a9-a007-1ad1454cdeac" start_index="0" end="199ad7e1-207c-4c71-af48-2c54dbd3a9c3" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="1f4915c0-d22d-469c-96dc-64783dd0332b" annotationText="" left="4770.05579185967" top="824.975099262879" width="204" height="139" fontSize="30" InitialTop="870.975099262879" InitialHeight="123" TextblockHeight="36" backgrouund="#FFFF7BAC">
      <Models ModelGuid="adba1743-1027-48ab-9936-ff33a39b7256" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="dff7aaf1-c9c3-4144-8800-7a8f6ccb74dd" annotationText="" left="4473.50352268835" top="841.036476408709" width="229" height="139" fontSize="30" InitialTop="887.036476408709" InitialHeight="123" TextblockHeight="36" backgrouund="#FFFF7BAC">
      <Models ModelGuid="53fa46ae-437b-4d21-b98a-d69d22b05852" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="e06a3d54-d5f7-45a4-9579-ea3d1230545f" annotationText="COPY ELEMENTS TO FROM START POINT TO END POINT" left="5099.86204216157" top="1110.4058615458" width="551.24290695367" height="285" fontSize="30" InitialTop="1192.4058615458" InitialHeight="374.48192323169" TextblockHeight="72" backgrouund="#FFC1D676">
      <Models ModelGuid="49c62cc1-f7de-4f38-ba8c-9de88c114546" />
      <Models ModelGuid="2f541abb-a108-4389-ac2c-25d309d85ce9" />
      <Models ModelGuid="3d4e331b-08b5-4c8f-bd92-e02b01e23f62" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>