<Workspace Version="1.3.1.1736" X="111.375162059612" Y="121.587300427128" zoom="1.78359936238281" ScaleFactor="1" Name="ViewInstance.ByPoint" Description="Places a view hosted family instance at a given point in the view (e.g. a detail component, 2d annotation)." ID="e2913a86-189d-49b7-b162-aff744bc796a" Category="Springs.Revit.FamilyInstance">
  <NamespaceResolutionMap>
    <ClassMap partialName="String" resolvedName="DSCore.String" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="Math" resolvedName="DSCore.Math" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="List" resolvedName="DSCore.List" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="Line" resolvedName="Autodesk.DesignScript.Geometry.Line" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="5480587a-28b7-436b-aeb5-09a81ece3490" type="PythonNodeModels.PythonNode" nickname="Python Script" x="211.314182178324" y="28.0332013200555" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>#Copyright(c) 2016, Dimitar Venkov
# @5devene, dimitar.ven@gmail.com

import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
import Autodesk

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

def tolist(obj1):
	if hasattr(obj1,"__iter__"): return obj1
	else: return [obj1]

view = UnwrapElement(tolist(IN[0]))
ftype = UnwrapElement(tolist(IN[1]))
fpts = UnwrapElement(tolist(IN[2]))

OUT = []
ftp_len = len(ftype) == 1
view_len = len(view) == 1

TransactionManager.Instance.EnsureInTransaction(doc)
for i in xrange(len(fpts) ):
	p = fpts[i].ToXyz(True)
	j = 0 if ftp_len else i
	k = 0 if view_len else i
	try:
		if not ftype[j].IsActive : ftype[j].Activate()
		nf = doc.Create.NewFamilyInstance(p, ftype[j], view[k])
		OUT.append(nf.ToDSType(False) )
	except:
		OUT.append(None)
TransactionManager.Instance.TransactionTaskDone()</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="408fb051-1893-40c8-bc9c-8e5c530be55c" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="367.385708251042" y="28.0332013200555" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="FamilyInstance" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="016437ac-3431-4081-b36d-1b89eb229ebf" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="45.7093427014639" y="-7.62599464684206" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="view: var[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="d51f8505-36dd-4e3f-bf0c-37bbcb293a04" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="46.7454383912838" y="52.7178720231111" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="type: var[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="8f4b9b73-2aae-454d-9745-40d6b6d9ed04" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="41.6439212956633" y="122.410770208717" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="point: var[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="5480587a-28b7-436b-aeb5-09a81ece3490" start_index="0" end="408fb051-1893-40c8-bc9c-8e5c530be55c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="016437ac-3431-4081-b36d-1b89eb229ebf" start_index="0" end="5480587a-28b7-436b-aeb5-09a81ece3490" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d51f8505-36dd-4e3f-bf0c-37bbcb293a04" start_index="0" end="5480587a-28b7-436b-aeb5-09a81ece3490" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8f4b9b73-2aae-454d-9745-40d6b6d9ed04" start_index="0" end="5480587a-28b7-436b-aeb5-09a81ece3490" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="81.9612025848931" eyeY="60.6141246867221" eyeZ="62.2681174153678" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>